ALTER ROLE [db_owner] ADD MEMBER [AAFV]
GO
ALTER ROLE [db_owner] ADD MEMBER [ACCJ]
GO
ALTER ROLE [db_owner] ADD MEMBER [admin]
GO
ALTER ROLE [db_owner] ADD MEMBER [BEFA]
GO
ALTER ROLE [db_owner] ADD MEMBER [BEMC]
GO
ALTER ROLE [db_owner] ADD MEMBER [CARM1]
GO
ALTER ROLE [db_owner] ADD MEMBER [CARR1]
GO
ALTER ROLE [db_owner] ADD MEMBER [CAVB]
GO
ALTER ROLE [db_owner] ADD MEMBER [CEBTMW]
GO
ALTER ROLE [db_owner] ADD MEMBER [CUCG1]
GO
ALTER ROLE [db_owner] ADD MEMBER [eleos]
GO
ALTER ROLE [db_owner] ADD MEMBER [ESMR1]
GO
ALTER ROLE [db_owner] ADD MEMBER [ESTAT]
GO
ALTER ROLE [db_owner] ADD MEMBER [FECJ]
GO
ALTER ROLE [db_owner] ADD MEMBER [GOBJ]
GO
ALTER ROLE [db_owner] ADD MEMBER [LUAL]
GO
ALTER ROLE [db_owner] ADD MEMBER [LUVA]
GO
ALTER ROLE [db_owner] ADD MEMBER [MACK]
GO
ALTER ROLE [db_owner] ADD MEMBER [MATAN]
GO
ALTER ROLE [db_owner] ADD MEMBER [MIUR]
GO
ALTER ROLE [db_owner] ADD MEMBER [MOMJ]
GO
ALTER ROLE [db_owner] ADD MEMBER [MOPE]
GO
ALTER ROLE [db_owner] ADD MEMBER [MOPM2]
GO
ALTER ROLE [db_owner] ADD MEMBER [NAOO]
GO
ALTER ROLE [db_owner] ADD MEMBER [OEYE]
GO
ALTER ROLE [db_owner] ADD MEMBER [ORLE]
GO
ALTER ROLE [db_owner] ADD MEMBER [ORLJ]
GO
ALTER ROLE [db_owner] ADD MEMBER [PEPB]
GO
ALTER ROLE [db_owner] ADD MEMBER [RAOC]
GO
ALTER ROLE [db_owner] ADD MEMBER [REMM]
GO
ALTER ROLE [db_owner] ADD MEMBER [ROAVM]
GO
ALTER ROLE [db_owner] ADD MEMBER [ROMG]
GO
ALTER ROLE [db_owner] ADD MEMBER [satdr]
GO
ALTER ROLE [db_owner] ADD MEMBER [SEAG]
GO
ALTER ROLE [db_owner] ADD MEMBER [SOSE]
GO
ALTER ROLE [db_owner] ADD MEMBER [sysdba]
GO
ALTER ROLE [db_owner] ADD MEMBER [TDR\Administrator]
GO
ALTER ROLE [db_owner] ADD MEMBER [TDR\emolvera]
GO
ALTER ROLE [db_owner] ADD MEMBER [Totalmail]
GO
ALTER ROLE [db_owner] ADD MEMBER [VIMA2]
GO
