SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

 CREATE view [dbo].[vista_drivertmt]
 as

SELECT [MPP_ID]
,[MPP_TRACTORNUMBER]
,[MPP_FIRSTNAME]
,[MPP_LASTNAME]
,[MPP_ADDRESS1]
,[MPP_ADDRESS2]
,[CTY_NAME]
,[CTY_STATE]
,[MPP_ZIP]
,[MPP_HIREDATE]
,[MPP_LICENSENUMBER]
,[MPP_LICENSESTATE]
,[MPP_LICENSECLASS]
,[MPP_CURRENTPHONE]
,[MPP_ALTERNATEPHONE]
,[MPP_HOMEPHONE]
,[MPP_EMERPHONE]
,[MPP_EMERNAME]
,[MPP_TERMINATIONDT]
,[MPP_VOICEMAILBOX]
,[MPP_EMAIL]
,[MPP_COMPANY]
,[MPP_DIVISION]
,m.timestamp
FROM [MANPOWERPROFILE] M
INNER JOIN [CITY] C ON M.[MPP_CITY] = C.[CTY_CODE]
WHERE C.[CTY_NAME] <> 'UNKNOWN'
GO
