SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[TMWScrollLegHeaderActiveView] AS

SELECT  
	orderheader.ord_number, 
	orderheader.ord_company as 'ord_company',
	company_legstart.cmp_id as 'origin_cmp_id', 
	company_legstart.cmp_name as 'origin_cmp_name', 
	company_legend.cmp_id as 'dest_cmp_id', 
	company_legend.cmp_name as 'dest_cmp_name', 
	company_orderby.cmp_id as 'orderby_cmp_id', 
	company_orderby.cmp_name as 'orderby_cmp_name', 
	company_orderby.cty_nmstct as 'orderby_cty_nmstct', 
	company_billto.cmp_id as 'billto_cmp_id', 
	company_billto.cmp_name as 'billto_cmp_name', 
	company_billto.cty_nmstct as 'billto_cty_nmstct',
	(select name from labelfile where labeldefinition = 'DispStatus' and abbr = orderheader.ord_status) as 'ord_status_name', 
	orderheader.ord_startdate, 
	orderheader.ord_completiondate, 
	orderheader.ord_originstate, 
	orderheader.ord_deststate, 
	orderheader.ord_revtype1 as 'ord_revtype1', 
	(select name from labelfile where labeldefinition = 'RevType1' and abbr = orderheader.ord_revtype1) as 'ord_revtype1_name',
	orderheader.ord_revtype2 as 'ord_revtype2', 
	(select name from labelfile where labeldefinition = 'RevType2' and abbr = orderheader.ord_revtype2) as 'ord_revtype2_name',
	orderheader.ord_revtype3 as 'ord_revtype3', 
	(select name from labelfile where labeldefinition = 'RevType3' and abbr = orderheader.ord_revtype3) as 'ord_revtype3_name', 
	orderheader.ord_revtype4 as 'ord_revtype4', 
	(select name from labelfile where labeldefinition = 'RevType4' and abbr = orderheader.ord_revtype4) as 'ord_revtype4_name', 
	orderheader.mov_number, 
	orderheader.ord_charge, 
	orderheader.ord_totalcharge, 
	orderheader.ord_accessorial_chrg, 
	orderheader.ord_priority, 
	orderheader.ord_originregion1, 
	orderheader.ord_destregion1, 
	orderheader.ord_reftype, 
	orderheader.ord_refnum, 
	orderheader.ord_status as 'ord_status', 
	orderheader.ord_invoicestatus as 'ord_invoicestatus', 
	(select name from labelfile where labeldefinition = 'OrdInvStatus' and abbr = orderheader.ord_invoicestatus) as 'ord_invoicestatus_name', 
	(CASE company_legstart.cty_nmstct WHEN 'UNKNOWN' THEN city_legstart.cty_nmstct ELSE company_legstart.cty_nmstct  END) as 'origin_cty_nmstct', 
	(CASE company_legend.cty_nmstct WHEN 'UNKNOWN' THEN city_legend.cty_nmstct ELSE company_legend.cty_nmstct END) as 'dest_cty_nmstct', 
	orderheader.ord_origincity,
	orderheader.ord_destcity,
	orderheader.cmd_code as 'cmd_code',
	orderheader.ord_description, 
	orderheader.ord_remark, 
	orderheader.ord_hdrnumber, 
	orderheader.ord_trailer, 
	orderheader.ord_bookdate, 
	orderheader.ord_bookedby, 
	orderheader.ord_booked_revtype1, 
	orderheader.ord_entryport, 
	orderheader.ord_exitport, 
	orderheader.ord_driver1, 
	orderheader.ord_driver2, 
	orderheader.ord_tractor, 
	orderheader.ord_odmetermiles, 
	orderheader.ord_route, 
	orderheader.ord_route_effc_date, 
	orderheader.ord_route_exp_date, 
	company_legstart.cmp_primaryphone as 'origin_cmp_primaryphone', 
	company_legend.cmp_primaryphone as 'dest_cmp_primaryphone', 
	company_billto.cmp_primaryphone as 'billto_cmp_primaryphone', 
	orderheader.ord_totalmiles, 
	legheader_active.lgh_carrier as 'ord_carrier', 
	ISNULL(orderheader.ord_trailer2, '') as 'ord_trailer2', 
	orderheader.ord_chassis as 'ord_chassis', 
	orderheader.ord_chassis2 as 'ord_chassis2', 
	orderheader.ord_origin_earliestdate as 'origin_earliest', 
	orderheader.ord_origin_latestdate as 'origin_latest', 
	orderheader.ord_dest_earliestdate as 'dest_earliest', 
	orderheader.ord_dest_latestdate as 'dest_latest',
	orderheader.ord_schedulebatch as 'schedule_batch',
	orderheader.ord_shipper as 'ord_shipper',
	orderheader.ord_consignee as 'ord_consignee',
	orderheader.ord_billto as 'ord_billto',
	orderheader.ord_dest_zip as 'ord_dest_zip',
	orderheader.ord_origin_zip as 'ord_origin_zip',
	orderheader.ord_order_source as 'ord_order_source',
	orderheader.ord_originregion2 as 'ord_originregion2',
	orderheader.ord_originregion3 as 'ord_originregion3',
	orderheader.ord_originregion4 as 'ord_originregion4',
	orderheader.ord_destregion2 as 'ord_destregion2',
	orderheader.ord_destregion3 as 'ord_destregion3',
	orderheader.ord_destregion4 as 'ord_destregion4',
	orderheader.ord_schedulebatch as 'ord_schedulebatch',
	orderheader.ord_origin_earliestdate as 'ord_origin_earliestdate',
	legheader_active.lgh_number as 'lgh_number',
 	company_billto.cmp_state as 'billto_state',
	orderheader.ord_fromschedule as 'ord_fromschedule',
	orderheader.ord_BelongsTo as 'ord_belongsto',
	orderheader.rowsec_rsrv_id as 'ord_rowsec_rsrv_id',
	legheader_active.lgh_outstatus as 'lgh_outstatus',
	legheader_active.lgh_booked_revtype1 as 'lgh_booked_revtype1', 
	isnull(recordlock.locked_by, 'Not Locked') mov_lockedby,
	isnull(recordlock.session_date, '19500101') mov_lockedon,
	city_legstart.cty_latitude As origin_latitude,
	city_legstart.cty_longitude As origin_longitude,
	city_legend.cty_latitude As dest_latitude,
	city_legend.cty_longitude As dest_longitude,
	city_legstart.cty_region1 as origin_zone,
	city_legstart.cty_region2 as origin_area,
	lgh_carrier_truck as Carrier_Truck,
	lgh_driver_name as Carrier_Driver,
	lgh_driver_phone as Carrier_Phone,
	lgh_trailernumber as Carrier_Trailer,
	ISNULL(legheader_active.lgh_split_flag, 'N') lgh_split_flag,
	ISNULL(legheader_brokered.lgh_nextaction, '') 'nextaction',
	ISNULL(legheader_brokered.lgh_nextactiondate, '') 'nextactiondate',
	CONVERT(VARCHAR, ckc_date, 10) + ' ' + LEFT(CONVERT(VARCHAR, ckc_date, 8), 5) AS Last_Checkcall,
	ckc_comment AS Last_Checkcall_Comment,
	'' as Confirmed_Checkcall,
	dbo.fn_BrokerageTrackingStatusOnly(legheader_active.lgh_number) as Status_Desc,
	Offer_Count=(select count(*) from carrierauctions ca (nolock) where ca.lgh_number = legheader_active.lgh_number),
	convert(varchar,orderheader.ord_revenue_pay) as Top_Spend,
	orderheader.ord_revenue_pay_fix as Top_Spend_Fix,
	orderheader.trl_type1 as Trailer1_Requested,
	orderheader.ord_totalweight as Weight,
	(select sum(pyd_amount) from paydetail where paydetail.lgh_number = legheader_active.lgh_number) as Pay_Total,
	ckc_cityname as Last_Ckc_City,
	orderheader.ord_totalpieces,
	'' as web_notes
FROM legheader_active (nolock)
	left outer join legheader_brokered (nolock) on legheader_active.lgh_number = legheader_brokered.lgh_number
	left outer join orderheader (nolock) on legheader_active.ord_hdrnumber = orderheader.ord_hdrnumber 
	left outer join recordlock (nolock) on (legheader_active.mov_number = recordlock.ord_hdrnumber and
		recordlock.session_date = (SELECT MAX(rm.session_date) FROM recordlock rm (nolock) WHERE rm.ord_hdrnumber = legheader_active.mov_number))
	join company company_legstart (nolock) on (legheader_active.cmp_id_start = company_legstart.cmp_id)  
	join company company_legend (nolock) on (legheader_active.cmp_id_end = company_legend.cmp_id)  
	join company company_orderby (nolock) on (orderheader.ord_company = company_orderby.cmp_id)  
	join company company_billto (nolock) on (orderheader.ord_billto = company_billto.cmp_id) 
	join company company_shipper (nolock) on (orderheader.ord_shipper = company_shipper.cmp_id) 
	join company company_consignee (nolock) on (orderheader.ord_consignee = company_consignee.cmp_id) 
	join city city_legstart (nolock) on (legheader_active.lgh_startcity = city_legstart.cty_code)  
	join city city_legend (nolock) on (legheader_active.lgh_endcity = city_legend.cty_code)
	left outer join checkcall (nolock) on ckc_date = (SELECT Max(ckc_date) FROM checkcall (nolock) WHERE ckc_lghnumber = legheader_active.lgh_number)
WHERE legheader_active.lgh_carrier <> Upper (IsNull((SELECT TOP 1 Left (gi_string1, 8) from generalinfo where gi_name = 'PlanningCarrierID'), 'NEWCAR' ))
GO
GRANT SELECT ON  [dbo].[TMWScrollLegHeaderActiveView] TO [public]
GO
