SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE     View [dbo].[vSSRSRB_SafetyAccidentByTractor]

As
/**
 *
 * NAME:
 * dbo.vSSRSRB_SafetyAccidentByTractor
 *
 * TYPE:
 * View
 *
 * DESCRIPTION:
 * Safety accident and tractor views combined
 
 *
**************************************************************************

Sample call


select * from vSSRSRB_SafetyAccidentByTractor


**************************************************************************
 * RETURNS:
 * Recordset
 *
 * RESULT SETS:
 * Safety and tractor view combination
 *
 * PARAMETERS:
 * n/a
 *
 * REFERENCES: 
 *
 * REVISION HISTORY:
 *
 * 3/18/2014 JR created SSRS version of this view
 **
 */

Select vSSRSRB_SafetyAccident.[Rpt Report ID]
      ,vSSRSRB_SafetyAccident.[Rpt Number]
      ,vSSRSRB_SafetyAccident.[Rpt Event Date]
      ,vSSRSRB_SafetyAccident.[Rpt Event Date Only]
      ,vSSRSRB_SafetyAccident.[Rpt Event Location Is]
      ,vSSRSRB_SafetyAccident.[Rpt DOT Recordable]
      ,vSSRSRB_SafetyAccident.[Rpt Event Location Company ID]
      ,vSSRSRB_SafetyAccident.[Rpt Event Location]
      ,vSSRSRB_SafetyAccident.[Rpt Event Address1]
      ,vSSRSRB_SafetyAccident.[Rpt Event Address2]
      ,vSSRSRB_SafetyAccident.[Rpt Event City]
      ,vSSRSRB_SafetyAccident.[Rpt Event City Name State]
      ,vSSRSRB_SafetyAccident.[Rpt Event State]
      ,vSSRSRB_SafetyAccident.[Rpt Event Zip]
      ,vSSRSRB_SafetyAccident.[Rpt Event Country]
      ,vSSRSRB_SafetyAccident.[Rpt OnPremises]
      ,vSSRSRB_SafetyAccident.[Rpt Description]
      ,vSSRSRB_SafetyAccident.[Rpt Classification]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyType1]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyType2]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyType3]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyType4]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyStatus]
      ,vSSRSRB_SafetyAccident.[Rpt ReportedBy]
      ,vSSRSRB_SafetyAccident.[Rpt Reported Date]
      ,vSSRSRB_SafetyAccident.[Rpt Reported Date Only]
      ,vSSRSRB_SafetyAccident.[Rpt Req1Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req1DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req2Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req2DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req3Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req3DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req4Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req4DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req5Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req5DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req6Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req6DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Responsible Party]
      ,vSSRSRB_SafetyAccident.[Rpt Responsible Party Description]
      ,vSSRSRB_SafetyAccident.[Rpt Estimated Cost]
      ,vSSRSRB_SafetyAccident.[Rpt Actual Cost]
      ,vSSRSRB_SafetyAccident.[Rpt Total PaidBy Company]
      ,vSSRSRB_SafetyAccident.[Rpt Total PaidBy Insurance]
      ,vSSRSRB_SafetyAccident.[Rpt Total Reserves]
      ,vSSRSRB_SafetyAccident.[Rpt Total Recovered]
      ,vSSRSRB_SafetyAccident.[Rpt Terminal]
      ,vSSRSRB_SafetyAccident.[Rpt Tractor ID]
      ,vSSRSRB_SafetyAccident.[Rpt Trailer1 ID]
      ,vSSRSRB_SafetyAccident.[Rpt Trailer2 ID]
      ,vSSRSRB_SafetyAccident.[Rpt Driver1 ID]
      ,vSSRSRB_SafetyAccident.[Rpt Driver2 ID]
      ,vSSRSRB_SafetyAccident.[Rpt DriverOrEmployee ID]
      ,vSSRSRB_SafetyAccident.[Rpt Employee ID]
      ,vSSRSRB_SafetyAccident.[Rpt DriverOrEmployee Name]
      ,vSSRSRB_SafetyAccident.[Rpt Carrier ID]
      ,vSSRSRB_SafetyAccident.[Rpt Commodity Code]
      ,vSSRSRB_SafetyAccident.[Rpt Hazmat]
      ,vSSRSRB_SafetyAccident.[Rpt Insurance Company]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Address]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo City]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo City Name State]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo State]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Zip]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Country]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Phone Number]
      ,vSSRSRB_SafetyAccident.[Rpt ReportedToInsurance]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Report Date]
      ,vSSRSRB_SafetyAccident.[Rpt Claim Number]
      ,vSSRSRB_SafetyAccident.[Rpt Insurance Policy NBR]
      ,vSSRSRB_SafetyAccident.[Rpt Order Number]
      ,vSSRSRB_SafetyAccident.[Rpt Move Number]
      ,vSSRSRB_SafetyAccident.[Rpt Leg Number]
      ,vSSRSRB_SafetyAccident.[Bill To ID]
      ,vSSRSRB_SafetyAccident.[RevType1]
      ,vSSRSRB_SafetyAccident.[RevType2]
      ,vSSRSRB_SafetyAccident.[RevType3]
      ,vSSRSRB_SafetyAccident.[RevType4]
      ,vSSRSRB_SafetyAccident.[Rpt Picture Count]
      ,vSSRSRB_SafetyAccident.[Accident ID]
      ,vSSRSRB_SafetyAccident.[Report ID]
      ,vSSRSRB_SafetyAccident.[Accident Type 1]
      ,vSSRSRB_SafetyAccident.[Accident Type 1 Name]
      ,vSSRSRB_SafetyAccident.[Accident Type 2]
      ,vSSRSRB_SafetyAccident.[Accident Type 2 Name]
      ,vSSRSRB_SafetyAccident.[Vehicle Role]
      ,vSSRSRB_SafetyAccident.[Description]
      ,vSSRSRB_SafetyAccident.[Comments]
      ,vSSRSRB_SafetyAccident.[DOT Recordable]
      ,vSSRSRB_SafetyAccident.[Road Situation]
      ,vSSRSRB_SafetyAccident.[Illumination]
      ,vSSRSRB_SafetyAccident.[Weather Type]
      ,vSSRSRB_SafetyAccident.[Road Surface]
      ,vSSRSRB_SafetyAccident.[Nbr Of Injuries]
      ,vSSRSRB_SafetyAccident.[Nbr Of Fatalities]
      ,vSSRSRB_SafetyAccident.[Alcohol Test Done]
      ,vSSRSRB_SafetyAccident.[HoursToA lcoholTest]
      ,vSSRSRB_SafetyAccident.[Alcohol Test Date]
      ,vSSRSRB_SafetyAccident.[Alcohol Test Result]
      ,vSSRSRB_SafetyAccident.[Drug Test Done]
      ,vSSRSRB_SafetyAccident.[Hours To Drug Test]
      ,vSSRSRB_SafetyAccident.[Drug Test Date]
      ,vSSRSRB_SafetyAccident.[Drug Test Result]
      ,vSSRSRB_SafetyAccident.[Corrective Action Req]
      ,vSSRSRB_SafetyAccident.[DriverAtWheel]
      ,vSSRSRB_SafetyAccident.[Driver1]
      ,vSSRSRB_SafetyAccident.[Driver2]
      ,vSSRSRB_SafetyAccident.[Tractor ID]
      ,vSSRSRB_SafetyAccident.[Trailer1 ID]
      ,vSSRSRB_SafetyAccident.[Trailer2 ID]
      ,vSSRSRB_SafetyAccident.[Carrier ID]
      ,vSSRSRB_SafetyAccident.[Pictures]
      ,vSSRSRB_SafetyAccident.[CV Damage]
      ,vSSRSRB_SafetyAccident.[Trailer1 Damage]
      ,vSSRSRB_SafetyAccident.[Trailer2 Damage]
      ,vSSRSRB_SafetyAccident.[Tractor Damage]
      ,vSSRSRB_SafetyAccident.[Vehicle Towed]
      ,vSSRSRB_SafetyAccident.[Tow Destination]
      ,vSSRSRB_SafetyAccident.[Tow Dest Address]
      ,vSSRSRB_SafetyAccident.[Tow Dest City]
      ,vSSRSRB_SafetyAccident.[Tow Dest City Name State]
      ,vSSRSRB_SafetyAccident.[Tow Dest State]
      ,vSSRSRB_SafetyAccident.[Tow Dest Zip]
      ,vSSRSRB_SafetyAccident.[Tow Dest Country]
      ,vSSRSRB_SafetyAccident.[Tow Dest Phone]
      ,vSSRSRB_SafetyAccident.[LawEnf DeptName]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept Address]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept City]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept City Name State]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept State]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept Country]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept Zip]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept Phone]
      ,vSSRSRB_SafetyAccident.[LawEnf Officer]
      ,vSSRSRB_SafetyAccident.[LawEnf Officer Badge]
      ,vSSRSRB_SafetyAccident.[Police Report Number]
      ,vSSRSRB_SafetyAccident.[Ticket Issued]
      ,vSSRSRB_SafetyAccident.[Ticket IssuedTo]
      ,vSSRSRB_SafetyAccident.[Traffic Violation]
      ,vSSRSRB_SafetyAccident.[Ticket Desc]
      ,vSSRSRB_SafetyAccident.[Points]
      ,vSSRSRB_SafetyAccident.[Accident Prevent Ability]
      ,vSSRSRB_SafetyAccident.[Hazmat]
      ,vSSRSRB_SafetyAccident.[Estd Speed]
      ,vSSRSRB_SafetyAccident.[Road Type]
      ,vSSRSRB_SafetyAccident.[Reported To Insurance Co]
      ,vSSRSRB_SafetyAccident.[Ins Report Date]
      ,vSSRSRB_SafetyAccident.[OV Damaged]
      ,vSSRSRB_SafetyAccident.[OP Damaged]
      ,vSSRSRB_SafetyAccident.[Move Number]
      ,vSSRSRB_SafetyAccident.[Leg Header Number]
      ,vSSRSRB_SafetyAccident.[Order Number]
      ,vSSRSRB_SafetyAccident.[Code]
      ,vSSRSRB_SafetyAccident.[Shipper ID]
      ,vSSRSRB_SafetyAccident.[Tractor]
      ,vSSRSRB_SafetyAccident.[Owner]
      ,vSSRSRB_SafetyAccident.[TrcType1]
      ,vSSRSRB_SafetyAccident.[TrcType1 Name]
      ,vSSRSRB_SafetyAccident.[TrcType2]
      ,vSSRSRB_SafetyAccident.[TrcType2 Name]
      ,vSSRSRB_SafetyAccident.[TrcType3]
      ,vSSRSRB_SafetyAccident.[TrcType3 Name]
      ,vSSRSRB_SafetyAccident.[TrcType4]
      ,vSSRSRB_SafetyAccident.[TrcType4 Name]
      ,vSSRSRB_SafetyAccident.[Trailer Owner]
      ,vSSRSRB_SafetyAccident.[TrlType1]
      ,vSSRSRB_SafetyAccident.[TrlType1 Name]
      ,vSSRSRB_SafetyAccident.[TrlType2]
      ,vSSRSRB_SafetyAccident.[TrlType2 Name]
      ,vSSRSRB_SafetyAccident.[TrlType3]
      ,vSSRSRB_SafetyAccident.[TrlType3 Name]
      ,vSSRSRB_SafetyAccident.[TrlType4]
      ,vSSRSRB_SafetyAccident.[TrlType4 Name]
      ,vSSRSRB_SafetyAccident.[First Name]
      ,vSSRSRB_SafetyAccident.[Last Name]
      ,vSSRSRB_SafetyAccident.[Address1]
      ,vSSRSRB_SafetyAccident.[Address2]
      ,vSSRSRB_SafetyAccident.[City]
      ,vSSRSRB_SafetyAccident.[State]
      ,vSSRSRB_SafetyAccident.[Zip Code]
      --,vSSRSRB_TractorProfile.[Tractor]
      ,vSSRSRB_TractorProfile.[MaxAssignmentNumber]
      ,vSSRSRB_TractorProfile.[ActiveYN]
     -- ,vSSRSRB_TractorProfile.[Owner]
      ,vSSRSRB_TractorProfile.[Make]
      ,vSSRSRB_TractorProfile.[Model]
      ,vSSRSRB_TractorProfile.[Current Hub]
      --,vSSRSRB_TractorProfile.[TrcType1]
      --,vSSRSRB_TractorProfile.[TrcType1 Name]
      --,vSSRSRB_TractorProfile.[TrcType2]
      --,vSSRSRB_TractorProfile.[TrcType2 Name]
      --,vSSRSRB_TractorProfile.[TrcType3]
      --,vSSRSRB_TractorProfile.[TrcType3 Name]
      --,vSSRSRB_TractorProfile.[TrcType4]
      --,vSSRSRB_TractorProfile.[TrcType4 Name]
      ,vSSRSRB_TractorProfile.[Year]
      ,vSSRSRB_TractorProfile.[Start Date]
      ,vSSRSRB_TractorProfile.[Start Date Only]
      ,vSSRSRB_TractorProfile.[Retire Date]
      ,vSSRSRB_TractorProfile.[Retire Date Only]
      ,vSSRSRB_TractorProfile.[Miles Per Gallon]
      ,vSSRSRB_TractorProfile.[Fleet]
      ,vSSRSRB_TractorProfile.[Division]
      ,vSSRSRB_TractorProfile.[Company]
      ,vSSRSRB_TractorProfile.[Terminal]
      ,vSSRSRB_TractorProfile.[Date Acquired]
      ,vSSRSRB_TractorProfile.[Original Mileage]
      ,vSSRSRB_TractorProfile.[Engine Hours]
      ,vSSRSRB_TractorProfile.[Engine Make]
      ,vSSRSRB_TractorProfile.[Engine Model]
      ,vSSRSRB_TractorProfile.[Engine Serial]
      ,vSSRSRB_TractorProfile.[Serial]
      ,vSSRSRB_TractorProfile.[License State]
      ,vSSRSRB_TractorProfile.[License Number]
      ,vSSRSRB_TractorProfile.[Original Cost]
      ,vSSRSRB_TractorProfile.[Operation Cost Per Mile]
      ,vSSRSRB_TractorProfile.[Gross Weight]
      ,vSSRSRB_TractorProfile.[Axles]
      ,vSSRSRB_TractorProfile.[Warranty Days]
      ,vSSRSRB_TractorProfile.[Commethod]
      ,vSSRSRB_TractorProfile.[Tractor Status]
      ,vSSRSRB_TractorProfile.[Available Date]
      ,vSSRSRB_TractorProfile.[Available Date Only]
      ,vSSRSRB_TractorProfile.[Available Company ID]
      ,vSSRSRB_TractorProfile.[Available City]
      ,vSSRSRB_TractorProfile.[Available Status]
      ,vSSRSRB_TractorProfile.[Planned Date]
      ,vSSRSRB_TractorProfile.[Planned Company ID]
      ,vSSRSRB_TractorProfile.[Planned City]
      ,vSSRSRB_TractorProfile.[Planned Legheader]
      ,vSSRSRB_TractorProfile.[Available Legheader]
      ,vSSRSRB_TractorProfile.[Current Mileage]
      ,vSSRSRB_TractorProfile.[Driver ID]
      ,vSSRSRB_TractorProfile.[Driver Name]
      ,vSSRSRB_TractorProfile.[Driver Terminal]
      ,vSSRSRB_TractorProfile.[Driver Terminal ID]
      ,vSSRSRB_TractorProfile.[DrvType1 Name]
      ,vSSRSRB_TractorProfile.[DrvType1]
      ,vSSRSRB_TractorProfile.[DrvType2 Name]
      ,vSSRSRB_TractorProfile.[DrvType2]
      ,vSSRSRB_TractorProfile.[DrvType3 Name]
      ,vSSRSRB_TractorProfile.[DrvType3]
      ,vSSRSRB_TractorProfile.[DrvType4 Name]
      ,vSSRSRB_TractorProfile.[DrvType4]
      ,vSSRSRB_TractorProfile.[Accounting Type]
      ,vSSRSRB_TractorProfile.[Driver2 ID]
      ,vSSRSRB_TractorProfile.[Misc1]
      ,vSSRSRB_TractorProfile.[Misc2]
      ,vSSRSRB_TractorProfile.[Misc3]
      ,vSSRSRB_TractorProfile.[Misc4]
      ,vSSRSRB_TractorProfile.[Updated By]
      ,vSSRSRB_TractorProfile.[Turn Down]
      ,vSSRSRB_TractorProfile.[Phone Number]
      ,vSSRSRB_TractorProfile.[Next Destination Preference]
      ,vSSRSRB_TractorProfile.[MT Call Time]
      ,vSSRSRB_TractorProfile.[Updated On]
      ,vSSRSRB_TractorProfile.[Updated On Date Only]
      ,vSSRSRB_TractorProfile.[Tare Weight]
      ,vSSRSRB_TractorProfile.[Tare Weight UOM]
      ,vSSRSRB_TractorProfile.[BMPR To Steer]
      ,vSSRSRB_TractorProfile.[BMPR To Steer UOM]
      ,vSSRSRB_TractorProfile.[Steer to Drive1]
      ,vSSRSRB_TractorProfile.[Steer To Drive1 UOM]
      ,vSSRSRB_TractorProfile.[Drive1 To Drive2]
      ,vSSRSRB_TractorProfile.[Drive1 To Drive2 UOM]
      ,vSSRSRB_TractorProfile.[Drive2 To Rear]
      ,vSSRSRB_TractorProfile.[Drive2 to Rear UOM]
      ,vSSRSRB_TractorProfile.[Created Date]
      ,vSSRSRB_TractorProfile.[Wheel To Base]
      ,vSSRSRB_TractorProfile.[Cab To Axle]
      ,vSSRSRB_TractorProfile.[BPR To BkCab]
      ,vSSRSRB_TractorProfile.[Front Axle Spec]
      ,vSSRSRB_TractorProfile.[Rear Axle Spec]
      ,vSSRSRB_TractorProfile.[Fifth Wheel Tvl]
      ,vSSRSRB_TractorProfile.[Dummy]
      ,vSSRSRB_TractorProfile.[TTL Tare Weight]
      ,vSSRSRB_TractorProfile.[Wheel To Base UOM]
      ,vSSRSRB_TractorProfile.[Cab To Axle UOM]
      ,vSSRSRB_TractorProfile.[BPR To BkCab UOM]
      ,vSSRSRB_TractorProfile.[Rear Axle Spec UOM]
      ,vSSRSRB_TractorProfile.[Front Axle Spec UOM]
      ,vSSRSRB_TractorProfile.[Fifth Wheel TVL UOM]
      ,vSSRSRB_TractorProfile.[TTL Tare Weight UOM]
      ,vSSRSRB_TractorProfile.[Fifth Wheel Height]
      ,vSSRSRB_TractorProfile.[Fifth Wheel Height UOM]
      ,vSSRSRB_TractorProfile.[Quick Entry]
      ,vSSRSRB_TractorProfile.[Next Region 4]
      ,vSSRSRB_TractorProfile.[Next Region 2]
      ,vSSRSRB_TractorProfile.[Next Region 1]
      ,vSSRSRB_TractorProfile.[Next State]
      ,vSSRSRB_TractorProfile.[Next City]
      ,vSSRSRB_TractorProfile.[Next Company ID]
      ,vSSRSRB_TractorProfile.[Next Event]
      ,vSSRSRB_TractorProfile.[Prior Region 4]
      ,vSSRSRB_TractorProfile.[Prior Region 3]
      ,vSSRSRB_TractorProfile.[Prior Region 2]
      ,vSSRSRB_TractorProfile.[Prior Region 1]
      ,vSSRSRB_TractorProfile.[Prior State]
      ,vSSRSRB_TractorProfile.[Prior City]
      ,vSSRSRB_TractorProfile.[Prior Company ID]
      ,vSSRSRB_TractorProfile.[Prior Event]
      ,vSSRSRB_TractorProfile.[Alert Date]
      ,vSSRSRB_TractorProfile.[Alert Date Only]
      ,vSSRSRB_TractorProfile.[Note Date]
      ,vSSRSRB_TractorProfile.[Note Date Only]
      ,vSSRSRB_TractorProfile.[Check Conflict]
      ,vSSRSRB_TractorProfile.[Next Maintenance Hub]
      ,vSSRSRB_TractorProfile.[Exp2 Date]
      ,vSSRSRB_TractorProfile.[Exp2 Date Only]
      ,vSSRSRB_TractorProfile.[Exp1 Date]
      ,vSSRSRB_TractorProfile.[Exp1 Date Only]
      ,vSSRSRB_TractorProfile.[Networks]
      ,vSSRSRB_TractorProfile.[GPS Longitude]
      ,vSSRSRB_TractorProfile.[GPS Latitude]
      ,vSSRSRB_TractorProfile.[GPS Date]
      ,vSSRSRB_TractorProfile.[GPS Date Only]
      ,vSSRSRB_TractorProfile.[GPS Desc]
      ,vSSRSRB_TractorProfile.[Trailer 2]
      ,vSSRSRB_TractorProfile.[Trailer 1]
      ,vSSRSRB_TractorProfile.[Tank Capacity]
      ,vSSRSRB_TractorProfile.[Gallons In Tank]
      ,vSSRSRB_TractorProfile.[Third Party]
      ,vSSRSRB_TractorProfile.[Next Region 3]
      ,vSSRSRB_TractorProfile.[Branch]
      ,vSSRSRB_TractorProfile.[NewUsed]
      ,vSSRSRB_TractorProfile.[Accessory List]
      ,vSSRSRB_TractorProfile.[Company Name]
      ,vSSRSRB_TractorProfile.[Division Name]
      ,vSSRSRB_TractorProfile.[Terminal Name]
      ,vSSRSRB_TractorProfile.[Fleet Name]
      ,vSSRSRB_TractorProfile.[TractorCount]
      ,vSSRSRB_TractorProfile.[LastDriverCarrierOnTrip]

From   vSSRSRB_SafetyAccident 
	Left Join vSSRSRB_TractorProfile On vSSRSRB_TractorProfile.[Tractor] = vSSRSRB_SafetyAccident.[Tractor ID]


	

GO
GRANT SELECT ON  [dbo].[vSSRSRB_SafetyAccidentByTractor] TO [public]
GO
