SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE     View [dbo].[vSSRSRB_SafetyAccidentByTrailer]

As
/**
 *
 * NAME:
 * dbo.vSSRSRB_SafetyAccidentByTrailer
 *
 * TYPE:
 * View
 *
 * DESCRIPTION:
 * Safety accident and trailer views combined
 
 *
**************************************************************************

Sample call


select * from vSSRSRB_SafetyAccidentByTrailer


**************************************************************************
 * RETURNS:
 * Recordset
 *
 * RESULT SETS:
 * Safety and trailer view combination
 *
 * PARAMETERS:
 * n/a
 *
 * REFERENCES: 
 *
 * REVISION HISTORY:
 *
 * 3/18/2014 JR created SSRS version of this view
 **
 */
Select vSSRSRB_SafetyAccident.[Rpt Report ID]
      ,vSSRSRB_SafetyAccident.[Rpt Number]
      ,vSSRSRB_SafetyAccident.[Rpt Event Date]
      ,vSSRSRB_SafetyAccident.[Rpt Event Date Only]
      ,vSSRSRB_SafetyAccident.[Rpt Event Location Is]
      ,vSSRSRB_SafetyAccident.[Rpt DOT Recordable]
      ,vSSRSRB_SafetyAccident.[Rpt Event Location Company ID]
      ,vSSRSRB_SafetyAccident.[Rpt Event Location]
      ,vSSRSRB_SafetyAccident.[Rpt Event Address1]
      ,vSSRSRB_SafetyAccident.[Rpt Event Address2]
      ,vSSRSRB_SafetyAccident.[Rpt Event City]
      ,vSSRSRB_SafetyAccident.[Rpt Event City Name State]
      ,vSSRSRB_SafetyAccident.[Rpt Event State]
      ,vSSRSRB_SafetyAccident.[Rpt Event Zip]
      ,vSSRSRB_SafetyAccident.[Rpt Event Country]
      ,vSSRSRB_SafetyAccident.[Rpt OnPremises]
      ,vSSRSRB_SafetyAccident.[Rpt Description]
      ,vSSRSRB_SafetyAccident.[Rpt Classification]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyType1]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyType2]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyType3]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyType4]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyStatus]
      ,vSSRSRB_SafetyAccident.[Rpt ReportedBy]
      ,vSSRSRB_SafetyAccident.[Rpt Reported Date]
      ,vSSRSRB_SafetyAccident.[Rpt Reported Date Only]
      ,vSSRSRB_SafetyAccident.[Rpt Req1Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req1DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req2Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req2DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req3Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req3DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req4Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req4DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req5Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req5DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req6Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req6DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Responsible Party]
      ,vSSRSRB_SafetyAccident.[Rpt Responsible Party Description]
      ,vSSRSRB_SafetyAccident.[Rpt Estimated Cost]
      ,vSSRSRB_SafetyAccident.[Rpt Actual Cost]
      ,vSSRSRB_SafetyAccident.[Rpt Total PaidBy Company]
      ,vSSRSRB_SafetyAccident.[Rpt Total PaidBy Insurance]
      ,vSSRSRB_SafetyAccident.[Rpt Total Reserves]
      ,vSSRSRB_SafetyAccident.[Rpt Total Recovered]
      ,vSSRSRB_SafetyAccident.[Rpt Terminal]
      ,vSSRSRB_SafetyAccident.[Rpt Tractor ID]
      ,vSSRSRB_SafetyAccident.[Rpt Trailer1 ID]
      ,vSSRSRB_SafetyAccident.[Rpt Trailer2 ID]
      ,vSSRSRB_SafetyAccident.[Rpt Driver1 ID]
      ,vSSRSRB_SafetyAccident.[Rpt Driver2 ID]
      ,vSSRSRB_SafetyAccident.[Rpt DriverOrEmployee ID]
      ,vSSRSRB_SafetyAccident.[Rpt Employee ID]
      ,vSSRSRB_SafetyAccident.[Rpt DriverOrEmployee Name]
      ,vSSRSRB_SafetyAccident.[Rpt Carrier ID]
      ,vSSRSRB_SafetyAccident.[Rpt Commodity Code]
      ,vSSRSRB_SafetyAccident.[Rpt Hazmat]
      ,vSSRSRB_SafetyAccident.[Rpt Insurance Company]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Address]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo City]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo City Name State]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo State]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Zip]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Country]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Phone Number]
      ,vSSRSRB_SafetyAccident.[Rpt ReportedToInsurance]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Report Date]
      ,vSSRSRB_SafetyAccident.[Rpt Claim Number]
      ,vSSRSRB_SafetyAccident.[Rpt Insurance Policy NBR]
      ,vSSRSRB_SafetyAccident.[Rpt Order Number]
      ,vSSRSRB_SafetyAccident.[Rpt Move Number]
      ,vSSRSRB_SafetyAccident.[Rpt Leg Number]
      ,vSSRSRB_SafetyAccident.[Bill To ID]
      ,vSSRSRB_SafetyAccident.[RevType1]
      ,vSSRSRB_SafetyAccident.[RevType2]
      ,vSSRSRB_SafetyAccident.[RevType3]
      ,vSSRSRB_SafetyAccident.[RevType4]
      ,vSSRSRB_SafetyAccident.[Rpt Picture Count]
      ,vSSRSRB_SafetyAccident.[Accident ID]
      ,vSSRSRB_SafetyAccident.[Report ID]
      ,vSSRSRB_SafetyAccident.[Accident Type 1]
      ,vSSRSRB_SafetyAccident.[Accident Type 1 Name]
      ,vSSRSRB_SafetyAccident.[Accident Type 2]
      ,vSSRSRB_SafetyAccident.[Accident Type 2 Name]
      ,vSSRSRB_SafetyAccident.[Vehicle Role]
      ,vSSRSRB_SafetyAccident.[Description]
      ,vSSRSRB_SafetyAccident.[Comments]
      ,vSSRSRB_SafetyAccident.[DOT Recordable]
      ,vSSRSRB_SafetyAccident.[Road Situation]
      ,vSSRSRB_SafetyAccident.[Illumination]
      ,vSSRSRB_SafetyAccident.[Weather Type]
      ,vSSRSRB_SafetyAccident.[Road Surface]
      ,vSSRSRB_SafetyAccident.[Nbr Of Injuries]
      ,vSSRSRB_SafetyAccident.[Nbr Of Fatalities]
      ,vSSRSRB_SafetyAccident.[Alcohol Test Done]
      ,vSSRSRB_SafetyAccident.[HoursToA lcoholTest]
      ,vSSRSRB_SafetyAccident.[Alcohol Test Date]
      ,vSSRSRB_SafetyAccident.[Alcohol Test Result]
      ,vSSRSRB_SafetyAccident.[Drug Test Done]
      ,vSSRSRB_SafetyAccident.[Hours To Drug Test]
      ,vSSRSRB_SafetyAccident.[Drug Test Date]
      ,vSSRSRB_SafetyAccident.[Drug Test Result]
      ,vSSRSRB_SafetyAccident.[Corrective Action Req]
      ,vSSRSRB_SafetyAccident.[DriverAtWheel]
      ,vSSRSRB_SafetyAccident.[Driver1]
      ,vSSRSRB_SafetyAccident.[Driver2]
      ,vSSRSRB_SafetyAccident.[Tractor ID]
      ,vSSRSRB_SafetyAccident.[Trailer1 ID]
      ,vSSRSRB_SafetyAccident.[Trailer2 ID]
      ,vSSRSRB_SafetyAccident.[Carrier ID]
      ,vSSRSRB_SafetyAccident.[Pictures]
      ,vSSRSRB_SafetyAccident.[CV Damage]
      ,vSSRSRB_SafetyAccident.[Trailer1 Damage]
      ,vSSRSRB_SafetyAccident.[Trailer2 Damage]
      ,vSSRSRB_SafetyAccident.[Tractor Damage]
      ,vSSRSRB_SafetyAccident.[Vehicle Towed]
      ,vSSRSRB_SafetyAccident.[Tow Destination]
      ,vSSRSRB_SafetyAccident.[Tow Dest Address]
      ,vSSRSRB_SafetyAccident.[Tow Dest City]
      ,vSSRSRB_SafetyAccident.[Tow Dest City Name State]
      ,vSSRSRB_SafetyAccident.[Tow Dest State]
      ,vSSRSRB_SafetyAccident.[Tow Dest Zip]
      ,vSSRSRB_SafetyAccident.[Tow Dest Country]
      ,vSSRSRB_SafetyAccident.[Tow Dest Phone]
      ,vSSRSRB_SafetyAccident.[LawEnf DeptName]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept Address]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept City]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept City Name State]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept State]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept Country]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept Zip]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept Phone]
      ,vSSRSRB_SafetyAccident.[LawEnf Officer]
      ,vSSRSRB_SafetyAccident.[LawEnf Officer Badge]
      ,vSSRSRB_SafetyAccident.[Police Report Number]
      ,vSSRSRB_SafetyAccident.[Ticket Issued]
      ,vSSRSRB_SafetyAccident.[Ticket IssuedTo]
      ,vSSRSRB_SafetyAccident.[Traffic Violation]
      ,vSSRSRB_SafetyAccident.[Ticket Desc]
      ,vSSRSRB_SafetyAccident.[Points]
      ,vSSRSRB_SafetyAccident.[Accident Prevent Ability]
      ,vSSRSRB_SafetyAccident.[Hazmat]
      ,vSSRSRB_SafetyAccident.[Estd Speed]
      ,vSSRSRB_SafetyAccident.[Road Type]
      ,vSSRSRB_SafetyAccident.[Reported To Insurance Co]
      ,vSSRSRB_SafetyAccident.[Ins Report Date]
      ,vSSRSRB_SafetyAccident.[OV Damaged]
      ,vSSRSRB_SafetyAccident.[OP Damaged]
      ,vSSRSRB_SafetyAccident.[Move Number]
      ,vSSRSRB_SafetyAccident.[Leg Header Number]
      ,vSSRSRB_SafetyAccident.[Order Number]
      ,vSSRSRB_SafetyAccident.[Code]
      ,vSSRSRB_SafetyAccident.[Shipper ID]
      ,vSSRSRB_SafetyAccident.[Tractor]
      ,vSSRSRB_SafetyAccident.[Owner]
      ,vSSRSRB_SafetyAccident.[TrcType1]
      ,vSSRSRB_SafetyAccident.[TrcType1 Name]
      ,vSSRSRB_SafetyAccident.[TrcType2]
      ,vSSRSRB_SafetyAccident.[TrcType2 Name]
      ,vSSRSRB_SafetyAccident.[TrcType3]
      ,vSSRSRB_SafetyAccident.[TrcType3 Name]
      ,vSSRSRB_SafetyAccident.[TrcType4]
      ,vSSRSRB_SafetyAccident.[TrcType4 Name]
      ,vSSRSRB_SafetyAccident.[Trailer Owner]
      ,vSSRSRB_SafetyAccident.[TrlType1]
      ,vSSRSRB_SafetyAccident.[TrlType1 Name]
      ,vSSRSRB_SafetyAccident.[TrlType2]
      ,vSSRSRB_SafetyAccident.[TrlType2 Name]
      ,vSSRSRB_SafetyAccident.[TrlType3]
      ,vSSRSRB_SafetyAccident.[TrlType3 Name]
      ,vSSRSRB_SafetyAccident.[TrlType4]
      ,vSSRSRB_SafetyAccident.[TrlType4 Name]
      ,vSSRSRB_SafetyAccident.[First Name]
      ,vSSRSRB_SafetyAccident.[Last Name]
      ,vSSRSRB_SafetyAccident.[Address1]
      ,vSSRSRB_SafetyAccident.[Address2]
      ,vSSRSRB_SafetyAccident.[City]
      ,vSSRSRB_SafetyAccident.[State]
      ,vSSRSRB_SafetyAccident.[Zip Code]
      ,vSSRSRB_TrailerProfile.[Trailer ID]
      ,vSSRSRB_TrailerProfile.[ActiveYN]
      --,vSSRSRB_TrailerProfile.[Owner]
      ,vSSRSRB_TrailerProfile.[Make]
      ,vSSRSRB_TrailerProfile.[Model]
      ,vSSRSRB_TrailerProfile.[Current Hub]
     -- ,vSSRSRB_TrailerProfile.[TrlType1]
     -- ,vSSRSRB_TrailerProfile.[TrlType1 Name]
     -- ,vSSRSRB_TrailerProfile.[TrlType2]
     -- ,vSSRSRB_TrailerProfile.[TrlType2 Name]
     -- ,vSSRSRB_TrailerProfile.[TrlType3]
     -- ,vSSRSRB_TrailerProfile.[TrlType3 Name]
     -- ,vSSRSRB_TrailerProfile.[TrlType4]
     -- ,vSSRSRB_TrailerProfile.[TrlType4 Name]
      ,vSSRSRB_TrailerProfile.[Year]
      ,vSSRSRB_TrailerProfile.[Start Date]
      ,vSSRSRB_TrailerProfile.[Start Date Only]
      ,vSSRSRB_TrailerProfile.[Retire Date]
      ,vSSRSRB_TrailerProfile.[Retire Date Only]
      ,vSSRSRB_TrailerProfile.[Miles Per Gallon]
      ,vSSRSRB_TrailerProfile.[Trailer Company]
      ,vSSRSRB_TrailerProfile.[Trailer Company Name]
      ,vSSRSRB_TrailerProfile.[Trailer Fleet]
      ,vSSRSRB_TrailerProfile.[Trailer Fleet Name]
      ,vSSRSRB_TrailerProfile.[Trailer Division]
      ,vSSRSRB_TrailerProfile.[Trailer Division Name]
      ,vSSRSRB_TrailerProfile.[Trailer Terminal]
      ,vSSRSRB_TrailerProfile.[Trailer Terminal Name]
      ,vSSRSRB_TrailerProfile.[Company ID]
     -- ,vSSRSRB_TrailerProfile.[City]
      ,vSSRSRB_TrailerProfile.[Ilt]
      ,vSSRSRB_TrailerProfile.[MT Weight]
      ,vSSRSRB_TrailerProfile.[Gross Weight]
      ,vSSRSRB_TrailerProfile.[Axles]
      ,vSSRSRB_TrailerProfile.[Trailer Height]
      ,vSSRSRB_TrailerProfile.[Trailer Length]
      ,vSSRSRB_TrailerProfile.[Trailer Width]
      ,vSSRSRB_TrailerProfile.[License State]
      ,vSSRSRB_TrailerProfile.[License Number]
      ,vSSRSRB_TrailerProfile.[Trailer Status]
      ,vSSRSRB_TrailerProfile.[Serial]
      ,vSSRSRB_TrailerProfile.[Date Acquired]
      ,vSSRSRB_TrailerProfile.[Date Acquired Date Only]
      ,vSSRSRB_TrailerProfile.[Original Cost]
      ,vSSRSRB_TrailerProfile.[Operation Cost Per Mile]
      ,vSSRSRB_TrailerProfile.[Scheduled Date]
      ,vSSRSRB_TrailerProfile.[Scheduled Date Only]
      ,vSSRSRB_TrailerProfile.[Scheduled Company ID]
      ,vSSRSRB_TrailerProfile.[Scheduled City]
      ,vSSRSRB_TrailerProfile.[Scheduled Status]
      ,vSSRSRB_TrailerProfile.[Available Date]
      ,vSSRSRB_TrailerProfile.[Available Date Only]
      ,vSSRSRB_TrailerProfile.[Available Company ID]
      ,vSSRSRB_TrailerProfile.[Available City]
      ,vSSRSRB_TrailerProfile.[Fix Record]
      ,vSSRSRB_TrailerProfile.[Last Stop]
      ,vSSRSRB_TrailerProfile.[Misc1]
      ,vSSRSRB_TrailerProfile.[Misc2]
      ,vSSRSRB_TrailerProfile.[Misc3]
      ,vSSRSRB_TrailerProfile.[Misc4]
      ,vSSRSRB_TrailerProfile.[Trailer]
      ,vSSRSRB_TrailerProfile.[Current Mileage]
      ,vSSRSRB_TrailerProfile.[BMP PathName]
      ,vSSRSRB_TrailerProfile.[Accounting Type]
      ,vSSRSRB_TrailerProfile.[Ilt Scac]
      ,vSSRSRB_TrailerProfile.[Updated By]
      ,vSSRSRB_TrailerProfile.[Updated On]
      ,vSSRSRB_TrailerProfile.[Updated On Date Only]
      ,vSSRSRB_TrailerProfile.[Tare Weight]
      ,vSSRSRB_TrailerProfile.[Kp To Axle1]
      ,vSSRSRB_TrailerProfile.[Axle1 To Axle2]
      ,vSSRSRB_TrailerProfile.[Axle2 To Axle3]
      ,vSSRSRB_TrailerProfile.[Axle3 To Axle4]
      ,vSSRSRB_TrailerProfile.[Compartment1 Size Wet]
      ,vSSRSRB_TrailerProfile.[Compartment2 Size Wet]
      ,vSSRSRB_TrailerProfile.[Compartment3 Size Wet]
      ,vSSRSRB_TrailerProfile.[Compartment4 Size Wet]
      ,vSSRSRB_TrailerProfile.[Compartment5 Size Wet]
      ,vSSRSRB_TrailerProfile.[Compartment6 Size Wet]
      ,vSSRSRB_TrailerProfile.[Compartment1 Uom Wet]
      ,vSSRSRB_TrailerProfile.[Compartment2 Uom Wet]
      ,vSSRSRB_TrailerProfile.[Compartment3 Uom Wet]
      ,vSSRSRB_TrailerProfile.[Compartment4 Uom Wet]
      ,vSSRSRB_TrailerProfile.[Compartment5 Uom Wet]
      ,vSSRSRB_TrailerProfile.[Compartment6 Uom Wet]
      ,vSSRSRB_TrailerProfile.[Compartment1 Bulkhead]
      ,vSSRSRB_TrailerProfile.[Compartment2 Bulkhead]
      ,vSSRSRB_TrailerProfile.[Compartment3 Bulkhead]
      ,vSSRSRB_TrailerProfile.[Compartment4 Bulkhead]
      ,vSSRSRB_TrailerProfile.[Compartment5 Bulkhead]
      ,vSSRSRB_TrailerProfile.[Tareweight Uom]
      ,vSSRSRB_TrailerProfile.[Kp To Axle1 Uom]
      ,vSSRSRB_TrailerProfile.[Axle1 To Axle2 Uom]
      ,vSSRSRB_TrailerProfile.[Axle2 To Axle3 Uom]
      ,vSSRSRB_TrailerProfile.[Axle3 To Axle4 Uom]
      ,vSSRSRB_TrailerProfile.[Created Date]
      ,vSSRSRB_TrailerProfile.[Created Date Only]
      ,vSSRSRB_TrailerProfile.[Pup ID]
      ,vSSRSRB_TrailerProfile.[Axle4 To Axle5]
      ,vSSRSRB_TrailerProfile.[Axle4 To Axle5 Uom]
      ,vSSRSRB_TrailerProfile.[Last Axle To Rear]
      ,vSSRSRB_TrailerProfile.[Last Axle To Rear Uom]
      ,vSSRSRB_TrailerProfile.[Nose To Kp]
      ,vSSRSRB_TrailerProfile.[Nose To Kp Uom]
      ,vSSRSRB_TrailerProfile.[Total Number of Compartments]
      ,vSSRSRB_TrailerProfile.[Total Trailer Size Wet]
      ,vSSRSRB_TrailerProfile.[Uom Wet]
      ,vSSRSRB_TrailerProfile.[Total Trailer Size Dry]
      ,vSSRSRB_TrailerProfile.[Uom Dry]
      ,vSSRSRB_TrailerProfile.[Compartment1 Size Dry]
      ,vSSRSRB_TrailerProfile.[Compartment2 Size Dry]
      ,vSSRSRB_TrailerProfile.[Compartment3 Size Dry]
      ,vSSRSRB_TrailerProfile.[Compartment4 Size Dry]
      ,vSSRSRB_TrailerProfile.[Compartment5 Size Dry]
      ,vSSRSRB_TrailerProfile.[Compartment6 Size Dry]
      ,vSSRSRB_TrailerProfile.[Compartment1 Uom Dry]
      ,vSSRSRB_TrailerProfile.[Compartment2 Uom Dry]
      ,vSSRSRB_TrailerProfile.[Compartment3 Uom Dry]
      ,vSSRSRB_TrailerProfile.[Compartment4 Uom Dry]
      ,vSSRSRB_TrailerProfile.[Compartment5 Uom Dry]
      ,vSSRSRB_TrailerProfile.[Compartment6 Uom Dry]
      ,vSSRSRB_TrailerProfile.[Bulkhead Compartment1 Thick]
      ,vSSRSRB_TrailerProfile.[Bulkhead Compartment2 Thick]
      ,vSSRSRB_TrailerProfile.[Bulkhead Compartment3 Thick]
      ,vSSRSRB_TrailerProfile.[Bulkhead Compartment4 Thick]
      ,vSSRSRB_TrailerProfile.[Bulkhead Compartment5 Thick]
      ,vSSRSRB_TrailerProfile.[Bulkhead Compartment1 Thick Uom]
      ,vSSRSRB_TrailerProfile.[Bulkhead Compartment2 Thick Uom]
      ,vSSRSRB_TrailerProfile.[Bulkhead Compartment3 Thick Uom]
      ,vSSRSRB_TrailerProfile.[Bulkhead Compartment4 Thick Uom]
      ,vSSRSRB_TrailerProfile.[Bulkhead Compartment5 Thick Uom]
      ,vSSRSRB_TrailerProfile.[Quick Entry]
      ,vSSRSRB_TrailerProfile.[Wash Status]
      ,vSSRSRB_TrailerProfile.[Manual Update]
      ,vSSRSRB_TrailerProfile.[Expiration1 Date]
      ,vSSRSRB_TrailerProfile.[Expiration1 Date Only]
      ,vSSRSRB_TrailerProfile.[Expiration2 Date]
      ,vSSRSRB_TrailerProfile.[Expiration2 Date Only]
      ,vSSRSRB_TrailerProfile.[Last Cmd]
      ,vSSRSRB_TrailerProfile.[Last Cmd Ord]
      ,vSSRSRB_TrailerProfile.[Last Cmd Date]
      ,vSSRSRB_TrailerProfile.[Last Cmd Date Only]
      ,vSSRSRB_TrailerProfile.[Pallet Count]
      ,vSSRSRB_TrailerProfile.[Customer Flag]
      ,vSSRSRB_TrailerProfile.[Bill To Parent]
      ,vSSRSRB_TrailerProfile.[Booked RevType1]
      ,vSSRSRB_TrailerProfile.[Next Event]
      ,vSSRSRB_TrailerProfile.[Next Company ID]
      ,vSSRSRB_TrailerProfile.[Next City]
      ,vSSRSRB_TrailerProfile.[Next State]
      ,vSSRSRB_TrailerProfile.[Next Region 1]
      ,vSSRSRB_TrailerProfile.[Next Region 2]
      ,vSSRSRB_TrailerProfile.[Next Region 3]
      ,vSSRSRB_TrailerProfile.[Next Region 4]
      ,vSSRSRB_TrailerProfile.[Prior Event]
      ,vSSRSRB_TrailerProfile.[Prior Company ID]
      ,vSSRSRB_TrailerProfile.[Prior City]
      ,vSSRSRB_TrailerProfile.[Prior State]
      ,vSSRSRB_TrailerProfile.[Prior Region 1]
      ,vSSRSRB_TrailerProfile.[Prior Region 2]
      ,vSSRSRB_TrailerProfile.[Prior Region 4]
      ,vSSRSRB_TrailerProfile.[Prior Region 3]
      ,vSSRSRB_TrailerProfile.[Branch]
      ,vSSRSRB_TrailerProfile.[Accessory List]
      ,vSSRSRB_TrailerProfile.[GP Class]
      ,vSSRSRB_TrailerProfile.[NewUsed]

From   vSSRSRB_SafetyAccident 
	Left Join vSSRSRB_TrailerProfile On vSSRSRB_TrailerProfile.[Trailer ID] = vSSRSRB_SafetyAccident.[Trailer1 ID]



GO
GRANT SELECT ON  [dbo].[vSSRSRB_SafetyAccidentByTrailer] TO [public]
GO
