SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE     View [dbo].[vSSRSRB_SafetyAccidentByDriver]

As
/**
 *
 * NAME:
 * dbo.vSSRSRB_SafetyAccidentByDriver
 *
 * TYPE:
 * View
 *
 * DESCRIPTION:
 * Safety accident and driver views combined
 
 *
**************************************************************************

Sample call


select * from vSSRSRB_SafetyAccidentByDriver


**************************************************************************
 * RETURNS:
 * Recordset
 *
 * RESULT SETS:
 * Safety and driver view combination
 *
 * PARAMETERS:
 * n/a
 *
 * REFERENCES: 
 *
 * REVISION HISTORY:
 *
 * 3/18/2014 JR created SSRS version of this view
 **/
Select vSSRSRB_SafetyAccident.[Rpt Report ID]
      ,vSSRSRB_SafetyAccident.[Rpt Number]
      ,vSSRSRB_SafetyAccident.[Rpt Event Date]
      ,vSSRSRB_SafetyAccident.[Rpt Event Date Only]
      ,vSSRSRB_SafetyAccident.[Rpt Event Location Is]
      ,vSSRSRB_SafetyAccident.[Rpt DOT Recordable]
      ,vSSRSRB_SafetyAccident.[Rpt Event Location Company ID]
      ,vSSRSRB_SafetyAccident.[Rpt Event Location]
      ,vSSRSRB_SafetyAccident.[Rpt Event Address1]
      ,vSSRSRB_SafetyAccident.[Rpt Event Address2]
      ,vSSRSRB_SafetyAccident.[Rpt Event City]
      ,vSSRSRB_SafetyAccident.[Rpt Event City Name State]
      ,vSSRSRB_SafetyAccident.[Rpt Event State]
      ,vSSRSRB_SafetyAccident.[Rpt Event Zip]
      ,vSSRSRB_SafetyAccident.[Rpt Event Country]
      ,vSSRSRB_SafetyAccident.[Rpt OnPremises]
      ,vSSRSRB_SafetyAccident.[Rpt Description]
      ,vSSRSRB_SafetyAccident.[Rpt Classification]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyType1]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyType2]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyType3]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyType4]
      ,vSSRSRB_SafetyAccident.[Rpt SafetyStatus]
      ,vSSRSRB_SafetyAccident.[Rpt ReportedBy]
      ,vSSRSRB_SafetyAccident.[Rpt Reported Date]
      ,vSSRSRB_SafetyAccident.[Rpt Reported Date Only]
      ,vSSRSRB_SafetyAccident.[Rpt Req1Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req1DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req2Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req2DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req3Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req3DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req4Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req4DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req5Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req5DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Req6Complete]
      ,vSSRSRB_SafetyAccident.[Rpt Req6DtDone]
      ,vSSRSRB_SafetyAccident.[Rpt Responsible Party]
      ,vSSRSRB_SafetyAccident.[Rpt Responsible Party Description]
      ,vSSRSRB_SafetyAccident.[Rpt Estimated Cost]
      ,vSSRSRB_SafetyAccident.[Rpt Actual Cost]
      ,vSSRSRB_SafetyAccident.[Rpt Total PaidBy Company]
      ,vSSRSRB_SafetyAccident.[Rpt Total PaidBy Insurance]
      ,vSSRSRB_SafetyAccident.[Rpt Total Reserves]
      ,vSSRSRB_SafetyAccident.[Rpt Total Recovered]
      ,vSSRSRB_SafetyAccident.[Rpt Terminal]
      ,vSSRSRB_SafetyAccident.[Rpt Tractor ID]
      ,vSSRSRB_SafetyAccident.[Rpt Trailer1 ID]
      ,vSSRSRB_SafetyAccident.[Rpt Trailer2 ID]
      ,vSSRSRB_SafetyAccident.[Rpt Driver1 ID]
      ,vSSRSRB_SafetyAccident.[Rpt Driver2 ID]
      ,vSSRSRB_SafetyAccident.[Rpt DriverOrEmployee ID]
      ,vSSRSRB_SafetyAccident.[Rpt Employee ID]
      ,vSSRSRB_SafetyAccident.[Rpt DriverOrEmployee Name]
      ,vSSRSRB_SafetyAccident.[Rpt Carrier ID]
      ,vSSRSRB_SafetyAccident.[Rpt Commodity Code]
      ,vSSRSRB_SafetyAccident.[Rpt Hazmat]
      ,vSSRSRB_SafetyAccident.[Rpt Insurance Company]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Address]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo City]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo City Name State]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo State]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Zip]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Country]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Phone Number]
      ,vSSRSRB_SafetyAccident.[Rpt ReportedToInsurance]
      ,vSSRSRB_SafetyAccident.[Rpt InsuranceCo Report Date]
      ,vSSRSRB_SafetyAccident.[Rpt Claim Number]
      ,vSSRSRB_SafetyAccident.[Rpt Insurance Policy NBR]
      ,vSSRSRB_SafetyAccident.[Rpt Order Number]
      ,vSSRSRB_SafetyAccident.[Rpt Move Number]
      ,vSSRSRB_SafetyAccident.[Rpt Leg Number]
      ,vSSRSRB_SafetyAccident.[Bill To ID]
      ,vSSRSRB_SafetyAccident.[RevType1]
      ,vSSRSRB_SafetyAccident.[RevType2]
      ,vSSRSRB_SafetyAccident.[RevType3]
      ,vSSRSRB_SafetyAccident.[RevType4]
      ,vSSRSRB_SafetyAccident.[Rpt Picture Count]
      ,vSSRSRB_SafetyAccident.[Accident ID]
      ,vSSRSRB_SafetyAccident.[Report ID]
      ,vSSRSRB_SafetyAccident.[Accident Type 1]
      ,vSSRSRB_SafetyAccident.[Accident Type 1 Name]
      ,vSSRSRB_SafetyAccident.[Accident Type 2]
      ,vSSRSRB_SafetyAccident.[Accident Type 2 Name]
      ,vSSRSRB_SafetyAccident.[Vehicle Role]
      ,vSSRSRB_SafetyAccident.[Description]
      ,vSSRSRB_SafetyAccident.[Comments]
      ,vSSRSRB_SafetyAccident.[DOT Recordable]
      ,vSSRSRB_SafetyAccident.[Road Situation]
      ,vSSRSRB_SafetyAccident.[Illumination]
      ,vSSRSRB_SafetyAccident.[Weather Type]
      ,vSSRSRB_SafetyAccident.[Road Surface]
      ,vSSRSRB_SafetyAccident.[Nbr Of Injuries]
      ,vSSRSRB_SafetyAccident.[Nbr Of Fatalities]
      ,vSSRSRB_SafetyAccident.[Alcohol Test Done]
      ,vSSRSRB_SafetyAccident.[HoursToA lcoholTest]
      ,vSSRSRB_SafetyAccident.[Alcohol Test Date]
      ,vSSRSRB_SafetyAccident.[Alcohol Test Result]
      ,vSSRSRB_SafetyAccident.[Drug Test Done]
      ,vSSRSRB_SafetyAccident.[Hours To Drug Test]
      ,vSSRSRB_SafetyAccident.[Drug Test Date]
      ,vSSRSRB_SafetyAccident.[Drug Test Result]
      ,vSSRSRB_SafetyAccident.[Corrective Action Req]
      ,vSSRSRB_SafetyAccident.[DriverAtWheel]
      ,vSSRSRB_SafetyAccident.[Driver1]
      ,vSSRSRB_SafetyAccident.[Driver2]
      ,vSSRSRB_SafetyAccident.[Tractor ID]
      ,vSSRSRB_SafetyAccident.[Trailer1 ID]
      ,vSSRSRB_SafetyAccident.[Trailer2 ID]
      ,vSSRSRB_SafetyAccident.[Carrier ID]
      ,vSSRSRB_SafetyAccident.[Pictures]
      ,vSSRSRB_SafetyAccident.[CV Damage]
      ,vSSRSRB_SafetyAccident.[Trailer1 Damage]
      ,vSSRSRB_SafetyAccident.[Trailer2 Damage]
      ,vSSRSRB_SafetyAccident.[Tractor Damage]
      ,vSSRSRB_SafetyAccident.[Vehicle Towed]
      ,vSSRSRB_SafetyAccident.[Tow Destination]
      ,vSSRSRB_SafetyAccident.[Tow Dest Address]
      ,vSSRSRB_SafetyAccident.[Tow Dest City]
      ,vSSRSRB_SafetyAccident.[Tow Dest City Name State]
      ,vSSRSRB_SafetyAccident.[Tow Dest State]
      ,vSSRSRB_SafetyAccident.[Tow Dest Zip]
      ,vSSRSRB_SafetyAccident.[Tow Dest Country]
      ,vSSRSRB_SafetyAccident.[Tow Dest Phone]
      ,vSSRSRB_SafetyAccident.[LawEnf DeptName]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept Address]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept City]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept City Name State]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept State]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept Country]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept Zip]
      ,vSSRSRB_SafetyAccident.[LawEnf Dept Phone]
      ,vSSRSRB_SafetyAccident.[LawEnf Officer]
      ,vSSRSRB_SafetyAccident.[LawEnf Officer Badge]
      ,vSSRSRB_SafetyAccident.[Police Report Number]
      ,vSSRSRB_SafetyAccident.[Ticket Issued]
      ,vSSRSRB_SafetyAccident.[Ticket IssuedTo]
      ,vSSRSRB_SafetyAccident.[Traffic Violation]
      ,vSSRSRB_SafetyAccident.[Ticket Desc]
      ,vSSRSRB_SafetyAccident.[Points]
      ,vSSRSRB_SafetyAccident.[Accident Prevent Ability]
      ,vSSRSRB_SafetyAccident.[Hazmat]
      ,vSSRSRB_SafetyAccident.[Estd Speed]
      ,vSSRSRB_SafetyAccident.[Road Type]
      ,vSSRSRB_SafetyAccident.[Reported To Insurance Co]
      ,vSSRSRB_SafetyAccident.[Ins Report Date]
      ,vSSRSRB_SafetyAccident.[OV Damaged]
      ,vSSRSRB_SafetyAccident.[OP Damaged]
      ,vSSRSRB_SafetyAccident.[Move Number]
      ,vSSRSRB_SafetyAccident.[Leg Header Number]
      ,vSSRSRB_SafetyAccident.[Order Number]
      ,vSSRSRB_SafetyAccident.[Code]
      ,vSSRSRB_SafetyAccident.[Shipper ID]
      ,vSSRSRB_SafetyAccident.[Tractor]
      ,vSSRSRB_SafetyAccident.[Owner]
      ,vSSRSRB_SafetyAccident.[TrcType1]
      ,vSSRSRB_SafetyAccident.[TrcType1 Name]
      ,vSSRSRB_SafetyAccident.[TrcType2]
      ,vSSRSRB_SafetyAccident.[TrcType2 Name]
      ,vSSRSRB_SafetyAccident.[TrcType3]
      ,vSSRSRB_SafetyAccident.[TrcType3 Name]
      ,vSSRSRB_SafetyAccident.[TrcType4]
      ,vSSRSRB_SafetyAccident.[TrcType4 Name]
      ,vSSRSRB_SafetyAccident.[Trailer Owner]
      ,vSSRSRB_SafetyAccident.[TrlType1]
      ,vSSRSRB_SafetyAccident.[TrlType1 Name]
      ,vSSRSRB_SafetyAccident.[TrlType2]
      ,vSSRSRB_SafetyAccident.[TrlType2 Name]
      ,vSSRSRB_SafetyAccident.[TrlType3]
      ,vSSRSRB_SafetyAccident.[TrlType3 Name]
      ,vSSRSRB_SafetyAccident.[TrlType4]
      ,vSSRSRB_SafetyAccident.[TrlType4 Name]
      ,vSSRSRB_SafetyAccident.[First Name]
      ,vSSRSRB_SafetyAccident.[Last Name]
      ,vSSRSRB_SafetyAccident.[Address1]
      ,vSSRSRB_SafetyAccident.[Address2]
      ,vSSRSRB_SafetyAccident.[City]
      ,vSSRSRB_SafetyAccident.[State]
      ,vSSRSRB_SafetyAccident.[Zip Code]
      ,vSSRSRB_DriverProfile.[Driver ID]
      ,vSSRSRB_DriverProfile.[ActiveYN]
      ,vSSRSRB_DriverProfile.[Last Accident Date]
      ,vSSRSRB_DriverProfile.[Driver Type]
      --,vSSRSRB_DriverProfile.[Tractor]
      ,vSSRSRB_DriverProfile.[Other ID]
      ,vSSRSRB_DriverProfile.[Employed By]
     -- ,vSSRSRB_DriverProfile.[First Name]
      ,vSSRSRB_DriverProfile.[Middle Name]
      --,vSSRSRB_DriverProfile.[Last Name]
      ,vSSRSRB_DriverProfile.[Social Security Number]
     -- ,vSSRSRB_DriverProfile.[Address1]
     -- ,vSSRSRB_DriverProfile.[Address2]
     -- ,vSSRSRB_DriverProfile.[City]
      --,vSSRSRB_DriverProfile.[State]
     -- ,vSSRSRB_DriverProfile.[Zip Code]
      ,vSSRSRB_DriverProfile.[Hire Date Only]
      ,vSSRSRB_DriverProfile.[Hire Day Only]
      ,vSSRSRB_DriverProfile.[Hire Day]
      ,vSSRSRB_DriverProfile.[Hire Month]
      ,vSSRSRB_DriverProfile.[Hire Month Only]
      ,vSSRSRB_DriverProfile.[Hire Year]
      ,vSSRSRB_DriverProfile.[Hire Date]
      ,vSSRSRB_DriverProfile.[Seniority Date]
      ,vSSRSRB_DriverProfile.[License State]
      ,vSSRSRB_DriverProfile.[License Class]
      ,vSSRSRB_DriverProfile.[License Number]
      ,vSSRSRB_DriverProfile.[Date of Birth]
      ,vSSRSRB_DriverProfile.[Date Of Birth Date Only]
      ,vSSRSRB_DriverProfile.[Date Of Birth Day]
      ,vSSRSRB_DriverProfile.[Date of Birth Day Only]
      ,vSSRSRB_DriverProfile.[Date Of Birth Month]
      ,vSSRSRB_DriverProfile.[Date Of Birth Month Only]
      ,vSSRSRB_DriverProfile.[Date Of Birth Year]
      ,vSSRSRB_DriverProfile.[Current Phone Number]
      ,vSSRSRB_DriverProfile.[Alternate Phone Number]
      ,vSSRSRB_DriverProfile.[Home Phone Number]
      ,vSSRSRB_DriverProfile.[DrvType1 Name]
      ,vSSRSRB_DriverProfile.[DrvType1]
      ,vSSRSRB_DriverProfile.[DrvType2 Name]
      ,vSSRSRB_DriverProfile.[DrvType2]
      ,vSSRSRB_DriverProfile.[DrvType3 Name]
      ,vSSRSRB_DriverProfile.[DrvType3]
      ,vSSRSRB_DriverProfile.[DrvType4 Name]
      ,vSSRSRB_DriverProfile.[DrvType4]
      ,vSSRSRB_DriverProfile.[Currency]
      ,vSSRSRB_DriverProfile.[PayTo]
      ,vSSRSRB_DriverProfile.[Single Mile Rate]
      ,vSSRSRB_DriverProfile.[Team Mile Rate]
      ,vSSRSRB_DriverProfile.[Hourly Rate]
      ,vSSRSRB_DriverProfile.[Revenue Rate]
      ,vSSRSRB_DriverProfile.[Team Leader]
      ,vSSRSRB_DriverProfile.[Team Leader Name]
      ,vSSRSRB_DriverProfile.[Fleet]
      ,vSSRSRB_DriverProfile.[Division]
      ,vSSRSRB_DriverProfile.[Domicile]
      ,vSSRSRB_DriverProfile.[Company ID]
      ,vSSRSRB_DriverProfile.[Terminal]
      ,vSSRSRB_DriverProfile.[Driver Status]
      ,vSSRSRB_DriverProfile.[Emergency Phone Number]
      ,vSSRSRB_DriverProfile.[Emergency Contact Name]
      ,vSSRSRB_DriverProfile.[Voice Mail Box]
      ,vSSRSRB_DriverProfile.[Termination Date]
      ,vSSRSRB_DriverProfile.[Available Date]
      ,vSSRSRB_DriverProfile.[Available Company ID]
      ,vSSRSRB_DriverProfile.[Available City]
      ,vSSRSRB_DriverProfile.[Available Status]
      ,vSSRSRB_DriverProfile.[Planned Date]
      ,vSSRSRB_DriverProfile.[Planned Company ID]
      ,vSSRSRB_DriverProfile.[Planned City]
      ,vSSRSRB_DriverProfile.[Planned LegHeader]
      ,vSSRSRB_DriverProfile.[Available LegHeader]
      ,vSSRSRB_DriverProfile.[Driver Last First Name]
      ,vSSRSRB_DriverProfile.[Accounting Type]
      ,vSSRSRB_DriverProfile.[Last Home]
      ,vSSRSRB_DriverProfile.[Want Home]
      ,vSSRSRB_DriverProfile.[Misc1]
      ,vSSRSRB_DriverProfile.[Misc2]
      ,vSSRSRB_DriverProfile.[Misc3]
      ,vSSRSRB_DriverProfile.[Misc4]
      ,vSSRSRB_DriverProfile.[Use Cash Card]
      ,vSSRSRB_DriverProfile.[Updated By]
      ,vSSRSRB_DriverProfile.[Bmp Path Name]
      ,vSSRSRB_DriverProfile.[Updated On]
      ,vSSRSRB_DriverProfile.[Created Date]
      ,vSSRSRB_DriverProfile.[Quick Entry]
      ,vSSRSRB_DriverProfile.[Service Rule]
      ,vSSRSRB_DriverProfile.[GPS Description]
      ,vSSRSRB_DriverProfile.[GPS Date]
      ,vSSRSRB_DriverProfile.[GPS Latitude]
      ,vSSRSRB_DriverProfile.[GPS Longitude]
      ,vSSRSRB_DriverProfile.[Travel Minutes]
      ,vSSRSRB_DriverProfile.[Mile Day 7]
      ,vSSRSRB_DriverProfile.[Home Latitude]
      ,vSSRSRB_DriverProfile.[Home Longitude]
      ,vSSRSRB_DriverProfile.[Last Log Date]
      ,vSSRSRB_DriverProfile.[Hours1]
      ,vSSRSRB_DriverProfile.[Hours2]
      ,vSSRSRB_DriverProfile.[Hours3]
      ,vSSRSRB_DriverProfile.[Hours4]
      ,vSSRSRB_DriverProfile.[Home City]
      ,vSSRSRB_DriverProfile.[Exp1 Date]
      ,vSSRSRB_DriverProfile.[Exp2 Date]
      ,vSSRSRB_DriverProfile.[Next Event]
      ,vSSRSRB_DriverProfile.[Next Company ID]
      ,vSSRSRB_DriverProfile.[Next City]
      ,vSSRSRB_DriverProfile.[Next State]
      ,vSSRSRB_DriverProfile.[Next Region 1]
      ,vSSRSRB_DriverProfile.[Next Region 2]
      ,vSSRSRB_DriverProfile.[Next Region 3]
      ,vSSRSRB_DriverProfile.[Next Region 4]
      ,vSSRSRB_DriverProfile.[Prior Event]
      ,vSSRSRB_DriverProfile.[Prior Company ID]
      ,vSSRSRB_DriverProfile.[Prior City]
      ,vSSRSRB_DriverProfile.[Prior State]
      ,vSSRSRB_DriverProfile.[Prior Region 1]
      ,vSSRSRB_DriverProfile.[Prior Region 2]
      ,vSSRSRB_DriverProfile.[Prior Region 3]
      ,vSSRSRB_DriverProfile.[Prior Region 4]
      ,vSSRSRB_DriverProfile.[Daily Hours Estimate]
      ,vSSRSRB_DriverProfile.[Weekly Hours Estimate]
      ,vSSRSRB_DriverProfile.[Lost Log Company ID]
      ,vSSRSRB_DriverProfile.[Last Log Estitimate Date]
      ,vSSRSRB_DriverProfile.[Last Log Company Name]
      ,vSSRSRB_DriverProfile.[Estimate Log Date Time]
      ,vSSRSRB_DriverProfile.[MaxAssignmentNumber]
      ,vSSRSRB_DriverProfile.[Branch]
      ,vSSRSRB_DriverProfile.[GP Class]
      ,vSSRSRB_DriverProfile.[Qualification List]
      ,vSSRSRB_DriverProfile.[Region1]
      ,vSSRSRB_DriverProfile.[Region2]
      ,vSSRSRB_DriverProfile.[Region3]
      ,vSSRSRB_DriverProfile.[Region4]
      ,vSSRSRB_DriverProfile.[Company Name]
      ,vSSRSRB_DriverProfile.[Division Name]
      ,vSSRSRB_DriverProfile.[Terminal Name]
      ,vSSRSRB_DriverProfile.[Fleet Name]
      ,vSSRSRB_DriverProfile.[DriverCount]
      ,vSSRSRB_DriverProfile.[lgh_number]
      ,vSSRSRB_DriverProfile.[Last Trip Move Number]
      ,vSSRSRB_DriverProfile.[Last Trip Status]
      ,vSSRSRB_DriverProfile.[Last Trip Assignment Date]
      ,vSSRSRB_DriverProfile.[Last Accident Description]
      ,vSSRSRB_DriverProfile.[Last Accident Preventable]
      ,vSSRSRB_DriverProfile.[Last Accident Cost]
      ,vSSRSRB_DriverProfile.[Last Accident Reference Number]
      ,vSSRSRB_DriverProfile.[Miles Since Last Accident]
      ,vSSRSRB_DriverProfile.[Last Trip Tractor]
      ,vSSRSRB_DriverProfile.[Last Trip Final Destination]
      ,vSSRSRB_DriverProfile.[Last Trip Final State]

From   vSSRSRB_SafetyAccident 
	Left Join vSSRSRB_DriverProfile On vSSRSRB_DriverProfile.[Driver ID] = vSSRSRB_SafetyAccident.[Driver1]



GO
GRANT SELECT ON  [dbo].[vSSRSRB_SafetyAccidentByDriver] TO [public]
GO
