SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[Extra_Info_Delete_Data_sp](@Extra_ID INTEGER, @Tab_ID INTEGER, @TableKey VARCHAR(50), @Row INTEGER, @Col_ID INTEGER) AS
BEGIN
	DELETE	EXTRA_INFO_DATA
	WHERE	EXTRA_INFO_DATA.EXTRA_ID = @Extra_ID
		AND EXTRA_INFO_DATA.TAB_ID = @Tab_ID
		AND EXTRA_INFO_DATA.TABLE_KEY = @TableKey
		AND EXTRA_INFO_DATA.COL_ROW = @Row
		AND EXTRA_INFO_DATA.COL_ID = @Col_ID
END
GO
GRANT EXECUTE ON  [dbo].[Extra_Info_Delete_Data_sp] TO [public]
GO
