SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[order_default_extended_sp] 
    @source varchar(30),
    @sourcevalue varchar(30),
    @targetfield varchar(30),
    @userid varchar(30),
    @pvalue char(30) OUTPUT
AS
 --NOTES:
 --
 --@source - identifies the source tag.  this should typically be PROCEDURE
 --
 --@sourcevalue - value from the changed source field
 --
 --@targetfield - The field that will receive the value generated by this procedure
 --                 
 --@userid      - The user id of the user logged into TMWSUITE.  Note, this may be
 --               different from the user id logged into the database (see 
 --               PTS 38839)
 --
 --@pvalue       - Output parameter, will be set with the default value
 --
 --NOTES:  This procedure dynamic calls another stored procedure (provided that one is 
 --        identified in the generalinfo table.  The use of a dynamic stored procedure
 --        allows clients to provide their own default settings.
 --
 --Sample execution string:
 --
 --declare @pvalue varchar(30)
 --exec order_default_extended_sp 'PROCEDURE','017C','SUBCOMPANY','KDECELLE',@pvalue
 --select @pvalue


declare 
@sourceprocedure varchar(100),  --name of the stored procedure that will provide the default subcompany value.
@rtn int                        --return value from the dynamic procecure

select @sourceprocedure = 'NONE'

--default the return value
select @pvalue = null

select @sourceprocedure = gi_string1 from generalinfo where
    upper(gi_name)='ORDERDEFAULTPROC'

select @sourceprocedure=isnull(@sourceprocedure,'NONE')

if @sourceprocedure <>'NONE' and @sourceprocedure<>''
BEGIN
    --build the sql execution string.
    exec @rtn = @sourceprocedure @source,@sourcevalue,@targetfield,@userid,@pvalue output
    
    if @rtn<>0 or @@error<>0 
        set @pvalue = null
                
END
   
GO
GRANT EXECUTE ON  [dbo].[order_default_extended_sp] TO [public]
GO
