SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[TMT_ADDALIAS]
@ASSET_IDTYPE char(7),
@ASSET_ID char(13),
@ALIAS_NAME char(13),
@ERRORCODE int OUTPUT

AS

SET @ERRORCODE=0

IF @ASSET_IDTYPE= 'TRACTOR'
BEGIN
SELECT @ASSET_IDTYPE= 'TRC'
END

IF @ASSET_IDTYPE= 'TRAILER'
BEGIN
SELECT @ASSET_IDTYPE= 'TRL'
END

-- ****************************************************************************
-- Grab Unit Type Definitions from TMT Lookup Table
-- ****************************************************************************
IF @ASSET_IDTYPE <> 'TRC' OR @ASSET_IDTYPE <> 'TRL'
BEGIN
IF EXISTS(SELECT [CODE]
FROM [dbo].[TMTUNITTYPE] (NOLOCK)
WHERE [CODE] = @ASSET_IDTYPE)
BEGIN
SELECT @ASSET_IDTYPE= [TMWDESIGNATION]
FROM [dbo].[TMTUNITTYPE] (NOLOCK)
WHERE [CODE] = @ASSET_IDTYPE
END
END
ELSE
BEGIN
SELECT @ERRORCODE=-1
GOTO ERROR_EXIT
END

IF @ASSET_IDTYPE = 'TRC'
BEGIN
IF NOT EXISTS (SELECT NULL FROM [dbo].[TRACTORPROFILE] WHERE [TRC_NUMBER] = @ASSET_ID)
BEGIN
SELECT @ERRORCODE=-2
GOTO ERROR_EXIT
END
END
ELSE IF @ASSET_IDTYPE = 'TRL'
BEGIN
IF NOT EXISTS (SELECT NULL FROM [dbo].[TRAILERPROFILE] WHERE [TRL_ID] = @ASSET_ID)
BEGIN
SELECT @ERRORCODE=-2
GOTO ERROR_EXIT
END
END

IF (ISNULL(@ALIAS_NAME,'') = '')
BEGIN
SELECT @ERRORCODE=-3
GOTO ERROR_EXIT
END


IF NOT EXISTS (SELECT NULL FROM [dbo].[ASSET_ALIAS] WHERE [ALIAS_TYPE] = @ASSET_IDTYPE AND [ALIAS_NAME] = @ALIAS_NAME AND [ASSET_ID] = @ASSET_ID)
BEGIN
INSERT INTO [dbo].[ASSET_ALIAS] ([ALIAS_TYPE], [ALIAS_NAME], [ASSET_ID]) VALUES(@ASSET_IDTYPE, @ALIAS_NAME, @ASSET_ID)
END

GOTO NO_ERROR_EXIT

ERROR_EXIT:

NO_ERROR_EXIT:

GO
GRANT EXECUTE ON  [dbo].[TMT_ADDALIAS] TO [public]
GO
