SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[OUTBOUND204_PREPROCESS] (@lgh_number INTEGER)
AS
RETURN 1
GO
GRANT EXECUTE ON  [dbo].[OUTBOUND204_PREPROCESS] TO [public]
GO
