SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

/*
Autor: Emilio Olvera
Version : 1.0
SP que agrega las expiraciones de driver por dia sobre un calendario
recibi de parametro la flota y los meses atras o adelante, mes atras con signo de menos
mes actual con 0

exec  sp_exptractormonth  'ABIERTO2', 0


*/


CREATE proc [dbo].[sp_exptractormonth]  @flota varchar(20), @month int

as

SET LANGUAGE Spanish; 

declare @minutedayoffset int = 56

select null as ID, null as Model,'' as DRV,'' as Placa, '' as GPS,
 
  '.' + case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  0))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  0)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  0)),'dd-MM')   end  as dia1,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  1))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  1)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  1)),'dd-MM')   end  as dia2,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  2))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  2)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  2)),'dd-MM')   end  as dia3,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  3))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  3)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  3)),'dd-MM')   end  as dia4,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  4))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  4)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  4)),'dd-MM')   end  as dia5,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  5))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  5)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  5)),'dd-MM')   end  as dia6,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  6))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  6)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  6)),'dd-MM')   end  as dia7,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  7))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  7)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  7)),'dd-MM')   end  as dia8,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  8))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  8)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  8)),'dd-MM')   end  as dia9,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  9))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  9)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  9)),'dd-MM')   end  as dia10,

		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 10))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 10)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 10)),'dd-MM')   end  as dia11,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 11))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 11)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 11)),'dd-MM')   end  as dia12,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 12))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 12)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 12)),'dd-MM')   end  as dia13,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 13))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 13)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 13)),'dd-MM')   end  as dia14,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 14))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 14)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 14)),'dd-MM')   end  as dia15,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 15))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 15)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 15)),'dd-MM')   end  as dia16,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 16))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 16)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 16)),'dd-MM')   end  as dia17,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 17))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 17)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 17)),'dd-MM')   end  as dia18,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 18))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 18)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 18)),'dd-MM')   end  as dia19,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 19))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 19)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 19)),'dd-MM')   end  as dia20,


		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 20))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 20)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 20)),'dd-MM')   end  as dia21,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 21))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 21)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 21)),'dd-MM')   end  as dia22,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 22))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 22)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 22)),'dd-MM')   end  as dia23,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 23))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 23)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 23)),'dd-MM')   end  as dia24,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 24))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 24)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 24)),'dd-MM')   end  as dia25,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 25))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 25)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 25)),'dd-MM')   end  as dia26,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 26))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 26)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 26)),'dd-MM')   end  as dia27,
		case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 27))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 27)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 27)),'dd-MM')   end  as dia28,

        case when  dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 27))   =  dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 28)) then '' else  
	   (case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 28))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 28)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 28 )),'dd-MM')   end ) end as dia29,
       
	    case when  dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 28))   =  dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 29)) then '' else  
	   (case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 29))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 29)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 29 )),'dd-MM')   end ) end as dia30,
       
	    case when  dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 28))   =  dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 29)) then '' else  
	   (case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 30))) = 0 then '**'+  format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 30)),'dd-MM')+ '**' else format(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 30 )),'dd-MM')   end ) end as dia31,
       

  0 as dias,
  0 as mes,
  0 as anio

union

select null as ID, null as Nombre,'','', '' as GPS,
   '.' + case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  0))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 0)))) +'**'  else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 0))))  end as dia1,
         case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  1))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 1)))) +'**'  else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 1))))  end as dia2,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  2))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 2)))) +'**'  else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 2))))  end as dia3,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  3))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 3)))) +'**'  else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 3))))  end as dia4,
         case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  4))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 4)))) +'**'  else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 4))))  end as dia5,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  5))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 5)))) +'**'  else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 5))))  end as dia6,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  6))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 6)))) +'**'  else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 6))))  end as dia7,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  7))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 7)))) +'**'  else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 7))))  end as dia8,
         case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  8))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 8)))) +'**'  else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 8))))  end as dia9,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  9))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 9)))) +'**'  else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 9))))  end as dia10,

		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  10))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 10)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 10))))  end as dia11,
         case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  11))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 11)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 11))))  end as dia12,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  12))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 12)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 12))))  end as dia13,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  13))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 13)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 13))))  end as dia14,
         case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  14))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 14)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 14))))  end as dia15,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  15))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 15)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 15))))  end as dia16,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  16))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 16)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 16))))  end as dia17,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  17))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 17)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 17))))  end as dia18,
         case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  18))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 18)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 18))))  end as dia19,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  19))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 19)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 19))))  end as dia20,

	     case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  20))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 20)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 20))))  end as dia21,
         case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  21))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 21)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 21))))  end as dia22,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  22))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 22)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 22))))  end as dia23,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  23))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 23)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 23))))  end as dia24,
         case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  24))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 24)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 24))))  end as dia25,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  25))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 25)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 25))))  end as dia26,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  26))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 26)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 26))))  end as dia27,
		 case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  27))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 27)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 27))))  end as dia28,


         case when  dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 27))   =  dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 28)) then '' else
		(case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  28))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 28)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 28))))  end) end as dia29,

		 case when  dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 27))   =  dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 28)) then '' else
		(case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  29))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 29)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 29))))  end) end as dia30,

		 case when  dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 27))   =  dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 28)) then '' else
		(case when  datediff(day,getdate(),dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()),  30))) = 0 then '**'+ datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 30)))) +'**' else datename(dw,(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 30))))  end) end as dia31,

 0 as dias,
 0 as mes,
 0 as anio

union


select trc_number,
       	 case when (select count(*)from tractoraccesories where  tca_tractor= trc_number and tca_type = 'SIS') >'0' then '6x2 ' else '' end   + trc_model+ ' ' + cast(trc_year as varchar(20)) as model,
	   isnull(trc_driver + ' | '+ (select mpp_firstname + ' ' + mpp_lastname from manpowerprofile where mpp_id = trc_driver),'Unseated'),
	   trc_licnum,
	   cast( trc_gps_Date as varchar(20)) + ' | ' + trc_gps_desc,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and  dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 0)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia1,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and  dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 1)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia2,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and  dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 2)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia3,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and  dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 3)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia4,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and  dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 4)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia5,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and  dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 5)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia6,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and  dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 6)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia7,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and  dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 7)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia8,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and  dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 8)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia9,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and  dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 9)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia10,

	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 10)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia11,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 11)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia12,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 12)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia13,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 13)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia14,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 14)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia15,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 15)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia16,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 16)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia17,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 17)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia18,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 18)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia19,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 19)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia20,

	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 20)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia21,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 21)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia22,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 22)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia23,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 23)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia24,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 24)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia25,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 25)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia26,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 26)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia27,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 27)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia28,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 28)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia29,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 29)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia30,
	STUFF(( select ',' + exp_code   from expiration where exp_idtype = 'TRC'  and exp_code in (select abbr from labelfile where labeldefinition = 'TRCexp' and code > 197) and   dateadd(MONTH,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 30)) between CAST(CAST(exp_expirationdate AS DATE) AS DATETIME) and case when DATEDIFF(day,exp_expirationdate, exp_compldate)>= 1 then  dateadd(minute, -@minutedayoffset,exp_compldate) else exp_compldate  end  and exp_id = trc_number  FOR XML PATH('')  ), 1, 1, '')as dia31,
	datediff(day, dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 0)), dateadd(month, 1, dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 0)))) as dias,
	month(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 1))) as mes,
	year(dateadd(month,@month,DATEADD(m, DATEDIFF(m, 0, GETDATE()), 1))) as anio

    

from tractorprofile
where
trc_fleet =  (select abbr from labelfile where labeldefinition = 'fleet' and name in (@flota )) and 
trc_status <> 'OUT' and trc_number <> 'UNKNOWN'

GO
