SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[Extra_Info_Get_Label_List_sp](@Label VARCHAR(50)) AS
BEGIN

IF EXISTS (SELECT 1 FROM EXTRA_INFO_COLS WHERE EXTRA_INFO_COLS.LABEL = @Label)
SELECT	NAME,
ABBR,
CODE,
LOCKED,
USERLABELNAME,
SYSTEMCODE,
RETIRED
FROM LABELFILE where labeldefinition = @Label

END
GO
GRANT EXECUTE ON  [dbo].[Extra_Info_Get_Label_List_sp] TO [public]
GO
