SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   PROCEDURE [dbo].[TMT_EXP_BATCH_COMPLETE]
AS
DECLARE @DEBUG INTEGER

SET @DEBUG = 0	-- 0 = Off, 1 = On
IF @DEBUG = 1 Print 'TMT_EXP_BATCH_COMPLETE'

-- Delete any PMs that were not sent that are not assoiciated with a RO.
IF (SELECT COUNT(1) FROM TMT_EXPIRATIONS WHERE EXP_TRANSFER_STATUS IS NOT NULL AND EXP_CODE = 'PRE' AND EXP_ORDERID = -1) > 0 -- MAKE SURE THAT THE JOB HAS RUN.
BEGIN
IF @DEBUG = 1 Print 'Deleting expirations that are no longer valid.'
DELETE from EXPIRATION where EXP_KEY in (select EXP_KEY from TMT_EXPIRATIONS where EXP_TRANSFER_STATUS IS NULL and EXP_CODE = 'PRE' AND EXP_ORDERID = -1) and EXP_CODE = 'PRE'
DELETE from TMT_EXPIRATIONS where EXP_TRANSFER_STATUS IS NULL and EXP_CODE = 'PRE' AND EXP_ORDERID = -1
UPDATE TMT_EXPIRATIONS set EXP_TRANSFER_STATUS = NULL
END

-- Validate that the expirations have not been completed in TMWS and not in AMS.
UPDATE EXPIRATION set EXP_COMPLETED = 'N' WHERE EXP_KEY IN (SELECT EXP_KEY FROM TMT_EXPIRATIONS WHERE EXP_COMPLETED = 'N') AND EXP_COMPLETED = 'Y' AND EXP_CODE <> 'OUT'

-- Check for deleted expirations.
DELETE FROM TMT_EXPIRATIONS WHERE EXP_KEY not in (SELECT EXP_KEY FROM expiration WHERE EXP_KEY = TMT_EXPIRATIONS.EXP_KEY)

GO
GRANT EXECUTE ON  [dbo].[TMT_EXP_BATCH_COMPLETE] TO [public]
GO
