SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


----------------------------------
--- TMT AMS from TMWSYSTEMS
---
--- CHANGED 12/3/2014  MB TASK:538
--- CHANGED 6/11/2013  MB PCR:8541
--- CHANGED 1/31/2013  MB PCR:8541
---  CHANGED 1/29/2013  MB PCR:8541
---  CREATED 1/22/2013 KM (PCR: 8541)
----------------------------------
CREATE PROCEDURE [dbo].[TMT_PAYTO_TO_CUSTOMER_TRANSFER_SP]
(
@ERROR INT OUTPUT ,
@daysBack INT = NULL ,          -- Days to go back before @LatestDate
-- is NULL 1 day is used	@err varchar(255) output)
@LatestDate DATETIME = NULL   -- Last Move date
-- If Null Midnight of previous day is used



)
AS
DECLARE	@Lowdate DATETIME
DECLARE	@HighDate DATETIME
DECLARE	@LOCALERRORID INT

SELECT	@ERROR = 0


IF ISNULL(@daysBack, '') = ''
SET @daysBack = 7
IF ISNULL(@LatestDate, '') = ''
SET @LatestDate = CONVERT(DATETIME, FLOOR(CONVERT(FLOAT, GETDATE() + 1)))
SET @HighDate = @LatestDate
SET @Lowdate = CONVERT   (DATETIME, FLOOR(CONVERT (FLOAT, @HighDate))
- @daysBack)



DECLARE	@MINTEMPID [INTEGER]
DECLARE	@MAXTEMPID [INTEGER]
DECLARE	@ERRORID [INTEGER]
DECLARE	@PTO_ID [VARCHAR](12)
DECLARE	@PTO_ALTID CHAR(12)
DECLARE	@PTO_FNAME VARCHAR(20)
DECLARE	@PTO_MNAME CHAR(1)
DECLARE	@PTO_LNAME VARCHAR(20)
DECLARE	@PTO_SSN CHAR(9)
DECLARE	@PTO_ADDRESS1 VARCHAR(30)
DECLARE	@PTO_ADDRESS2 VARCHAR(30)
DECLARE	@CITY VARCHAR(18)
DECLARE	@PTO_ZIP VARCHAR(10)
DECLARE	@PTO_PHONE1 CHAR(10)
DECLARE	@PTO_PHONE2 CHAR(10)
DECLARE	@PTO_PHONE3 CHAR(10)
DECLARE	@PTO_CURRENCY CHAR(6)
DECLARE	@PTO_TYPE1 CHAR(6)
DECLARE	@PTO_TYPE2 CHAR(6)
DECLARE	@PTO_TYPE3 CHAR(6)
DECLARE	@PTO_TYPE4 CHAR(6)
DECLARE	@PTO_COMPANY CHAR(6)
DECLARE	@PTO_DIVISION CHAR(6)
DECLARE	@PTO_TERMINAL CHAR(6)
DECLARE	@PTO_STATUS CHAR(6)
DECLARE	@PTO_LASTFIRST VARCHAR(45)
DECLARE	@PTO_FLEET VARCHAR(6)
DECLARE	@PTO_MISC1 VARCHAR(254)
DECLARE	@PTO_MISC2 VARCHAR(254)
DECLARE	@PTO_MISC3 VARCHAR(254)
DECLARE	@PTO_MISC4 VARCHAR(254)
DECLARE	@PTO_UPDATEDBY VARCHAR(20)
DECLARE	@PTO_UPDATEDDATE DATETIME
DECLARE	@PTO_YRTODATEGROSS MONEY
DECLARE	@PTO_SOCSECFEDTAX VARCHAR(10)
DECLARE	@PTO_DIRDEPOSIT CHAR(6)
DECLARE	@PTO_FLEETTRC VARCHAR(8)
DECLARE	@PTO_STARTDATE DATETIME
DECLARE	@PTO_TERMINATEDATE DATETIME
DECLARE	@PTO_CREATEDATE DATETIME
DECLARE	@PTO_COMPANYNAME VARCHAR(65)
DECLARE	@PTO_COUNTRY VARCHAR(6)
DECLARE	@PTO_GP_CLASS CHAR(11)
DECLARE	@PTO_FACTORID VARCHAR(12)
DECLARE	@PTO_ASSET_MAINTENANCE_TYPE1 VARCHAR(12)
DECLARE	@PTO_ASSET_MAINTENANCE_TYPE2 VARCHAR(12)
DECLARE	@PTO_ASSET_MAINTENANCE_TYPE3 VARCHAR(12)
DECLARE	@STATE CHAR(6)
DECLARE	@SQL [NVARCHAR](4000)
DECLARE	@TMTSERVER VARCHAR(25)
DECLARE	@TMTDB VARCHAR(25)
DECLARE	@CUSTTYPE VARCHAR(12)
DECLARE	@SERVERTEST VARCHAR(24)
DECLARE	@SSTRING VARCHAR(70)
DECLARE	@STOPSERVICE CHAR(1)
DECLARE	@PAYTO TABLE
(
[TEMPID] [INTEGER] IDENTITY(1, 1) ,
[PTO_ID] [VARCHAR](12) NOT NULL ,
[PTO_ALTID] [CHAR](12) NULL ,
[PTO_FNAME] [VARCHAR](20) NULL ,
[PTO_MNAME] [CHAR](1) NULL ,
[PTO_LNAME] [VARCHAR](20) NOT NULL ,
[PTO_SSN] [CHAR](9) NULL ,
[PTO_ADDRESS1] [VARCHAR](30) NULL ,
[PTO_ADDRESS2] [VARCHAR](30) NULL ,
[CITY] [VARCHAR](18) NULL ,
[PTO_ZIP] [VARCHAR](10) NULL ,
[PTO_PHONE1] [CHAR](10) NULL ,
[PTO_PHONE2] [CHAR](10) NULL ,
[PTO_PHONE3] [CHAR](10) NULL ,
[PTO_CURRENCY] [CHAR](6) NULL ,
[PTO_TYPE1] [CHAR](6) NULL ,
[PTO_TYPE2] [CHAR](6) NULL ,
[PTO_TYPE3] [CHAR](6) NULL ,
[PTO_TYPE4] [CHAR](6) NULL ,
[PTO_COMPANY] [CHAR](6) NULL ,
[PTO_DIVISION] [CHAR](6) NULL ,
[PTO_TERMINAL] [CHAR](6) NULL ,
[PTO_STATUS] [CHAR](6) NULL ,
[PTO_LASTFIRST] [VARCHAR](45) NULL ,
[PTO_FLEET] [VARCHAR](6) NULL ,
[PTO_MISC1] [VARCHAR](254) NULL ,
[PTO_MISC2] [VARCHAR](254) NULL ,
[PTO_MISC3] [VARCHAR](254) NULL ,
[PTO_MISC4] [VARCHAR](254) NULL ,
[PTO_UPDATEDBY] [VARCHAR](20) NULL ,
[PTO_UPDATEDDATE] [DATETIME] NULL ,
[PTO_YRTODATEGROSS] [MONEY] NULL ,
[PTO_SOCSECFEDTAX] [VARCHAR](10) NULL ,
[PTO_DIRDEPOSIT] [CHAR](6) NULL ,
[PTO_FLEETTRC] [VARCHAR](8) NULL ,
[PTO_STARTDATE] [DATETIME] NULL ,
[PTO_TERMINATEDATE] [DATETIME] NULL ,
[PTO_CREATEDATE] [DATETIME] NULL ,
[PTO_COMPANYNAME] [VARCHAR](65) NULL ,
[PTO_COUNTRY] [VARCHAR](6) NULL ,
[PTO_GP_CLASS] [CHAR](11) NOT NULL ,
[PTO_FACTORID] [VARCHAR](12) NOT NULL ,
[PTO_ASSET_MAINTENANCE_TYPE1] [VARCHAR](12) NOT NULL ,
[PTO_ASSET_MAINTENANCE_TYPE2] [VARCHAR](12) NOT NULL ,
[PTO_ASSET_MAINTENANCE_TYPE3] [VARCHAR](12) NOT NULL ,
[STATE] [VARCHAR](6) NULL
)


INSERT	INTO @PAYTO
( [PTO_ID] ,
[PTO_ALTID] ,
[PTO_FNAME] ,
[PTO_MNAME] ,
[PTO_LNAME] ,
[PTO_SSN] ,
[PTO_ADDRESS1] ,
[PTO_ADDRESS2] ,
[CITY] ,
[PTO_ZIP] ,
[PTO_PHONE1] ,
[PTO_PHONE2] ,
[PTO_PHONE3] ,
[PTO_CURRENCY] ,
[PTO_TYPE1] ,
[PTO_TYPE2] ,
[PTO_TYPE3] ,
[PTO_TYPE4] ,
[PTO_COMPANY] ,
[PTO_DIVISION] ,
[PTO_TERMINAL] ,
[PTO_STATUS] ,
[PTO_LASTFIRST] ,
[PTO_FLEET] ,
[PTO_MISC1] ,
[PTO_MISC2] ,
[PTO_MISC3] ,
[PTO_MISC4] ,
[PTO_UPDATEDBY] ,
[PTO_UPDATEDDATE] ,
[PTO_YRTODATEGROSS] ,
[PTO_SOCSECFEDTAX] ,
[PTO_DIRDEPOSIT] ,
[PTO_FLEETTRC] ,
[PTO_STARTDATE] ,
[PTO_TERMINATEDATE] ,
[PTO_CREATEDATE] ,
[PTO_COMPANYNAME] ,
[PTO_COUNTRY] ,
[PTO_GP_CLASS] ,
[PTO_FACTORID] ,
[PTO_ASSET_MAINTENANCE_TYPE1] ,
[PTO_ASSET_MAINTENANCE_TYPE2] ,
[PTO_ASSET_MAINTENANCE_TYPE3] ,
[STATE]

)
SELECT	[PTO_ID] ,
[PTO_ALTID] ,
[PTO_FNAME] ,
[PTO_MNAME] ,
[PTO_LNAME] ,
[PTO_SSN] ,
[PTO_ADDRESS1] ,
[PTO_ADDRESS2] ,
PTC.[CTY_NAME] AS CITY ,
[PTO_ZIP] ,
[PTO_PHONE1] ,
[PTO_PHONE2] ,
[PTO_PHONE3] ,
[PTO_CURRENCY] ,
[PTO_TYPE1] ,
[PTO_TYPE2] ,
[PTO_TYPE3] ,
[PTO_TYPE4] ,
[PTO_COMPANY] ,
[PTO_DIVISION] ,
[PTO_TERMINAL] ,
[PTO_STATUS] ,
[PTO_LASTFIRST] ,
[PTO_FLEET] ,
[PTO_MISC1] ,
[PTO_MISC2] ,
[PTO_MISC3] ,
[PTO_MISC4] ,
[PTO_UPDATEDBY] ,
[PTO_UPDATEDDATE] ,
[PTO_YRTODATEGROSS] ,
[PTO_SOCSECFEDTAX] ,
[PTO_DIRDEPOSIT] ,
[PTO_FLEETTRC] ,
[PTO_STARTDATE] ,
[PTO_TERMINATEDATE] ,
[PTO_CREATEDATE] ,
[PTO_COMPANYNAME] ,
[PTO_COUNTRY] ,
[PTO_GP_CLASS] ,
[PTO_FACTORID] ,
[PTO_ASSET_MAINTENANCE_TYPE1] ,
[PTO_ASSET_MAINTENANCE_TYPE2] ,
[PTO_ASSET_MAINTENANCE_TYPE3] ,
[PTC].[CTY_STATE]
FROM		[dbo].[PAYTO] PT WITH ( NOLOCK )
INNER JOIN [dbo].[CITY] PTC WITH ( NOLOCK ) ON PT.[PTO_CITY] = PTC.[CTY_CODE]
WHERE		ISNULL([PTO_SOCSECFEDTAX], 'S') <> 'F'
AND [PTO_ID] IS NOT NULL
AND [pto_updateddate] BETWEEN @Lowdate AND @HighDate

SET @SERVERTEST = CONVERT(CHAR(24), SERVERPROPERTY('SERVERNAME'))


SELECT	@tmtdb = GI_STRING2 ,
@TMTSERVER = ISNULL(GI_STRING1, @SERVERTEST)
FROM		GENERALINFO (NOLOCK)
WHERE		GI_NAME = 'Shoplink'

IF ( @TMTSERVER = @SERVERTEST )
BEGIN
SET @SSTRING = ' .[' + RTRIM(@tmtdb) + '].[dbo].'
END
ELSE
BEGIN
SET @SSTRING = ' [' + RTRIM(@TMTSERVER) + '].[' + RTRIM(@tmtdb)
+ '].[dbo].'
END




SELECT	@MINTEMPID = ISNULL(MIN([TEMPID]), 1)
FROM		@PAYTO
SELECT	@MAXTEMPID = ( ISNULL(MAX([TEMPID]), 1) + 1 )
FROM		@PAYTO

WHILE @MINTEMPID < @MAXTEMPID
BEGIN
SELECT	@PTO_ID = [PTO_ID] ,
@PTO_ALTID = [PTO_ALTID] ,
@PTO_FNAME = [PTO_FNAME] ,
@PTO_MNAME = [PTO_MNAME] ,
@PTO_LNAME = [PTO_LNAME] ,
@PTO_SSN = [PTO_SSN] ,
@PTO_ADDRESS1 = ISNULL(NULLIF([PTO_ADDRESS1], ''),
'Unknown') ,
@PTO_ADDRESS2 = [PTO_ADDRESS2] ,
@CITY = [CITY] ,
@PTO_ZIP = [PTO_ZIP] ,
@PTO_PHONE1 = [PTO_PHONE1] ,
@PTO_PHONE2 = [PTO_PHONE2] ,
@PTO_PHONE3 = [PTO_PHONE3] ,
@PTO_CURRENCY = [PTO_CURRENCY] ,
@PTO_TYPE1 = [PTO_TYPE1] ,
@PTO_TYPE2 = [PTO_TYPE2] ,
@PTO_TYPE3 = [PTO_TYPE3] ,
@PTO_TYPE4 = [PTO_TYPE4] ,
@PTO_COMPANY = [PTO_COMPANY] ,
@PTO_DIVISION = [PTO_DIVISION] ,
@PTO_TERMINAL = [PTO_TERMINAL] ,
@PTO_STATUS = [PTO_STATUS] ,
@PTO_LASTFIRST = [PTO_LASTFIRST] ,
@PTO_FLEET = [PTO_FLEET] ,
@PTO_MISC1 = [PTO_MISC1] ,
@PTO_MISC2 = [PTO_MISC2] ,
@PTO_MISC3 = [PTO_MISC3] ,
@PTO_MISC4 = [PTO_MISC4] ,
@PTO_UPDATEDBY = [PTO_UPDATEDBY] ,
@PTO_UPDATEDDATE = [PTO_UPDATEDDATE] ,
@PTO_YRTODATEGROSS = [PTO_YRTODATEGROSS] ,
@PTO_SOCSECFEDTAX = [PTO_SOCSECFEDTAX] ,
@PTO_DIRDEPOSIT = [PTO_DIRDEPOSIT] ,
@PTO_FLEETTRC = [PTO_FLEETTRC] ,
@PTO_STARTDATE = [PTO_STARTDATE] ,
@PTO_TERMINATEDATE = NULLIF([PTO_TERMINATEDATE],
'2049-12-31 00:00:00.000') ,
@PTO_CREATEDATE = [PTO_CREATEDATE] ,
@PTO_COMPANYNAME = ISNULL([PTO_COMPANYNAME],
[PTO_LASTFIRST]) ,
@PTO_COUNTRY = [PTO_COUNTRY] ,
@PTO_GP_CLASS = [PTO_GP_CLASS] ,
@PTO_FACTORID = [PTO_FACTORID] ,
@PTO_ASSET_MAINTENANCE_TYPE1 = ISNULL(NULLIF([PTO_ASSET_MAINTENANCE_TYPE1],
'UNK'), 'ESC') -- PRICE TABLE
,
@PTO_ASSET_MAINTENANCE_TYPE2 = ISNULL(NULLIF([PTO_ASSET_MAINTENANCE_TYPE2],
'UNK'), 'IC')  -- CUST TYPE
,
@PTO_ASSET_MAINTENANCE_TYPE3 = ISNULL(NULLIF([PTO_ASSET_MAINTENANCE_TYPE3],
'UNK'), 'CHARGE')  -- PAYMETHOD
,
@STATE = [STATE]
FROM		@PAYTO
WHERE		[TEMPID] = @MINTEMPID




IF ISNULL(@PTO_TERMINATEDATE, '01/02/1901') = '01/02/1901'
OR ISNULL(@PTO_TERMINATEDATE, '2049-12-31 00:00:00.000') = '2049-12-31 00:00:00.000'
BEGIN
SET @STOPSERVICE = 'N'
END
ELSE
BEGIN
SET @STOPSERVICE = 'Y'
END

SELECT	@PTO_TERMINATEDATE ,
@STOPSERVICE ,
@PTO_COMPANYNAME ,
@PTO_ID

--- Call to SP here include Cross server code

SET @SQL = N'EXECUTE  ' + @SSTRING
+ '[TMWAMSEXT_CUSTOMERS_CREATE] @LOCALERRORID OUTPUT
,@LOCALCUSTOMERID,@LOCALNAME,@LOCALCUSTTYPE
,@LOCALADDRESS1,@LOCALADDRESS2,@LOCALCITY,@LOCALSTATE
,@LOCALZIPCODE,@LOCALCOUNTRY,@LOCALCOUNTY,@LOCALMAINPHONE
,@LOCALPHONEEXT,@LOCALFAXNUMBER,@LOCALEMAIL,@LOCALACTIVECODE
,@LOCALFEDTAXID,@LOCALTAXEXEMPT,@LOCALPRICETBL,@LOCALPAYTERMS
,@LOCALSTOPSERVICE,@LOCALREQPONO,@LOCALBILLATCLOSE,@LOCALBILLNAME
,@LOCALBILLADDRESS1,@LOCALBILLADDRESS2,@LOCALBILLCITY,@LOCALBILLSTATE
,@LOCALBILLZIP,@LOCALACCTTYPE,@LOCALENFORCECREDIT,@LOCALCREDITLIMIT
,@LOCALINVOICELIMIT,@LOCALTAXMETHOD,@LOCALALLOWRPTACCESS,@LOCALEMAILINVOICE,
@LOCALPAYMETHOD'


SET @ERRORID = 0

EXEC SP_EXECUTESQL @SQL, N' @LOCALERRORID INT OUTPUT
,@LOCALCUSTOMERID VARCHAR(12)
,@LOCALNAME VARCHAR(60)
,@LOCALCUSTTYPE VARCHAR(12)
,@LOCALADDRESS1 VARCHAR(35)
,@LOCALADDRESS2 VARCHAR(35)
,@LOCALCITY VARCHAR(20)
,@LOCALSTATE VARCHAR(12)
,@LOCALZIPCODE VARCHAR(16)
,@LOCALCOUNTRY VARCHAR(12)
,@LOCALCOUNTY VARCHAR(24)
,@LOCALMAINPHONE VARCHAR(20)
,@LOCALPHONEEXT VARCHAR(6)
,@LOCALFAXNUMBER VARCHAR(20)
,@LOCALEMAIL VARCHAR(254)
,@LOCALACTIVECODE CHAR(1)
,@LOCALFEDTAXID VARCHAR(24)
,@LOCALTAXEXEMPT CHAR(1)
,@LOCALPRICETBL VARCHAR(12)
,@LOCALPAYTERMS VARCHAR(12)
,@LOCALSTOPSERVICE CHAR(1)
,@LOCALREQPONO CHAR(1)
,@LOCALBILLATCLOSE CHAR(1)
,@LOCALBILLNAME VARCHAR(35)
,@LOCALBILLADDRESS1 VARCHAR(35)
,@LOCALBILLADDRESS2 VARCHAR(35)
,@LOCALBILLCITY VARCHAR(20)
,@LOCALBILLSTATE VARCHAR(12)
,@LOCALBILLZIP VARCHAR(16)
,@LOCALACCTTYPE VARCHAR(12)
,@LOCALENFORCECREDIT CHAR(1)
,@LOCALCREDITLIMIT NUMERIC(15,6)
,@LOCALINVOICELIMIT NUMERIC(15,6)
,@LOCALTAXMETHOD CHAR(1)
,@LOCALALLOWRPTACCESS CHAR(1)
,@LOCALEMAILINVOICE CHAR(1)
,@LOCALPAYMETHOD VARCHAR(12)',
@ERRORID OUTPUT, @PTO_ID  -- CUSTNAME
, @PTO_COMPANYNAME  -- @LOCALNAME
, @PTO_ASSET_MAINTENANCE_TYPE2 -- @LOCALCUSTTYPE
, @PTO_ADDRESS1, @PTO_ADDRESS2, @CITY, @STATE -- STATE???
, @PTO_ZIP, @PTO_COUNTRY, NULL -- COUNTY
, @PTO_PHONE1 -- MAIN PHONE
, NULL -- @LOCALPHONEEXT
, @PTO_PHONE2 -- @LOCALFAXNUMBER
, NULL -- @LOCALEMAIL
, 'Y', @PTO_SOCSECFEDTAX -- @LOCALFEDTAXID
, 'N' --@LOCALTAXEXEMPT??
, @PTO_ASSET_MAINTENANCE_TYPE1 -- @LOCALPRICETBLID Required
, NULL -- @LOCALPAYTERMS
, @STOPSERVICE -- @LOCALSTOPSERVICE
, NULL  -- @LOCALREQPONO
, NULL-- @LOCALBILLATCLOSE
, NULL -- @LOCALBILLNAME
, NULL, NULL, NULL, NULL, NULL -- @LOCALBILLZIP
, NULL -- @LOCALACCTTYPE
, NULL -- @LOCALENFORCECREDIT
, NULL -- @LOCALCREDITLIMIT
, NULL -- @LOCALINVOICELIMIT
, NULL -- @LOCALTAXMETHOD
, NULL -- @LOCALALLOWRPTACCESS
, NULL -- @LOCALEMAILINVOICE
, @PTO_ASSET_MAINTENANCE_TYPE3 -- @LOCALPAYMETHOD



SELECT	@PTO_COMPANYNAME  -- @LOCALNAME
,
@PTO_ASSET_MAINTENANCE_TYPE2 AS LOCALCUSTTYPE -- @LOCALCUSTTYPE
,
@PTO_ADDRESS1 ,
@PTO_ADDRESS2 ,
@CITY ,
@STATE -- STATE???
,
@PTO_ZIP ,
@PTO_COUNTRY ,
NULL -- COUNTY
,
@PTO_PHONE1 -- MAIN PHONE
,
NULL -- @LOCALPHONEEXT
,
@PTO_PHONE2 -- @LOCALFAXNUMBER
,
NULL -- @LOCALEMAIL
,
'Y' ,
@PTO_SOCSECFEDTAX -- @LOCALFEDTAXID
,
'N' --@LOCALTAXEXEMPT??
,
@PTO_ASSET_MAINTENANCE_TYPE1 AS LOCALPRICETBL -- @LOCALPRICETBLID Required
,
NULL -- @LOCALPAYTERMS
,
@STOPSERVICE -- @LOCALSTOPSERVICE
,
NULL  -- @LOCALREQPONO
,
NULL-- @LOCALBILLATCLOSE
,
NULL -- @LOCALBILLNAME
,
NULL ,
NULL ,
NULL ,
NULL ,
NULL -- @LOCALBILLZIP
,
NULL -- @LOCALACCTTYPE
,
NULL -- @LOCALENFORCECREDIT
,
NULL -- @LOCALCREDITLIMIT
,
NULL -- @LOCALINVOICELIMIT
,
NULL -- @LOCALTAXMETHOD
,
NULL -- @LOCALALLOWRPTACCESS
,
NULL -- @LOCALEMAILINVOICE
,
@PTO_ASSET_MAINTENANCE_TYPE3 AS LOCALPAYMETHOD -- @LOCALPAYMETHOD




IF @LOCALERRORID > 0
AND @ERROR = 0
BEGIN
SELECT	@ERROR = -1
END



SELECT	@PTO_ALTID = NULL ,
@PTO_FNAME = NULL ,
@PTO_MNAME = NULL ,
@PTO_LNAME = NULL ,
@PTO_SSN = NULL ,
@PTO_ADDRESS1 = NULL ,
@PTO_ADDRESS2 = NULL ,
@CITY = NULL ,
@STATE = NULL ,
@PTO_ZIP = NULL ,
@PTO_PHONE1 = NULL ,
@PTO_PHONE2 = NULL ,
@PTO_PHONE3 = NULL ,
@PTO_CURRENCY = NULL ,
@PTO_TYPE1 = NULL ,
@PTO_TYPE2 = NULL ,
@PTO_TYPE3 = NULL ,
@PTO_TYPE4 = NULL ,
@PTO_COMPANY = NULL ,
@PTO_DIVISION = NULL ,
@PTO_TERMINAL = NULL ,
@PTO_STATUS = NULL ,
@PTO_LASTFIRST = NULL ,
@PTO_FLEET = NULL ,
@PTO_MISC1 = NULL ,
@PTO_MISC2 = NULL ,
@PTO_MISC3 = NULL ,
@PTO_MISC4 = NULL ,
@PTO_UPDATEDBY = NULL ,
@PTO_UPDATEDDATE = NULL ,
@PTO_YRTODATEGROSS = NULL ,
@PTO_SOCSECFEDTAX = NULL ,
@PTO_DIRDEPOSIT = NULL ,
@PTO_FLEETTRC = NULL ,
@PTO_STARTDATE = NULL ,
@PTO_TERMINATEDATE = NULL ,
@PTO_CREATEDATE = NULL ,
@PTO_COMPANYNAME = NULL ,
@PTO_COUNTRY = NULL ,
@PTO_GP_CLASS = NULL ,
@PTO_FACTORID = NULL ,
@PTO_ASSET_MAINTENANCE_TYPE1 = NULL ,
@PTO_ASSET_MAINTENANCE_TYPE2 = NULL ,
@PTO_ASSET_MAINTENANCE_TYPE3 = NULL

SET @MINTEMPID = @MINTEMPID + 1
END


GO
GRANT EXECUTE ON  [dbo].[TMT_PAYTO_TO_CUSTOMER_TRANSFER_SP] TO [public]
GO
