SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[order_default_ext_trimac_sp] 
    @source varchar(30),
    @sourcevalue varchar(30),
    @targetfield varchar(30),
    @userid varchar(30),
    @pvalue char(30) OUTPUT
AS
 --NOTES:
 --
 --This is the trimac procedure for dynamic order defaults.
 --
 --@source - identifies the source tag.  this should typically be PROCEDURE but may be SHIPPER, CONSIGNEE, BILLTO
 --
 --@sourcevalue - value from the changed source field
 --
 --@targetfield - The field that will receive the value generated by this procedure
 --                 
 --@userid      - The user id of the user logged into TMWSUITE.  Note, this may be
 --               different from the user id logged into the database (see 
 --               PTS 38839)
 --
 --@pvalue       - Output parameter, will be set with the default value
 --
 --NOTES:  This procedure dynamic calls another stored procedure (provided that one is 
 --        identified in the generalinfo table.  The use of a dynamic stored procedure
 --        allows clients to provide their own default settings.
 --
 --Sample execution string:
 --
 --declare @pvalue varchar(100)
 --exec order_default_extended001_sp 'SHIPPER','017C','SUBCOMPANY','KDECELLE',@pvalue output
 --select @pvalue


declare 
    @rtn int  --return value 
    
    set @rtn = 0

    --This procedure is currently only producing defaults for SUBCOMPANY
    if @targetfield='SUBCOMPANY'
    BEGIN
        if isnull(@sourcevalue,'')='' 
        BEGIN
            select @pvalue = brn_orgtype1 
                from branch
                    inner join ttsusers on branch.brn_id=ttsusers.usr_type1
            where ttsusers.usr_userid = @userid
        END
        ELSE
        BEGIN
            select @pvalue = brn_orgtype1 
                from branch where brn_id = @sourcevalue
        END                    
    END    
              
   
   return @rtn
GO
GRANT EXECUTE ON  [dbo].[order_default_ext_trimac_sp] TO [public]
GO
