SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[settlement_default_rate_sp] 
    @source             varchar(30),
    @sourcevalue        varchar(30),
    @targetfield        varchar(30),
    @sparm1             varchar(30),
    @sparm2             varchar(30),
    @sparm3             varchar(30),
    @defrate            decimal(14,4) OUTPUT
AS
 --NOTES:
 --
 --@source - identifies the source tag.  this should typically be PROCEDURE
 --
 --@sourcevalue - value from the changed source field
 --
 --@targetfield - The field that will receive the value generated by this procedure
 --                 
 --@sparm1 - 1st generic string parm
 --
 --@sparm2 - 2nd generic string parm
 --
 --@sparm3 - 3rd generic string parm
 --
 --@def_rate       - Output parameter, will be set with the default $ value returned 
 --
 --NOTES:  This procedure dynamic calls another stored procedure (provided that one is 
 --        identified in the generalinfo table.  The use of a dynamic stored procedure
 --        allows clients to provide their own default settings.
 --
 --Sample execution string:
 --
 --declare @def_rate decimal(14,4)
 --exec order_default_extended_sp 'PROCEDURE,'','PYD_RATE','DRV','DOEJOH','', @def_rate output
 --select @def_rate

    DECLARE     @sourceprocedure varchar(100)   --name of the stored procedure 
                                                --that will provide the default stlmt rate value.
    DECLARE     @rtn             int            --return value from the dynamic procecure
    DECLARE     @spErr           int   
    
    SET @sourceprocedure = 'NONE'
    SET @defrate = null
    SET @rtn = 0
    
    SELECT @sourceprocedure = gi_string1 
    FROM generalinfo 
    WHERE UPPER(gi_name)= 'STLMNTDEFAULTRATEPROC'
    
    SET @sourceprocedure = ISNULL(@sourceprocedure,'NONE')

    IF @sourceprocedure <>'NONE' and @sourceprocedure<>''
    BEGIN
                        
        EXEC @rtn = @sourceprocedure @source,@sourcevalue,@targetfield,@sparm1,
                    @sparm2,@sparm3,@defrate output
                                                           
    END
    
    RETURN @rtn
   
GO
GRANT EXECUTE ON  [dbo].[settlement_default_rate_sp] TO [public]
GO
