SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[Extra_Info_Set_Data_sp](@Extra_ID INTEGER, @Tab_ID INTEGER, @TableKey VARCHAR(50), @Row INTEGER, @Col_ID INTEGER, @ColData VARCHAR(7665)) AS
BEGIN

if exists (
SELECT 1
FROM	EXTRA_INFO_DATA
WHERE	EXTRA_INFO_DATA.EXTRA_ID = @Extra_ID
AND EXTRA_INFO_DATA.TAB_ID = @Tab_ID
AND EXTRA_INFO_DATA.TABLE_KEY = @TableKey
AND EXTRA_INFO_DATA.COL_ROW = @Row
AND EXTRA_INFO_DATA.COL_ID = @Col_ID)
UPDATE	EXTRA_INFO_DATA set COL_DATA = @ColData
FROM 	EXTRA_INFO_DATA
WHERE	EXTRA_INFO_DATA.EXTRA_ID = @Extra_ID
AND EXTRA_INFO_DATA.TAB_ID = @Tab_ID
AND EXTRA_INFO_DATA.TABLE_KEY = @TableKey
AND EXTRA_INFO_DATA.COL_ROW = @Row
AND EXTRA_INFO_DATA.COL_ID = @Col_ID
else
INSERT INTO EXTRA_INFO_DATA (EXTRA_ID, TAB_ID,COL_ID, COL_DATA, TABLE_KEY, COL_ROW)
values	(@Extra_ID, @Tab_ID, @Col_ID, @ColData, @tablekey, @Row)

END
GO
GRANT EXECUTE ON  [dbo].[Extra_Info_Set_Data_sp] TO [public]
GO
