SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [dbo].[TMT_GetRepairOrder] @UNIT VARCHAR(12)
AS /**
*
* NAME:
* dbo.TMT_GetRepairOrder
*
* TYPE:
* StoredProcedure
*
* DESCRIPTION:
* Get repair order information from Transman
*
* RETURNS:
* Transman unit info.
* RESULT SETS:
* none.
*
* PARAMETERS:
* 	@unit - Transman unit id/
*
* REVISION HISTORY:
* 12/10/2005 - MRH – Created
* MB  05/07/2009 Expand String @SQL to 4000
* CHANGED 2/9/2014  MB Removed double set of SET @SQL =
**/

DECLARE @SHOPLINK INT
DECLARE @SQL NVARCHAR(4000)
,@TMTSERVER VARCHAR(80)
,@TMTDB VARCHAR(25)

SELECT @SHOPLINK = COUNT(1)
FROM   GENERALINFO
WHERE  GI_NAME = 'SHOPLINK'
AND GI_INTEGER1 > 0

IF @SHOPLINK = 0
RETURN                 -- SHOPLINK NOT INSTALLED

SET ANSI_NULLS ON;
SET ANSI_WARNINGS ON;

IF ISNULL(( SELECT GI_STRING1
FROM   GENERALINFO
WHERE  GI_NAME = 'SHOPLINK'
), '') <> ''
BEGIN
SELECT  @TMTSERVER = '[' + GI_STRING1 + ']'
FROM    GENERALINFO
WHERE   GI_NAME = 'SHOPLINK'
SELECT  @TMTDB = '[' + GI_STRING2 + ']'
FROM    GENERALINFO
WHERE   GI_NAME = 'SHOPLINK'
SET @SQL = 'SELECT [ORDERTYPE] ,[ORDERNUM] ,[SHOPID] ,[UNITID] ,[COMPANYUNIT]
,[STATUS] ,[RO_OPENED] ,[CLOSED] ,[RO_PRIORITY],[VENDOR]
,[VENDACCT] ,[TOTALAMT] ,[AMTPAID],[AMTUOM],[RO_REFORDERID]
,[REFINVOICE],[RO_MODIFIED],[RO_MODIFIEDBY] ,[CUSTID]
,[RO_TAXOVERRIDE],[BATCHID] ,[CREATEDON],[CREATEDBY]
,[OEMWARRANTY] ,[REFREPORDER] ,[CLOSEDBY],[CLOSEDON]
,[RO_COMPLTDATE] ,[SECTIONNUM] ,[BILLABLE]
,[SECSTATUS],[OPENED] ,[COMPLTDATE] ,[REPREASON]
,[COMPCDKEY],[COMPCODE] ,[COMPLAINT],[PRIORITY]
,[DELREASON],[WARSTATUS],[MODIFIED],[MODIFIEDBY]
,[VENDORID],[SECCOMMENT],[WARRTYPE],[INVOICENO]
,[TAXOVERRIDE],[EXTWARRANTY],[CAMPORDERID]
,[CAMPSECTION],[REFORDERID],[REFSECTION]' + ' FROM ' + @TMTSERVER + '.' + @TMTDB
+ '.dbo.VIEW_REPAIRORDER WHERE STATUS IN (''OPEN'', ''PENDING'') AND UNITID = ''' + @UNIT + ''''
EXEC SP_EXECUTESQL @SQL
END
ELSE
BEGIN
SELECT  @TMTDB = '[' + GI_STRING2 + ']'
FROM    GENERALINFO
WHERE   GI_NAME = 'SHOPLINK'
SET @SQL = 'SELECT [ORDERTYPE] ,[ORDERNUM] ,[SHOPID] ,[UNITID] ,[COMPANYUNIT]
,[STATUS] ,[RO_OPENED] ,[CLOSED] ,[RO_PRIORITY],[VENDOR]
,[VENDACCT] ,[TOTALAMT] ,[AMTPAID],[AMTUOM],[RO_REFORDERID]
,[REFINVOICE],[RO_MODIFIED],[RO_MODIFIEDBY] ,[CUSTID]
,[RO_TAXOVERRIDE],[BATCHID] ,[CREATEDON],[CREATEDBY]
,[OEMWARRANTY] ,[REFREPORDER] ,[CLOSEDBY],[CLOSEDON]
,[RO_COMPLTDATE] ,[SECTIONNUM] ,[BILLABLE]
,[SECSTATUS],[OPENED] ,[COMPLTDATE] ,[REPREASON]
,[COMPCDKEY],[COMPCODE] ,[COMPLAINT],[PRIORITY]
,[DELREASON],[WARSTATUS],[MODIFIED],[MODIFIEDBY]
,[VENDORID],[SECCOMMENT],[WARRTYPE],[INVOICENO]
,[TAXOVERRIDE],[EXTWARRANTY],[CAMPORDERID]
,[CAMPSECTION],[REFORDERID],[REFSECTION]' + 'FROM ' + @TMTDB + '.dbo.VIEW_REPAIRORDER WHERE IN (''OPEN'', ''PENDING'') AND UNITID = ''' + @UNIT + ''''
EXEC SP_EXECUTESQL @SQL

SET ANSI_NULLS OFF;
SET ANSI_WARNINGS OFF;
END

GO
GRANT EXECUTE ON  [dbo].[TMT_GetRepairOrder] TO [public]
GO
