SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

------------------------------
create proc [dbo].[TMT_GetRepReasons]
@CODE CHAR(12)
as

IF @CODE > ''
SELECT REASONCD.CODE, REASONCD.DESCRIP
FROM CMPONENT CMPONENT , REASONMAP REASONMAP ,
REASONCD REASONCD
WHERE
--(CMPONENT.CODEKEY = '031')
--AND
(CMPONENT.CODE = @CODE)
AND
( REASONMAP.CODEKEY = CMPONENT.CODEKEY )
AND
( REASONMAP.CODE = CMPONENT.CODE )
AND
( REASONCD.CODE = REASONMAP.REASONMAP)
ELSE
SELECT CODE, DESCRIP FROM VIEW_REASONCD ORDER BY DESCRIP

GO
GRANT EXECUTE ON  [dbo].[TMT_GetRepReasons] TO [public]
GO
