SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[TMWImaging_SetExpirations]
@IDTYPE CHAR(3), @ID VARCHAR(13), @CODE VARCHAR(6), @EXPDATE DATETIME, @UPDATEDBY VARCHAR(20)
AS

/*******************************************************************************************************************  
  Object Description:
  Imposes a document-based expiration.

  Revision History:
  Date         Name             Label/PTS    Description
  -----------  ---------------  ----------  ----------------------------------------
  08/07/2017   Chip Ciminero    WE-209653   Created
*******************************************************************************************************************/

UPDATE	expiration
SET		exp_completed = 'Y',
		exp_lastdate = CURRENT_TIMESTAMP,
		exp_updateon = CURRENT_TIMESTAMP,
		exp_updateby = @UPDATEDBY,
		exp_priority = 9
WHERE	exp_idtype = @IDTYPE AND exp_id = @ID AND exp_code = @CODE

INSERT INTO  expiration
(
  exp_idtype,
  exp_id,
  exp_code,
  exp_lastdate,
  exp_expirationdate,
  exp_completed,
  exp_routeto,
  exp_compldate,
  exp_updateby,
  exp_creatdate,
  exp_updateon,
  exp_description,
  exp_priority
)
VALUES
(
  @IDTYPE,
  @ID,
  @CODE,
  CURRENT_TIMESTAMP,
  CONVERT(VARCHAR(10), @EXPDATE, 101) + ' 23:59:59',
  'N',
  'UNKNOWN',  
  CONVERT(VARCHAR(10), @EXPDATE, 101) + ' 23:59:59',
  @UPDATEDBY,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP,
  'Generated by TMW Imaging Compliance Module on ' + CONVERT( VARCHAR(19), CURRENT_TIMESTAMP, 20),
  1
)
GO
GRANT EXECUTE ON  [dbo].[TMWImaging_SetExpirations] TO [public]
GO
