SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

create procedure [dbo].[d_branch_hierarchy] (@topbranch varchar(12), @type varchar(10))
AS


 WITH BranchHierarchy (brn_id, 
						brn_parent,  
						brn_name,   
					    brn_add1,   
						brn_add2,   
						brn_city,   
						brn_state_c,   
						brn_country_c,   
				        brn_tax_id,   
				        brn_primary_contact,   
				        brn_phone,   
						brn_arcurrency,   
         				brn_zip,   
				        brn_misc1,   
         				brn_misc2,   
				        brn_misc3,   
         				brn_misc4,   
         				brn_niwoid,   
         				brn_hourlyrate,   
         				brn_dailyguarenteedhours,   
         				brn_periodguarenteedhours,   
         				brn_comparisonflag,   
         				brn_zip2,   
         				brn_fax,   
         				brn_city2,   
         				brn_country2,   
         				brn_website,   
         				brn_billinginfo,   
         				brn_add1_2,   
         				brn_add2_2,   
         				brn_email,   
         				brn_payto,   
         				brn_actg_type,   
         				brn_legalentity,   
         				brn_stlcalc,   
         				brn_acctg_prefix,   
         				brn_leadbasis,   
         				brn_datebasis,   
         				brn_bookingterminal,   
         				brn_executingterminal,   
         				def_bookingterminal_tariff,   
         				max_bookingterminal_tariff,   
         				def_executingterminal_tariff,   
         				max_executingterminal_tariff,   
         				brn_retired,   
         				OrgLevel, 
						SortKey) AS
 (
  -- Create the anchor query. This establishes the starting
  -- point
  SELECT
		a.brn_id, 
		a.brn_parent,  
		a.brn_name,   
		a.brn_add1,   
		a.brn_add2,   
		a.brn_city,   
		a.brn_state_c,   
		a.brn_country_c,   
		a.brn_tax_id,   
		a.brn_primary_contact,   
		a.brn_phone,   
		a.brn_arcurrency,   
        a.brn_zip,   
		a.brn_misc1,   
        a.brn_misc2,   
		a.brn_misc3,   
        a.brn_misc4,   
        a.brn_niwoid,   
        a.brn_hourlyrate,   
        a.brn_dailyguarenteedhours,   
        a.brn_periodguarenteedhours,   
        a.brn_comparisonflag,   
        a.brn_zip2,   
        a.brn_fax,   
		a.brn_city2,   
        a.brn_country2,   
		a.brn_website,   
        a.brn_billinginfo,   
        a.brn_add1_2,   
        a.brn_add2_2,   
        a.brn_email,   
        a.brn_payto,   
        a.brn_actg_type,   
        a.brn_legalentity,   
        a.brn_stlcalc,   
        a.brn_acctg_prefix,   
        a.brn_leadbasis,   
        a.brn_datebasis,   
        a.brn_bookingterminal,   
        a.brn_executingterminal,   
        a.def_bookingterminal_tariff,   
        a.max_bookingterminal_tariff,   
        a.def_executingterminal_tariff,   
        a.max_executingterminal_tariff,   
        a.brn_retired, 0, CAST (a.brn_id AS VARBINARY(900))
   FROM dbo.branch a
   WHERE a.brn_id = @topbranch AND
			(brn_bookingterminal = 'Y' AND @type = 'BOOKING' or @type = 'BOTH') AND
			(brn_executingterminal = 'Y' and @type = 'EXECUTING' or @type = 'BOTH') AND
			a.brn_id <> 'UNKNOWN'
  UNION ALL
  -- Create the recursive query. This query will be executed
  -- until it returns no more rows
  SELECT
    		a.brn_id, 
		a.brn_parent,  
		a.brn_name,   
		a.brn_add1,   
		a.brn_add2,   
		a.brn_city,   
		a.brn_state_c,   
		a.brn_country_c,   
		a.brn_tax_id,   
		a.brn_primary_contact,   
		a.brn_phone,   
		a.brn_arcurrency,   
        a.brn_zip,   
		a.brn_misc1,   
        a.brn_misc2,   
		a.brn_misc3,   
        a.brn_misc4,   
        a.brn_niwoid,   
        a.brn_hourlyrate,   
        a.brn_dailyguarenteedhours,   
        a.brn_periodguarenteedhours,   
        a.brn_comparisonflag,   
        a.brn_zip2,   
        a.brn_fax,   
		a.brn_city2,   
        a.brn_country2,   
		a.brn_website,   
        a.brn_billinginfo,   
        a.brn_add1_2,   
        a.brn_add2_2,   
        a.brn_email,   
        a.brn_payto,   
        a.brn_actg_type,   
        a.brn_legalentity,   
        a.brn_stlcalc,   
        a.brn_acctg_prefix,   
        a.brn_leadbasis,   
        a.brn_datebasis,   
        a.brn_bookingterminal,   
        a.brn_executingterminal,   
        a.def_bookingterminal_tariff,   
        a.max_bookingterminal_tariff,   
        a.def_executingterminal_tariff,   
        a.max_executingterminal_tariff,   
        a.brn_retired, 
		b.OrgLevel+1,
		CAST (b.SortKey + CAST (a.brn_id AS BINARY(4)) AS VARBINARY(900))
   FROM dbo.branch a
     INNER JOIN BranchHierarchy b ON a.brn_parent = b.brn_id
		WHERE a.brn_id <> 'UNKNOWN'
   --WHERE b.OrgLevel < 1
 )

SELECT					brn_id, 
						brn_parent,  
						brn_name,   
					    brn_add1,   
						brn_add2,   
						brn_city,   
						brn_state_c,   
						brn_country_c,   
				        brn_tax_id,   
				        brn_primary_contact,   
				        brn_phone,   
						brn_arcurrency,   
         				brn_zip,   
				        brn_misc1,   
         				brn_misc2,   
				        brn_misc3,   
         				brn_misc4,   
         				brn_niwoid,   
         				brn_hourlyrate,   
         				brn_dailyguarenteedhours,   
         				brn_periodguarenteedhours,   
         				brn_comparisonflag,   
         				brn_zip2,   
         				brn_fax,   
         				brn_city2,   
         				brn_country2,   
         				brn_website,   
         				brn_billinginfo,   
         				brn_add1_2,   
         				brn_add2_2,   
         				brn_email,   
         				brn_payto,   
         				brn_actg_type,   
         				brn_legalentity,   
         				brn_stlcalc,   
         				brn_acctg_prefix,   
         				brn_leadbasis,   
         				brn_datebasis,   
         				brn_bookingterminal,   
         				brn_executingterminal,   
         				def_bookingterminal_tariff,   
         				max_bookingterminal_tariff,   
         				def_executingterminal_tariff,   
         				max_executingterminal_tariff,   
         				brn_retired,   
         				OrgLevel
 FROM BranchHierarchy orglevel
GO
GRANT EXECUTE ON  [dbo].[d_branch_hierarchy] TO [public]
GO
