SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROC [dbo].[d_invoice_printqueue_dedicated_sp] (@dbh_id int)
AS

DECLARE @int0  int, @varchar6 varchar(6), @varchar8 varchar (8), @money money, 
	@varchar254 varchar(254), @varchar30 varchar(30), @char3 char(3), @charn char,
	@chary char, @varchar20 varchar(20), @char1 char(1), @copies smallint
SELECT @int0 = 0, @money = 0.00, @varchar8 = '', @varchar30 = '', @varchar254 = '',
     @varchar6 = '', @char3 = '', @charn = 'N', @chary = 'Y',@varchar20 = '', @copies = 0
 
CREATE TABLE #invview (	
	mov_number int NULL,
	ivh_invoicenumber varchar(12) NULL,
	ivh_invoicestatus varchar(6) NULL,
	ivh_billto varchar(8) NULL,
	billto_name varchar(100) NULL,
	ivh_shipper varchar(8) NULL,
	shipper_name varchar(100) NULL,
	ivh_consignee varchar(8) NULL,
	consignee_name varchar(100) NULL,
	ivh_shipdate datetime NULL,
 	ivh_deliverydate datetime NULL,
 	ivh_revtype1 varchar(6) NULL,
 	ivh_revtype2 varchar(6) NULL,
 	ivh_revtype3 varchar(6) NULL,
 	ivh_revtype4 varchar(6) NULL,
 	ivh_totalweight float NULL,
 	ivh_totalpieces float NULL,
 	ivh_totalmiles float NULL,
 	ivh_totalvolume float NULL,
 	ivh_printdate datetime NULL,
 	ivh_billdate datetime NULL,
 	ivh_lastprintdate datetime NULL,
 	ord_hdrnumber int NULL,
 	ivh_remark varchar(254) NULL,
 	ivh_edi_flag char(30) NULL,
 	ivh_totalcharge money NULL,
	RevType1 char(8) NULL,
 	RevType2 char(8) NULL,
 	Revtype3 char(8) NULL,
 	RevType4 char(8) NULL,
 	ivh_hdrnumber int NULL,
 	ivh_order_by varchar(8) NULL,
 	ivh_user_id1 char(20) NULL,
 	ord_number char(12) NULL,
	ivh_terms char(3) NULL,
	ivh_trailer varchar(8) NULL,
	ivh_tractor varchar(8) NULL,
	commodities int NULL,
	validcommodities int NULL,
	accessorials int NULL,
	validaccessorials int NULL,
	trltype3 varchar(6) NULL,
	cmp_subcompany varchar(6) NULL,
	totallinehaul money NULL,
	negativecharges int NULL,
	edi_210_flag int NULL,
	ismasterbill char(1) NULL,
	trltype3name char(8) NULL, 
	cmp_mastercompany varchar(8) NULL,
	refnumber varchar(30) NULL,
	cmp_invoiceto char(3) NULL,
	cmp_invprintto char(1) NULL,
	cmp_invformat int NULL,
	cmp_transfertype varchar(6) NULL,
	ivh_mbstatus varchar(6) NULL,
	trp_linehaulmax money NULL,
	trp_totchargemax money NULL,
	cmp_invcopies smallint NULL,
	cmp_invoicetype varchar(6) NULL,
	ivh_definition varchar(6) NULL,
	ivh_applyto varchar(12) NULL,
	cmp_image_routing1	varchar(254) NULL,
	cmp_image_routing2	varchar(254) NULL,
	cmp_image_routing3	varchar(254) NULL,
	ivh_company	varchar(6) null,
	ivh_showshipper varchar(8) NULL,  	--PTS 39333
	ivh_showcons varchar(8) NULL ,  	--PTS 39333
	car_key int null,   --40753,
	inv_accessorials decimal (13,4) NULL,
	inv_fuel decimal (13,4) NULL ,
	inv_linehaul decimal (13,4) NULL,
	dbh_id int NULL
	)

INSERT INTO #invview
SELECT	0 mov_number,    
		'Dedicated' ivh_invoicenumber,   
		min(invoiceheader.ivh_mbstatus) ivh_invoicestatus,    
		min(invoiceheader.ivh_billto) ivh_billto,    
		@varchar30 billto_name,    
		'UNKNOWN' ivh_shipper,    
		@varchar30 shipper_name,    
		'UNKNOWN' ivh_consignee,    
		@varchar30 consignee_name,    
		'19500101 00:00' ivh_shipdate,    
		'20491231 23:59' ivh_deliverydate,    
		ivh_revtype1 = (select ivh_revtype1 from invoiceheader where dbh_id = @dbh_id and ivh_definition = 'DEDBIL'),     
		ivh_revtype2 = (select ivh_revtype2 from invoiceheader where dbh_id = @dbh_id and ivh_definition = 'DEDBIL'),
		ivh_revtype3 = (select ivh_revtype3 from invoiceheader where dbh_id = @dbh_id and ivh_definition = 'DEDBIL'),
		ivh_revtype4 = (select ivh_revtype4 from invoiceheader where dbh_id = @dbh_id and ivh_definition = 'DEDBIL'),
		0 ivh_totalweight,    
		0 ivh_totalpieces,    
		0 ivh_totalmiles,    
		0 ivh_totalvolume,    
		'19500101 00:00'  ivh_printdate,      
		'20491231 23:59' ivh_billdate,    
		'19500101 00:00' ivh_lastprintdate,    
		0 ord_hdrnumber,       
		'' ivh_remark ,    
		'' ivh_edi_flag,    
		sum(invoiceheader.ivh_totalcharge) ivh_totalcharge,    
		'RevType1' revtype1,    
		'RevType2' Revtype2,    
		'RevType3' revtype3,    
		'RevType4' revtype4,    
		@int0 ivh_hdrnumber,    
		'UNKNOWN' ivh_order_by,    
		'N/A' ivh_user_id1,    
		'' ord_number ,     
		@char3 ivh_terms,    
		@varchar8 ivh_trailer,    
		'UNKNOWN' ivh_tractor,    
		@int0 commodities,    
		@int0 validcommodities,    
		@int0 accessorials,    
		@int0 validaccessorials,    
		@varchar6 trltype3,      
		MIN(IsNull(bcmp.cmp_subcompany ,'UNK')),    
		@money totallinehaul,    
		@int0 negativecharges,    
		@int0 edi_210_flag,    
		'Y' ismasterbill,    
		'TrlType3' trltype3name,    
		@varchar8 cmp_mastercompany,    
		@varchar30 refnumber,    
		@char3 cmp_invoiceto,    
		@char1 cmp_invprintto,    
		@int0  cmp_invformat,    
		@varchar6 cmp_transfertype,    
		'RTP'  ivh_Mbstatus,    
		@money trp_linehaulmax,    
		@money trp_totchargemax,    
		max(bcmp.cmp_invcopies) cmp_invcopies,    
		'' cmp_invoicetype,    
		'' ivh_definition,    
		'' ivh_applyto,   
		@varchar254 cmp_image_routing1,
		@varchar254 cmp_image_routing2,
		@varchar254 cmp_image_routing3  ,
		'UNK' ivh_company,
		'' as ivh_showshipper,
		'' as ivh_showcons,
		0 as car_key,
		0.00 as inv_accessorials,
		0.00 as inv_fuel,
		0.00 as inv_linehaul, 
		Max (invoiceheader.dbh_id)
	FROM invoiceheader, company bcmp, company scmp, company ccmp 
	WHERE ( @dbh_id = invoiceheader.dbh_id ) 
	AND     ( bcmp.cmp_id = invoiceheader.ivh_billto)
	AND     ( scmp.cmp_id = invoiceheader.ivh_shipper)
	AND	( ccmp.cmp_id = invoiceheader.ivh_consignee)
	GROUP BY invoiceheader.dbh_id 


SELECT * from #invview

GO
GRANT EXECUTE ON  [dbo].[d_invoice_printqueue_dedicated_sp] TO [public]
GO
