SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[Extra_Info_Get_Data_sp](@Extra_ID INTEGER, @Tab_ID INTEGER, @TableKey VARCHAR(50), @Row INTEGER, @Col_ID INTEGER) AS
BEGIN
/* Returns a list of tabs and columns defined under a particular header
*/
SELECT	EXTRA_INFO_DATA.COL_DATA
FROM 	EXTRA_INFO_DATA
WHERE	EXTRA_INFO_DATA.EXTRA_ID = @Extra_ID
AND EXTRA_INFO_DATA.TAB_ID = @Tab_ID
AND EXTRA_INFO_DATA.TABLE_KEY = @TableKey
AND EXTRA_INFO_DATA.COL_ROW = @Row
AND EXTRA_INFO_DATA.COL_ID = @Col_ID
END
GO
GRANT EXECUTE ON  [dbo].[Extra_Info_Get_Data_sp] TO [public]
GO
