SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[Extra_Info_Get_Column_List_sp](@Extra_ID INTEGER, @Tab_ID INTEGER) AS
BEGIN
/* Returns a list of tabs and columns defined under a particular header
*/
SELECT	EXTRA_INFO_COLS.COL_ID,
EXTRA_INFO_COLS.COL_NAME,
EXTRA_INFO_COLS.DISPLAY_ORDER,
EXTRA_INFO_COLS.EDITABLE,
EXTRA_INFO_COLS.MASK,
EXTRA_INFO_COLS.MASK_TYPE,
EXTRA_INFO_COLS.LABEL,
EXTRA_INFO_COLS.FORMAT
FROM 	EXTRA_INFO_COLS
WHERE	EXTRA_INFO_COLS.EXTRA_ID = @Extra_ID
AND	EXTRA_INFO_COLS.TAB_ID = @Tab_ID
ORDER BY EXTRA_INFO_COLS.COL_NAME
END
GO
GRANT EXECUTE ON  [dbo].[Extra_Info_Get_Column_List_sp] TO [public]
GO
