SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS OFF
GO


create proc [dbo].[d_inv_edit_hdr_stl_sp] ( @pl_ordhdrnumber             int	)
as
/**
 * 
 * NAME:
 * dbo.d_inv_edit_hdr_stl_sp 
 *
 * TYPE:
 * Stored Procedure
 *
 * DESCRIPTION:
 * 
 *
 * RETURNS:
 * 
 * 
 * RESULT SETS: 
 * 
 *
 * PARAMETERS:
 * 001 - 
 *       
 * 002 - 
 *
 * REFERENCES: 
 *              
 * Calls001:    
 * Calls002:    
 *
 * CalledBy001:  
 * CalledBy002:  
 *
 * 
 * REVISION HISTORY:
 * Modified to not retrieve data used for UI only if queue processing. 
 * dpete pts6691 change totalweight,vol,pieces,miles to floats on temp table.
 * 08/08/2005.01 PTS29148 - jguo - replace double quotes around literals, table and column names.
 * 04/25/2008.01 PTS41922 - SLM  - Add logic to use GI setting for InvoiceA(linehaul) or Rebill if creditmemo exists
 *                                 In the case of no Rebill InvoiceA(linehaul) will be used.
 * 3/3/09 PTS 44417 DPETE for invoicing by MOV or CON the invoice for the passed order may be under anotehr number
 * LOR	PTS# 47552	added furthestpointconsignee
 *
 **/

-- BEGIN PTS 41922
Declare @UseMostRecentLineHaulinvoice char(1), @rebillcount integer
SELECT @UseMostRecentLineHaulinvoice = Isnull(gi_string1,'N') from generalinfo where upper(gi_name) = 'UseMostRecentLineHaulinvoice'
SELECT @rebillcount = count(*) from invoiceheader where ord_hdrnumber = @pl_ordhdrnumber and ivh_definition ='RBIL'
--END PTS 41922


declare @calcmaxstat		varchar(6), 
	@dummydate              datetime, 
	@remarks                varchar(254), 
	@fill6                  varchar(6), 
	@fill3                  varchar(3), 
	@fill13                 varchar(13),    
	@fill8                  varchar(8),     
	@fill20                 varchar(20), 
	@edi                    varchar(30), 
	@invnum                 varchar(12), 
	@comments_count         int,
	@notes_count            int,
	@loadreq_count          int,
	@ref_count              int,
	@pwork_req_count        int,
	@pwork_rec_count        int,
	@lgh_count		int, 
	@vchar6			varchar(6),
	@ish_status		char(3),
	@min_date		int,
	@billto_altid		varchar(8),
	@ivh_revenue_date 	datetime,
	@ivh_batch_id		varchar(10),
	@first_invoice_number	varchar(12),
	@first_origin		varchar(8),
	@first_dest		varchar(8),
	@first_billto		varchar(8),
	@mov_number		int,
	@ord_hdrnumber		int,
	@invoicecount           int,
	@ivhhdrnumber		int,
	@varchar12			varchar(12)

	create table #temp (
			ivh_invoicenumber char(12) null, 
			ivh_billto char(8) null,
			ivh_terms char(3) null, 
			ivh_totalcharge money null,    
			ivh_shipper char(8) null, 
			ivh_consignee char(8) null, 
			ivh_originpoint char(8) null,    
			ivh_destpoint char(8) null, 
			ivh_invoicestatus char(6) null, 
			ivh_origincity int null,     
			ivh_destcity int null, 
			ivh_originstate varchar(6) null, 
			ivh_deststate varchar(6) null,      
			ivh_originregion1 char(6) null, 
			ivh_destregion1 char(6) null, 
			ivh_supplier char(8) null,       
			ivh_shipdate datetime null, 
			ivh_deliverydate datetime null, 
			ivh_revtype1 char(6) null,       
			ivh_revtype2 char(6) null, 
			ivh_revtype3 char(6) null, 
			ivh_revtype4 char(6) null, 
			ivh_totalweight float(15)  null, 
			ivh_totalpieces float(15) null, 
			ivh_totalmiles float(15) null,     
			ivh_currency char(6) null,
			ivh_currencydate datetime null, 
			ivh_totalvolume float(15) null,    
			ivh_taxamount1 money null, 
			ivh_taxamount2 money null,       
			ivh_taxamount3 money null, 
			ivh_taxamount4 money null,
			ivh_transtype char(6) null,
			ivh_creditmemo char(1) null,     
			ivh_applyto char(12) null, 
			ivh_printdate datetime null, 
			ivh_billdate datetime null, 
			ivh_lastprintdate datetime null,   
			ivh_hdrnumber int null, 
			ord_hdrnumber int null, 
			ivh_originregion2 char(6) null,  
			ivh_originregion3 char(6) null, 
			ivh_originregion4 char(6) null, 
			ivh_destregion2 char(6) null,    
			ivh_destregion3 char(6) null, 
			ivh_destregion4 char(6) null, 
			ivh_mbnumber int null, 
			ivh_remark char(254) null, 
			ivh_driver char(8) null, 
			ivh_driver2 char(8) null, 
			ivh_tractor char(8) null,
			ivh_trailer char(13) null, 
			mov_number int null, 
			ivh_edi_flag char(30) null,
			revtype1 char(8) null, 
			revtype2 char(8) null, 
			revtype3 char(8) null, 
			revtype4 char(8) null, 
			ivh_freight_miles int null, 
			ivh_priority char(6),
			ivh_low_temp int null,
			ivh_high_temp int null,
			events_count int null,
			comments_count int null,
			notes_count int null,
			loadreq_count int null,
			ref_count int null,
			paperwork_required int null,
			paperwork_received int null,
			ivh_order_by char(8) null,
			tar_tarriffnumber char(12) null, 
			tar_number int null, 
			ivh_user_id1 char(20) null, 
			ivh_user_id2 char(20) null, 
			ivh_ref_number char(30) null,
			invoiceheader_ivh_bookyear int null,
			invoiceheader_ivh_bookmonth int null,
			tar_tariffitem char(12) null,
			ivh_mbstatus char(6) null,
			calc_maxstatus char(6) null,
			ord_number char(12) null,
			ivh_quantity float(15) null,
			ivh_rate money  null, 
			ivh_charge money null,
			cht_itemcode char(6) null,
			ivh_splitbill_flag char(1) null,
			dummy_ordstatus char(6) null,
			ivh_company char(8) null,
			ivh_carrier char(8) null,
			ivh_archarge money null,
			ivh_arcurrency char(6) null,
			ivh_loadtime int null,
			ivh_unloadtime int null,
			ivh_drivetime int null,
			ivh_totaltime int null,
			ivh_rateby char(1) null,
			ivh_unit char(6) null,
			ivh_rateunit char(6) null,
			lgh_count int NULL,
			ord_remark char(254) null,
			billto_altid	varchar(8) null,
			ivh_revenue_date datetime null,
			ivh_batch_id	varchar(10) null,
			mailto_flag char(1) null,
			ivh_stopoffs smallint null,
			ivh_quantity_type smallint null,
			ivh_charge_type smallint null,
			ivh_originzipcode varchar(10) null, 
			ivh_destzipcode varchar(10) null,
            inv_revenue_pay_fix int null,
            inv_revenue_pay money null,
			ord_fromorder varchar(12) null,
			furthestpointconsignee_flag  CHAR(1) NULL,
			furthestpoint_city int null,
			furthestpoint_state  varchar(6) null)	

-- if invoicing in aggregate get the ord_hdrnumber on the invoice for this order 
   If exists (select 1 from invoicemaster where ord_hdrnumber = @pl_ordhdrnumber)
   select @pl_ordhdrnumber = ivm_invoiceordhdrnumber 
     from invoicemaster
    where invoicemaster.ord_hdrnumber = @pl_ordhdrnumber
	
	
	IF exists (select * from invoiceheader where ord_hdrnumber = @pl_ordhdrnumber and ivh_creditmemo='Y')
	--PTS 41922, There is a creditmemo		
	IF (@rebillcount > 0 and @UseMostRecentLineHaulinvoice = 'Y') or (@rebillcount = 0)
	BEGIN
		--41922 Get Max invoice where ivh_charge > 0 and ivh_definition ='LH' in case of split
		INSERT into #temp
			SELECT i.ivh_invoicenumber, 
				i.ivh_billto, 
				i.ivh_terms, 
				i.ivh_totalcharge, 
				i.ivh_shipper, 
				i.ivh_consignee,    
				i.ivh_originpoint, 
				i.ivh_destpoint, 
				i.ivh_invoicestatus,        
				i.ivh_origincity, 
				i.ivh_destcity, 
				i.ivh_originstate,  
				i.ivh_deststate, 
				i.ivh_originregion1, 
				i.ivh_destregion1,  
				i.ivh_supplier, 
				i.ivh_shipdate, 
				i.ivh_deliverydate, 
				i.ivh_revtype1, 
				i.ivh_revtype2, 
				i.ivh_revtype3, 
				i.ivh_revtype4, 
				i.ivh_totalweight, 
				i.ivh_totalpieces,  
				i.ivh_totalmiles, 
				i.ivh_currency, 
				i.ivh_currencydate,         
				i.ivh_totalvolume, 
				i.ivh_taxamount1, 
				i.ivh_taxamount2,   
				i.ivh_taxamount3, 
				i.ivh_taxamount4, 
				i.ivh_transtype,    
				i.ivh_creditmemo, 
				i.ivh_applyto,      
				i.ivh_printdate, 
				i.ivh_billdate, 
				i.ivh_lastprintdate,        
				i.ivh_hdrnumber, 
				i.ord_hdrnumber, 
				i.ivh_originregion2,        
				i.ivh_originregion3, 
				i.ivh_originregion4, 
				i.ivh_destregion2,  
				i.ivh_destregion3, 
				i.ivh_destregion4, 
				i.ivh_mbnumber, 
				i.ivh_remark,
				i.ivh_driver,       
				i.ivh_driver2, 
				i.ivh_tractor, 
				i.ivh_trailer,      
				i.mov_number ,
				i.ivh_edi_flag, 
				'RevType1', 
				'RevType2', 
				'RevType3',    
				'RevType4', 
				i.ivh_freight_miles ,
				i.ivh_priority ,    
				i.ivh_low_temp, 
				i.ivh_high_temp , 
				0,
				0,
				0,
				0,
				0,
				0,
				0,
				i.ivh_order_by, 
				i.tar_tarriffnumber,        
				i.tar_number , 
				i.ivh_user_id1, 
				i.ivh_user_id2 ,    
				i.ivh_ref_number, 
				i.ivh_bookyear, 
				i.ivh_bookmonth, 
				i.tar_tariffitem, 
				i.ivh_mbstatus, 
				@calcmaxstat, 
				i.ord_number, 
				i.ivh_quantity, 
				i.ivh_rate, 
				i.ivh_charge, 
				i.cht_itemcode, 
				i.ivh_splitbill_flag, 
				@calcmaxstat,
				i.ivh_company,
				i.ivh_carrier,
				i.ivh_archarge,
				i.ivh_arcurrency,
				i.ivh_loadtime,
				i.ivh_unloadtime,
				i.ivh_drivetime,
				i.ivh_totaltime,
				i.ivh_rateby,
				@vchar6,
				@vchar6,
				0,
				@remarks,
				@billto_altid,
				i.ivh_revenue_date,
				i.ivh_batch_id,
				'N',
				i.ivh_stopoffs,
				ISNULL(ivh_quantity_type,0),
				ISNULL(ivh_charge_type,0), 
				ivh_originzipcode, 
				ivh_destzipcode,
				inv_revenue_pay_fix,
				inv_revenue_pay,
				@varchar12,
				'N',
				0,
				''
			FROM    invoiceheader i
			WHERE 	i.ivh_hdrnumber in (select max(ivh_hdrnumber) from invoiceheader where 
						   ord_hdrnumber = @pl_ordhdrnumber and 
						   ivh_charge > 0 and ivh_definition = 'LH')
	END
	ELSE
	BEGIN
	INSERT into #temp
	SELECT i.ivh_invoicenumber, 
		i.ivh_billto, 
		i.ivh_terms, 
		i.ivh_totalcharge, 
		i.ivh_shipper, 
		i.ivh_consignee,    
		i.ivh_originpoint, 
		i.ivh_destpoint, 
		i.ivh_invoicestatus,        
		i.ivh_origincity, 
		i.ivh_destcity, 
		i.ivh_originstate,  
		i.ivh_deststate, 
		i.ivh_originregion1, 
		i.ivh_destregion1,  
		i.ivh_supplier, 
		i.ivh_shipdate, 
		i.ivh_deliverydate, 
		i.ivh_revtype1, 
		i.ivh_revtype2, 
		i.ivh_revtype3, 
		i.ivh_revtype4, 
		i.ivh_totalweight, 
		i.ivh_totalpieces,  
		i.ivh_totalmiles, 
		i.ivh_currency, 
		i.ivh_currencydate,         
		i.ivh_totalvolume, 
		i.ivh_taxamount1, 
		i.ivh_taxamount2,   
		i.ivh_taxamount3, 
		i.ivh_taxamount4, 
		i.ivh_transtype,    
		i.ivh_creditmemo, 
		i.ivh_applyto,      
		i.ivh_printdate, 
		i.ivh_billdate, 
		i.ivh_lastprintdate,        
		i.ivh_hdrnumber, 
		i.ord_hdrnumber, 
		i.ivh_originregion2,        
		i.ivh_originregion3, 
		i.ivh_originregion4, 
		i.ivh_destregion2,  
		i.ivh_destregion3, 
		i.ivh_destregion4, 
		i.ivh_mbnumber, 
		i.ivh_remark,
		i.ivh_driver,       
		i.ivh_driver2, 
		i.ivh_tractor, 
		i.ivh_trailer,      
		i.mov_number ,
		i.ivh_edi_flag, 
		'RevType1', 
		'RevType2', 
		'RevType3',    
		'RevType4', 
		i.ivh_freight_miles ,
		i.ivh_priority ,    
		i.ivh_low_temp, 
		i.ivh_high_temp , 
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		i.ivh_order_by, 
		i.tar_tarriffnumber,        
		i.tar_number , 
		i.ivh_user_id1, 
		i.ivh_user_id2 ,    
		i.ivh_ref_number, 
		i.ivh_bookyear, 
		i.ivh_bookmonth, 
		i.tar_tariffitem, 
		i.ivh_mbstatus, 
		@calcmaxstat, 
		i.ord_number, 
		i.ivh_quantity, 
		i.ivh_rate, 
		i.ivh_charge, 
		i.cht_itemcode, 
		i.ivh_splitbill_flag, 
		@calcmaxstat,
		i.ivh_company,
		i.ivh_carrier,
		i.ivh_archarge,
		i.ivh_arcurrency,
		i.ivh_loadtime,
		i.ivh_unloadtime,
		i.ivh_drivetime,
		i.ivh_totaltime,
		i.ivh_rateby,
		@vchar6,
		@vchar6,
		0,
		@remarks,
		@billto_altid,
		i.ivh_revenue_date,
		i.ivh_batch_id,
		'N',
		i.ivh_stopoffs,
		ISNULL(ivh_quantity_type,0),
		ISNULL(ivh_charge_type,0), 
        ivh_originzipcode, 
        ivh_destzipcode,
        inv_revenue_pay_fix,
        inv_revenue_pay,
		@varchar12,
		'N',
		0,
		''
	FROM    invoiceheader i
	WHERE 	i.ivh_hdrnumber in (select min(ivh_hdrnumber) from invoiceheader where 
				   ord_hdrnumber = @pl_ordhdrnumber and 
				   ivh_hdrnumber > (select max(ivh_hdrnumber) from invoiceheader where
						    ord_hdrnumber = @pl_ordhdrnumber and ivh_creditmemo = 'Y'))	
	END
	ELSE
	BEGIN
	-- Get the data into the temp table
	INSERT into #temp
	SELECT i.ivh_invoicenumber, 
		i.ivh_billto, 
		i.ivh_terms, 
		i.ivh_totalcharge, 
		i.ivh_shipper, 
		i.ivh_consignee,    
		i.ivh_originpoint, 
		i.ivh_destpoint, 
		i.ivh_invoicestatus,        
		i.ivh_origincity, 
		i.ivh_destcity, 
		i.ivh_originstate,  
		i.ivh_deststate, 
		i.ivh_originregion1, 
		i.ivh_destregion1,  
		i.ivh_supplier, 
		i.ivh_shipdate, 
		i.ivh_deliverydate, 
		i.ivh_revtype1, 
		i.ivh_revtype2, 
		i.ivh_revtype3, 
		i.ivh_revtype4, 
		i.ivh_totalweight, 
		i.ivh_totalpieces,  
		i.ivh_totalmiles, 
		i.ivh_currency, 
		i.ivh_currencydate,         
		i.ivh_totalvolume, 
		i.ivh_taxamount1, 
		i.ivh_taxamount2,   
		i.ivh_taxamount3, 
		i.ivh_taxamount4, 
		i.ivh_transtype,    
		i.ivh_creditmemo, 
		i.ivh_applyto,      
		i.ivh_printdate, 
		i.ivh_billdate, 
		i.ivh_lastprintdate,        
		i.ivh_hdrnumber, 
		i.ord_hdrnumber, 
		i.ivh_originregion2,        
		i.ivh_originregion3, 
		i.ivh_originregion4, 
		i.ivh_destregion2,  
		i.ivh_destregion3, 
		i.ivh_destregion4, 
		i.ivh_mbnumber, 
		i.ivh_remark,
		i.ivh_driver,       
		i.ivh_driver2, 
		i.ivh_tractor, 
		i.ivh_trailer,      
		i.mov_number ,
		i.ivh_edi_flag, 
		'RevType1', 
		'RevType2', 
		'RevType3',    
		'RevType4', 
		i.ivh_freight_miles ,
		i.ivh_priority ,    
		i.ivh_low_temp, 
		i.ivh_high_temp , 
		0,
		0,
		0,
		0,
		0,
		0,
		0,
		i.ivh_order_by, 
		i.tar_tarriffnumber,        
		i.tar_number , 
		i.ivh_user_id1, 
		i.ivh_user_id2 ,    
		i.ivh_ref_number, 
		i.ivh_bookyear, 
		i.ivh_bookmonth, 
		i.tar_tariffitem, 
		i.ivh_mbstatus, 
		@calcmaxstat, 
		i.ord_number, 
		i.ivh_quantity, 
		i.ivh_rate, 
		i.ivh_charge, 
		i.cht_itemcode, 
		i.ivh_splitbill_flag, 
		@calcmaxstat,
		i.ivh_company,
		i.ivh_carrier,
		i.ivh_archarge,
		i.ivh_arcurrency,
		i.ivh_loadtime,
		i.ivh_unloadtime,
		i.ivh_drivetime,
		i.ivh_totaltime,
		i.ivh_rateby,
		@vchar6,
		@vchar6,
		0,
		@remarks,
		@billto_altid,
		i.ivh_revenue_date,
		i.ivh_batch_id,
		'N',
		i.ivh_stopoffs,
		ISNULL(ivh_quantity_type,0),
		ISNULL(ivh_charge_type,0), 
        ivh_originzipcode, 
        ivh_destzipcode,
        inv_revenue_pay_fix,
        inv_revenue_pay,
		@varchar12,
		'N',
		0,
		''
	FROM 	invoiceheader i
	WHERE 	i.ivh_hdrnumber in (select min(ivh_hdrnumber) from invoiceheader where ord_hdrnumber = @pl_ordhdrnumber)    
	END

--	LOR	PTS# 35521
Update #temp 
Set ord_fromorder = (Select IsNull(o.ord_fromorder, '') 
					FROM orderheader o
					WHERE #temp.ord_hdrnumber = o.ord_hdrnumber) 
--	LOR

--PTS39095 MBR 02/23/09
UPDATE #temp
   SET #temp.ivh_consignee = invoiceheader.ivh_furthestpointconsignee,
		#temp.furthestpointconsignee_flag = 'Y'
  FROM invoiceheader JOIN #temp ON invoiceheader.ivh_hdrnumber = #temp.ivh_hdrnumber
                     JOIN company ON invoiceheader.ivh_billto = company.cmp_id AND
                                     company.cmp_rbd_highrateoption = 'MSNF'
 WHERE (invoiceheader.ivh_furthestpointconsignee <> 'UNKNOWN' AND
       invoiceheader.ivh_furthestpointconsignee IS NOT NULL)

--	LOR	PTS# 47552
UPDATE #temp
SET furthestpoint_city = ct.cty_code,
	furthestpoint_state = ct.cty_state
FROM  company co, city ct
WHERE #temp.ivh_consignee = co.cmp_id
	  AND co.cmp_city = ct.cty_code 
	and #temp.furthestpointconsignee_flag = 'Y'
--	LOR

		SELECT	ivh_invoicenumber, 
				ivh_billto,
				ivh_terms, 
				ivh_totalcharge,    
				ivh_shipper, 
				ivh_consignee, 
				ivh_originpoint,    
				ivh_destpoint, 
				ivh_invoicestatus, 
				ivh_origincity,     
				ivh_destcity, 
				ivh_originstate, 
				ivh_deststate,      
				ivh_originregion1, 
				ivh_destregion1, 
				ivh_supplier,       
				ivh_shipdate, 
				ivh_deliverydate, 
				ivh_revtype1,       
				ivh_revtype2, 
				ivh_revtype3, 
				ivh_revtype4, 
				ivh_totalweight, 
				ivh_totalpieces, 
				ivh_totalmiles,     
				ivh_currency,
				ivh_currencydate, 
				ivh_totalvolume,    
				ivh_taxamount1, 
				ivh_taxamount2,       
				ivh_taxamount3, 
				ivh_taxamount4,
				ivh_transtype,
				ivh_creditmemo,     
				ivh_applyto, 
				ivh_printdate, 
				ivh_billdate, 
				ivh_lastprintdate,   
				ivh_hdrnumber, 
				ord_hdrnumber, 
				ivh_originregion2,  
				ivh_originregion3, 
				ivh_originregion4, 
				ivh_destregion2,    
				ivh_destregion3, 
				ivh_destregion4, 
				ivh_mbnumber, 
				ivh_remark, 
				ivh_driver,
				ivh_driver2, 
				ivh_tractor,
				ivh_trailer, 
				mov_number, 
				ivh_edi_flag, 
				revtype1, 
				revtype2, 
				revtype3, 
				revtype4, 
				ivh_freight_miles, 
				ivh_priority,
				ivh_low_temp, 
				ivh_high_temp,
				events_count,
				comments_count,
				notes_count,
				loadreq_count,
				ref_count,
				paperwork_required,
				paperwork_received,
				ivh_order_by, 
				tar_tarriffnumber, 
				tar_number, 
				ivh_user_id1, 
				ivh_user_id2, 
				ivh_ref_number, 
				invoiceheader_ivh_bookyear, 
				invoiceheader_ivh_bookmonth, 
				tar_tariffitem, 
				ivh_mbstatus, 
				calc_maxstatus, 
				ord_number, 
				ivh_quantity, 
				ivh_rate, 
				ivh_charge, 
				cht_itemcode, 
				ivh_splitbill_flag, 
				dummy_ordstatus,
				ivh_company,
				ivh_carrier,
				ivh_archarge,
				ivh_arcurrency,
				ivh_loadtime,
				ivh_unloadtime,
				ivh_drivetime,
				ivh_totaltime,
				ivh_rateby,
				ivh_unit,
				ivh_rateunit,
				lgh_count,
				ord_remark,
				billto_altid,
				ivh_revenue_date,
				ivh_batch_id,
				mailto_flag,
				ivh_stopoffs,
				ivh_quantity_type,
				ivh_charge_type, 
				ivh_originzipcode, 
				ivh_destzipcode,
                inv_revenue_pay_fix,
                inv_revenue_pay ,
				ord_fromorder,
				furthestpointconsignee_flag ,
				furthestpoint_city,
				furthestpoint_state
			FROM 	#temp


GO
GRANT EXECUTE ON  [dbo].[d_inv_edit_hdr_stl_sp] TO [public]
GO
