SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[tmail_OttMakeTrailerCommHistoryRec]
		@trl_id				VARCHAR(13),
		@tch_dttm			DATETIME,
		@tch_rcvd			DATETIME,
		@acm_system			VARCHAR(6),
		@tch_batteryalert	CHAR(1),
		@tch_fuelalert		CHAR(1),
		@tch_pmalert		CHAR(1),
		@tch_temp1alert		CHAR(1),
		@tch_temp2alert		CHAR(1),
		@tch_temp3alert		CHAR(1),
		@tch_temp4alert		CHAR(1),
		@tch_temp5alert		CHAR(1),
		@tch_ambient		FLOAT,
		@tch_discharge		FLOAT,
		@tch_cmpt1_return	FLOAT,
		@tch_cmpt1_setpoint	FLOAT,
		@tch_cmpt1_state	VARCHAR(6),
		@tch_cmpt2_return	FLOAT,
		@tch_cmpt2_setpoint	FLOAT,
		@tch_cmpt2_state	VARCHAR(6),
		@tch_cmpt3_return	FLOAT,
		@tch_cmpt3_setpoint	FLOAT,
		@tch_cmpt3_state	VARCHAR(6),
		@tch_cmpt4_return	FLOAT,
		@tch_cmpt4_setpoint	FLOAT,
		@tch_cmpt4_state	VARCHAR(6),
		@tch_cmpt5_return	FLOAT,
		@tch_cmpt5_setpoint	FLOAT,
		@tch_cmpt5_state	VARCHAR(6),
		@tch_auxtemp1		FLOAT,
		@tch_auxtemp2		FLOAT,
		@tch_auxtemp3		FLOAT,
		@tch_auxtemp4		FLOAT,
		@tch_auxtemp5		FLOAT,
		@tch_door1			CHAR(1),
		@tch_door1b			CHAR(1),
		@tch_door2			CHAR(1),
		@tch_door3			CHAR(1),
		@tch_door4			CHAR(1),
		@tch_door5			CHAR(1),
		@tch_hook			VARCHAR(6),
		@tch_hooktractor	VARCHAR(8),
		@tch_airbrake		CHAR(1),
		@tch_intelliset		VARCHAR(20),
		@tch_alarmsummary	VARCHAR(6),
		@tch_reefermode		VARCHAR(6),
		@tch_power			CHAR(1),
		@tch_servicestate	VARCHAR(6),
		@tch_standbystatus	VARCHAR(6),
		@tch_standbyhours	INT,
		@tch_switchonhours	INT,
		@tch_triggerevent	VARCHAR(MAX),
		@tch_afax			VARCHAR(6),
		@tch_voltage		FLOAT,
		@tch_controlprobe	CHAR(1),
		@tch_enginehrs		INT,
		@tch_fuel			FLOAT,
		@tch_pmhour			INT,
		@ckc_number			INT

AS

-- =============================================================================
-- Stored Proc: tmail_OttMakeTrailerCommHistoryRec
-- Author     :	Sensabaugh, Virgil
-- Create date: 2013.10.02
-- Description:
--      This procedure will take the given data from QC ESS Events and 
--      insert that date into the trailercommhistory table.
--		NOTE:  The mapping of data to the various checkcall table fields will be 
--		determined by the application function/method that calls this stored
--		proc.
--      
--      Outputs:
--      ------------------------------------------------------------------------
--      None
--
--      Input parameters:
--      ------------------------------------------------------------------------
--		001 - @trl_id				VARCHAR(13),
--		002 - @tch_dttm				DATETIME,
--		003 - @tch_rcvd				DATETIME,
--		004 - @acm_system			VARCHAR(6),
--		005 - @tch_batteryalert		CHAR(1),
--		006 - @tch_fuelalert		CHAR(1),
--		007 - @tch_pmalert			CHAR(1),
--		008 - @tch_temp1alert		CHAR(1),
--		009 - @tch_temp2alert		CHAR(1),
--		010 - @tch_temp3alert		CHAR(1),
--		011 - @tch_temp4alert		CHAR(1),
--		012 - @tch_temp5alert		CHAR(1),
--		013 - @tch_ambient			FLOAT,
--		014 - @tch_discharge		FLOAT,
--		015 - @tch_cmpt1_return		FLOAT,
--		016 - @tch_cmpt1_setpoint	FLOAT,
--		017 - @tch_cmpt1_state		VARCHAR(6),
--		018 - @tch_cmpt2_return		FLOAT,
--		019 - @tch_cmpt2_setpoint	FLOAT,
--		020 - @tch_cmpt2_state		VARCHAR(6),
--		021 - @tch_cmpt3_return		FLOAT,
--		022 - @tch_cmpt3_setpoint	FLOAT,
--		023 - @tch_cmpt3_state		VARCHAR(6),
--		024 - @tch_cmpt4_return		FLOAT,
--		025 - @tch_cmpt4_setpoint	FLOAT,
--		026 - @tch_cmpt4_state		VARCHAR(6),
--		027 - @tch_cmpt5_return		FLOAT,
--		028 - @tch_cmpt5_setpoint	FLOAT,
--		029 - @tch_cmpt5_state		VARCHAR(6),
--		030 - @tch_auxtemp1			FLOAT,
--		031 - @tch_auxtemp2			FLOAT,
--		032 - @tch_auxtemp3			FLOAT,
--		033 - @tch_auxtemp4			FLOAT,
--		034 - @tch_auxtemp5			FLOAT,
--		035 - @tch_door1			CHAR(1),
--		036 - @tch_door1b			CHAR(1),
--		037 - @tch_door2			CHAR(1),
--		038 - @tch_door3			CHAR(1),
--		039 - @tch_door4			CHAR(1),
--		040 - @tch_door5			CHAR(1),
--		041 - @tch_hook				VARCHAR(6),
--		042 - @tch_hooktractor		VARCHAR(8),
--		043 - @tch_airbrake			CHAR(1),
--		044 - @tch_intelliset		VARCHAR(20),
--		045 - @tch_alarmsummary		VARCHAR(6),
--		046 - @tch_reefermode		VARCHAR(6),
--		047 - @tch_power			CHAR(1),
--		048 - @tch_servicestate		VARCHAR(6),
--		049 - @tch_standbystatus	VARCHAR(6),
--		050 - @tch_standbyhours		INT,
--		051 - @tch_switchonhours	INT,
--		052 - @tch_triggerevent		VARCHAR(MAX),
--		053 - @tch_afax				VARCHAR(6),
--		054 - @tch_voltage			FLOAT,
--		055 - @tch_controlprobe		CHAR(1),
--		056 - @tch_enginehrs		INT,
--		057 - @tch_fuel				FLOAT,
--		058 - @tch_pmhour			INT,
--		059 - @ckc_number			INT
--
--      Modification Log:
--      ------------------------------------------------------------------------
--      ...PTS 73523 - VMS - 2013.11.20 - Rename proc to match name in VB.Net application
--                                        and move proc from TotalMail section of stored 
--                                        procs to TMW Suite section.
-- =============================================================================

BEGIN

	INSERT INTO dbo.trailercommhistory (
		trl_id,
		tch_dttm,
		tch_rcvd,
		acm_system,
		tch_batteryalert,
		tch_fuelalert,
		tch_pmalert,
		tch_temp1alert,
		tch_temp2alert,
		tch_temp3alert,
		tch_temp4alert,
		tch_temp5alert,
		tch_ambient,
		tch_discharge,
		tch_cmpt1_return,
		tch_cmpt1_setpoint,
		tch_cmpt1_state,
		tch_cmpt2_return,
		tch_cmpt2_setpoint,
		tch_cmpt2_state,
		tch_cmpt3_return,
		tch_cmpt3_setpoint,
		tch_cmpt3_state,
		tch_cmpt4_return,
		tch_cmpt4_setpoint,
		tch_cmpt4_state,
		tch_cmpt5_return,
		tch_cmpt5_setpoint,
		tch_cmpt5_state,
		tch_auxtemp1,
		tch_auxtemp2,
		tch_auxtemp3,
		tch_auxtemp4,
		tch_auxtemp5,
		tch_door1,
		tch_door1b,
		tch_door2,
		tch_door3,
		tch_door4,
		tch_door5,
		tch_hook,
		tch_hooktractor,
		tch_airbrake,
		tch_intelliset,
		tch_alarmsummary,
		tch_reefermode,
		tch_power,
		tch_servicestate,
		tch_standbystatus,
		tch_standbyhours,
		tch_switchonhours,
		tch_triggerevent,
		tch_afax,
		tch_voltage,
		tch_controlprobe,
		tch_enginehrs,
		tch_fuel,
		tch_pmhour,
		ckc_number)
	VALUES (
		@trl_id,
		@tch_dttm,
		@tch_rcvd,
		@acm_system,
		@tch_batteryalert,
		@tch_fuelalert,
		@tch_pmalert,
		@tch_temp1alert,
		@tch_temp2alert,
		@tch_temp3alert,
		@tch_temp4alert,
		@tch_temp5alert,
		@tch_ambient,
		@tch_discharge,
		@tch_cmpt1_return,
		@tch_cmpt1_setpoint,
		@tch_cmpt1_state,
		@tch_cmpt2_return,
		@tch_cmpt2_setpoint,
		@tch_cmpt2_state,
		@tch_cmpt3_return,
		@tch_cmpt3_setpoint,
		@tch_cmpt3_state,
		@tch_cmpt4_return,
		@tch_cmpt4_setpoint,
		@tch_cmpt4_state,
		@tch_cmpt5_return,
		@tch_cmpt5_setpoint,
		@tch_cmpt5_state,
		@tch_auxtemp1,
		@tch_auxtemp2,
		@tch_auxtemp3,
		@tch_auxtemp4,
		@tch_auxtemp5,
		@tch_door1,
		@tch_door1b,
		@tch_door2,
		@tch_door3,
		@tch_door4,
		@tch_door5,
		@tch_hook,
		@tch_hooktractor,
		@tch_airbrake,
		@tch_intelliset,
		@tch_alarmsummary,
		@tch_reefermode,
		@tch_power,
		@tch_servicestate,
		@tch_standbystatus,
		@tch_standbyhours,
		@tch_switchonhours,
		@tch_triggerevent,
		@tch_afax,
		@tch_voltage,
		@tch_controlprobe,
		@tch_enginehrs,
		@tch_fuel,
		@tch_pmhour,
		@ckc_number)
END

GO
GRANT EXECUTE ON  [dbo].[tmail_OttMakeTrailerCommHistoryRec] TO [public]
GO
