CREATE TABLE [dbo].[DW_MODIFY_ATTRIBUTES]
(
[DW_NAME] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SEQ] [int] NOT NULL,
[ATTRIBUTE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DATE_MODIFIED] [datetime] NULL,
[USER_MODIFIED] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPRESSION_LARGE] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DW_MODIFY_ATTRIBUTES] ADD CONSTRAINT [pk_DW_MODIFY_ATTRIBUTES] PRIMARY KEY CLUSTERED ([DW_NAME], [SEQ], [ATTRIBUTE]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[DW_MODIFY_ATTRIBUTES] TO [public]
GO
GRANT INSERT ON  [dbo].[DW_MODIFY_ATTRIBUTES] TO [public]
GO
GRANT SELECT ON  [dbo].[DW_MODIFY_ATTRIBUTES] TO [public]
GO
GRANT UPDATE ON  [dbo].[DW_MODIFY_ATTRIBUTES] TO [public]
GO
