CREATE TABLE [dbo].[zprub_cc]
(
[ckc_number] [int] NOT NULL,
[ckc_status] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ckc_asgntype] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ckc_asgnid] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ckc_date] [datetime] NOT NULL,
[ckc_event] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ckc_city] [int] NULL,
[ckc_comment] [char] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ckc_updatedby] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ckc_updatedon] [datetime] NOT NULL,
[ckc_latseconds] [int] NULL,
[ckc_longseconds] [int] NULL,
[ckc_lghnumber] [int] NULL,
[ckc_tractor] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ckc_extsensoralarm] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ckc_vehicleignition] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ckc_milesfrom] [float] NULL,
[ckc_directionfrom] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ckc_validity] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ckc_mtavailable] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ckc_minutes] [int] NULL,
[ckc_mileage] [int] NULL,
[ckc_home] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ckc_cityname] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ckc_state] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ckc_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ckc_commentlarge] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ckc_minutes_to_final] [int] NULL,
[ckc_miles_to_final] [int] NULL,
[ckc_Odometer] [int] NULL,
[TripStatus] [int] NULL,
[ckc_odometer2] [int] NULL,
[ckc_speed] [int] NULL,
[ckc_speed2] [int] NULL,
[ckc_heading] [float] NULL,
[ckc_gps_type] [int] NULL,
[ckc_gps_miles] [float] NULL,
[ckc_fuel_meter] [float] NULL,
[ckc_idle_meter] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[zprub_cc] ADD CONSTRAINT [zuk_number] PRIMARY KEY CLUSTERED ([ckc_number]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
