CREATE TABLE [dbo].[legheader_active]
(
[lgh_number] [int] NOT NULL,
[lgh_firstlegnumber] [int] NULL,
[lgh_lastlegnumber] [int] NULL,
[lgh_drvtripnumber] [int] NULL,
[lgh_cost] [float] NULL,
[lgh_revenue] [float] NULL,
[lgh_odometerstart] [int] NULL,
[lgh_odometerend] [int] NULL,
[lgh_milesshortest] [smallint] NULL,
[lgh_milespractical] [smallint] NULL,
[lgh_allocfactor] [float] NULL,
[lgh_startdate] [datetime] NULL,
[lgh_enddate] [datetime] NULL,
[lgh_startcity] [int] NULL,
[lgh_endcity] [int] NULL,
[lgh_startregion1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_endregion1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_startstate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_endstate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_outstatus] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_startlat] [int] NULL,
[lgh_startlong] [int] NULL,
[lgh_endlat] [int] NULL,
[lgh_endlong] [int] NULL,
[lgh_class1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_class2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_class3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_class4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_number_start] [int] NULL,
[stp_number_end] [int] NULL,
[cmp_id_start] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_id_end] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_startregion2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_startregion3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_startregion4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_endregion2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_endregion3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_endregion4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_instatus] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_driver1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_driver2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_tractor] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_primary_trailer] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mov_number] [int] NULL,
[fgt_number] [int] NULL,
[lgh_priority] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_schdtearliest] [datetime] NULL,
[lgh_schdtlatest] [datetime] NULL,
[cmd_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fgt_description] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_teamleader] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_fleet] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_division] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_domicile] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_company] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_terminal] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_type1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_type2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_type3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_type4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_company] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_division] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_fleet] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_terminal] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_type1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_type2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_type3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_type4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mfh_number] [int] NULL,
[trl_company] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_fleet] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_division] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_terminal] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_type1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_type2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_type3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_type4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_hdrnumber] [int] NULL,
[timestamp] [timestamp] NULL,
[lgh_fueltaxstatus] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_mtmiles] [smallint] NULL,
[lgh_prjdate1] [datetime] NULL,
[lgh_etaalert1] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_etamins1] [int] NULL,
[lgh_outofroute_routing] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_type1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_alloc_revenue] [money] NULL,
[lgh_primary_pup] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_prod_hr] [float] NULL,
[lgh_tot_hr] [float] NULL,
[lgh_ld_unld_time] [float] NULL,
[lgh_load_time] [float] NULL,
[lgh_startcty_nmstct] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_endcty_nmstct] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_carrier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_enddate_arrival] [datetime] NULL,
[lgh_dsp_date] [datetime] NULL,
[lgh_geo_date] [datetime] NULL,
[lgh_nexttrailer1] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_nexttrailer2] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_etamilestofinal] [int] NULL,
[lgh_etamintofinal] [int] NULL,
[lgh_split_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_createdby] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_createdon] [datetime] NULL,
[lgh_createapp] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_updatedby] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_updatedon] [datetime] NULL,
[lgh_updateapp] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_rstartdate] [datetime] NULL,
[lgh_renddate] [datetime] NULL,
[lgh_rstartcity] [int] NULL,
[lgh_rendcity] [int] NULL,
[lgh_rstartregion1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_rendregion1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_rstartstate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_rendstate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_rstartlat] [int] NULL,
[lgh_rstartlong] [int] NULL,
[lgh_rendlat] [int] NULL,
[lgh_rendlong] [int] NULL,
[stp_number_rstart] [int] NULL,
[stp_number_rend] [int] NULL,
[cmp_id_rstart] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_id_rend] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_rstartregion2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_rstartregion3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_rstartregion4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_rendregion2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_rendregion3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_rendregion4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_rstartcty_nmstct] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_rendcty_nmstct] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_feetavailable] [smallint] NULL,
[can_cap_expires] [datetime] NULL,
[can_ld_expires] [datetime] NULL,
[lgh_dispatchdate] [datetime] NULL,
[lgh_asset_lock] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_asset_lock_dtm] [datetime] NULL,
[lgh_asset_lock_user] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_load_origin] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_est_lhrate] [float] NULL,
[lgh_est_lhpay] [float] NULL,
[lgh_est_dhrate] [float] NULL,
[lgh_est_dhpay] [float] NULL,
[lgh_est_accessorials] [float] NULL,
[drvplan_number] [int] NULL,
[next_drp_stp_number] [int] NULL,
[next_pup_stp_number] [int] NULL,
[ord_totalweight] [int] NULL,
[ord_totalvolume] [int] NULL,
[tot_count] [int] NULL,
[cmd_count] [int] NULL,
[ordercount] [smallint] NULL,
[xdock] [int] NULL,
[ord_stopcount] [tinyint] NULL,
[washstatus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref_type] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref_number] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[npup_cmpid] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[npup_cmpname] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[npup_ctyname] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[npup_state] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[npup_arrivaldate] [datetime] NULL,
[ndrp_cmpid] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ndrp_cmpname] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ndrp_ctyname] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ndrp_state] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ndrp_arrivaldate] [datetime] NULL,
[npup_departuredate] [datetime] NULL,
[ndrp_departuredate] [datetime] NULL,
[lgh_type2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo5] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo6] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo7] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo8] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo9] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo10] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo11] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo12] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo13] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo14] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_extrainfo15] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_tm_status] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_tour_number] [int] NULL,
[o_cmpname] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[o_state] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[d_cmpname] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[d_state] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[f_cmpid] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[f_cmpname] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[f_ctyname] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[f_state] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_cmpid] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_cmpname] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_ctyname] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[l_state] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[evt_driver1_name] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[evt_driver2_name] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_outstatus_name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_instatus_name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_priority_name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_type1_name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_class1_name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_class2_name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_class3_name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_class4_name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[opt_trc_type4_label] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[opt_trl_type4_label] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_lgh_type1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c_lgh_type2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_fleet_name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_ord_subcompany] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_bookedby] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_trl_type1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_totalmiles] [int] NULL,
[o_cmp_geoloc] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[d_cmp_geoloc] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[d_address1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[d_address2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[next_stp_event_code] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[next_stop_of_total] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_comment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_miles] [int] NULL,
[lgh_linehaul] [float] NULL,
[lgh_ord_charge] [float] NULL,
[lgh_act_weight] [float] NULL,
[lgh_est_weight] [float] NULL,
[lgh_tot_weight] [float] NULL,
[lgh_reftype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_refnum] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_max_weight_exceeded] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_type1name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_type2name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_type3name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_type4name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_tmstatusstopnumber] [int] NULL,
[lgh_tm_statusname] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_detstatus] [int] NOT NULL CONSTRAINT [DF__legheader__lgh_d__13AA3F2D] DEFAULT (0),
[ord_billto] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_washplan] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_hzd_cmd_class] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_company] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_originzip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_destzip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_204status] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_booked_revtype1] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_order_source] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_permit_status] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_204date] [datetime] NULL,
[lgh_trc_comment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_ace_status] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[next_ndrp_cmpid] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[next_ndrp_cmpname] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[next_ndrp_ctyname] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[next_ndrp_state] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[next_ndrp_arrivaldate] [datetime] NULL,
[lgh_ace_status_name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_chassis] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__legheader__lgh_c__248E1192] DEFAULT ('UNKNOWN'),
[lgh_chassis2] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__legheader__lgh_c__258235CB] DEFAULT ('UNKNOWN'),
[lgh_204_tradingpartner] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ma_transaction_id] [bigint] NULL,
[ma_tour_number] [int] NULL,
[ma_tour_sequence] [tinyint] NULL,
[ma_tour_max_sequence] [tinyint] NULL,
[ma_mpp_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ma_trc_number] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ma_lgh_number] [int] NULL,
[lgh_total_mov_bill_miles] [int] NULL,
[lgh_total_mov_miles] [int] NULL,
[lgh_mile_overage_message] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_car_rate] [money] NULL,
[lgh_car_charge] [money] NULL,
[lgh_car_accessorials] [decimal] (12, 4) NULL,
[lgh_car_totalcharge] [money] NULL,
[lgh_recommended_car_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_spot_rate_updatedby] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_spot_rate_updateddt] [datetime] NULL,
[lgh_spot_rate] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_ship_status] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_protected_rate] [money] NULL,
[lgh_avg_rate] [money] NULL,
[lgh_edi_counter] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_faxemail_created] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_externalrating_miles] [int] NULL,
[lgh_acc_fsc] [money] NULL,
[lgh_prev_seg_status] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_prev_seg_status_last_updated] [datetime] NULL,
[lgh_raildispatchstatus] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_dolly] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_dolly2] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_trailer3] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_trailer4] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_teamleader] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_optimizestatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_optimizedrouteid] [int] NULL,
[lgh_other_status1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_other_status2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_direct_route_status1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_drv_tndr_status] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_autoloadmaxgvw] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[legheader_active] ADD CONSTRAINT [ux_legheader_active] PRIMARY KEY CLUSTERED ([lgh_number]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_legheader_active_lgh_class1] ON [dbo].[legheader_active] ([lgh_class1]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_legheader_active_lgh_class2] ON [dbo].[legheader_active] ([lgh_class2]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_legheader_active_lgh_class3] ON [dbo].[legheader_active] ([lgh_class3]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_legheader_active_lgh_class4] ON [dbo].[legheader_active] ([lgh_class4]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_legheader_active_lgh_driver1] ON [dbo].[legheader_active] ([lgh_driver1]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [uk_legheader_active_lgh_outstatus] ON [dbo].[legheader_active] ([lgh_outstatus], [ord_hdrnumber], [lgh_carrier]) WITH (FILLFACTOR=70) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_lgha_outstat_ordhdr_mov] ON [dbo].[legheader_active] ([lgh_outstatus], [ord_hdrnumber], [mov_number]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_legheader_active_tractor] ON [dbo].[legheader_active] ([lgh_tractor]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_legheader_active_ma_tran_tour] ON [dbo].[legheader_active] ([ma_transaction_id], [ma_tour_number]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_legheader_active_ma_tran_trc_seq] ON [dbo].[legheader_active] ([ma_transaction_id], [ma_trc_number], [ma_tour_sequence]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [uk_legheader_active_mov_number] ON [dbo].[legheader_active] ([mov_number], [lgh_number], [lgh_carrier]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_lgha_ordhdr_mov] ON [dbo].[legheader_active] ([ord_hdrnumber], [mov_number]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[legheader_active] TO [public]
GO
GRANT INSERT ON  [dbo].[legheader_active] TO [public]
GO
GRANT REFERENCES ON  [dbo].[legheader_active] TO [public]
GO
GRANT SELECT ON  [dbo].[legheader_active] TO [public]
GO
GRANT UPDATE ON  [dbo].[legheader_active] TO [public]
GO
