CREATE TABLE [dbo].[comprobante]
(
[VERSION] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SERIE] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[llave] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECHAEXPEDICION] [datetime] NULL,
[SELLO] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ANOAPROBACION] [int] NOT NULL,
[NOAPROBACION] [int] NOT NULL,
[NOCERTIFICADO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CERTIFICADO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONDICIONESDEPAGO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBTOTAL] [decimal] (28, 2) NOT NULL,
[DESCUENTO] [numeric] (28, 2) NULL,
[MOTIVODESCUENTO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FORMADEPAGO] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[METODOSDEPAGO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPODECOMPROBANTE] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TOTAL] [decimal] (28, 2) NOT NULL,
[totalimpuestosretenidos] [decimal] (19, 2) NOT NULL,
[totalimpuestostrasladados] [decimal] (19, 2) NOT NULL,
[ivh_userid] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECHAGENERA] [datetime] NULL,
[ivh_invoicenumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ord_number] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mov_number] [int] NULL,
[ivh_remark] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivh_tractor] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivh_trailer] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tractor_licnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trailer_licnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastname] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[firstname] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[licensenumber] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ciudad_origen] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ciudad_destino] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[moneda] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[masterbill] [bigint] NOT NULL,
[peso_estimado] [float] NULL,
[RFC] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOMBRE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CALLE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOEXTERIOR] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOINTERIOR] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COLONIA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUNICIPIO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LOCALIDAD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESTADO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAIS] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CODIGOPOSTAL] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RFCRECEPTOR] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOMBRERECEPTOR] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CALLERECEPTOR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NOEXTERIORRECEPTOR] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOINTERIORRECEPTOR] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COLONIARECEPTOR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCALIDADRECEPTOR] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUNICIPIORECEPTOR] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ESTADORECEPTOR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAISRECEPTOR] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CODIGOPOSTALRECEPTOR] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rfc_origen] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[calle_origen] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ext_origen] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[int_origen] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[colonia_origen] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[municipio_origen] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cd_origen] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[edo_origen] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pais_origen] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip_origen] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name_origen] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rfc_destino] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[calle_destino] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ext_destino] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[int_destino] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[colonia_destino] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[municipo_destino] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cd_destino] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[edo_destino] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pais_destino] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip_destino] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name_destino] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[archivo_tif] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARCHIVOPDF] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARCHIVOXML] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESTATUS] [int] NULL,
[PARCIALIDAD] [int] NULL,
[FECHA_CANCELA] [datetime] NULL,
[TASA_IVA] [decimal] (18, 2) NULL,
[RETENCIONTASA] [decimal] (28, 2) NULL,
[cadena_original] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fletes] [decimal] (18, 2) NULL,
[seguro] [decimal] (18, 2) NULL,
[autopistas] [decimal] (18, 2) NULL,
[otros] [decimal] (18, 2) NULL,
[maniobras] [decimal] (18, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[comprobante] ADD CONSTRAINT [PK__comprobante__31EC6D26] PRIMARY KEY CLUSTERED ([ivh_invoicenumber], [masterbill]) ON [PRIMARY]
GO
