CREATE TABLE [dbo].[ESTATACOLIST]
(
[login] [varchar] (132) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_id] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ESTATACOLIST_cmp_id] ON [dbo].[ESTATACOLIST] ([cmp_id]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ESTATACOLIST_login] ON [dbo].[ESTATACOLIST] ([login]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[ESTATACOLIST] TO [public]
GO
GRANT INSERT ON  [dbo].[ESTATACOLIST] TO [public]
GO
GRANT SELECT ON  [dbo].[ESTATACOLIST] TO [public]
GO
GRANT UPDATE ON  [dbo].[ESTATACOLIST] TO [public]
GO
