CREATE TABLE [dbo].[TariffInputTS]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[dtm_billdate_dt] [datetime] NULL,
[dtm_idt_start_date] [datetime] NULL,
[str_billto] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_trailer] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_revtype1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_revtype2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_revtype3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_revtype4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_cmdcode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_originpoint] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_origincity] [decimal] (19, 6) NULL,
[str_destpoint] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_destcity] [decimal] (19, 6) NULL,
[dec_weight] [decimal] (19, 6) NULL,
[str_wgtunit] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_pieces] [decimal] (19, 6) NULL,
[str_countunit] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_volume] [decimal] (19, 6) NULL,
[str_volunit] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_cht_itemcode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_routemiles] [decimal] (19, 6) NULL,
[str_distunit] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_orderedby] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_length] [decimal] (19, 6) NULL,
[dec_width] [decimal] (19, 6) NULL,
[dec_height] [decimal] (19, 6) NULL,
[str_company] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_carrier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_triptype] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_mtmiles] [decimal] (19, 6) NULL,
[dec_ldmiles] [decimal] (19, 6) NULL,
[str_loadstatus] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_team] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_cartype] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_tractor] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_mileagetable] [decimal] (19, 6) NULL,
[str_drvtype1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_drvtype2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_drvtype3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_drvtype4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_trctype1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_trctype2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_trctype3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_trctype4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_itemcode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_driver] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_pytitemcode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_ii_billedmiles] [decimal] (19, 6) NULL,
[dec_ii_stopsoffpaycount] [decimal] (19, 6) NULL,
[str_is_ord_trl_type1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dtm_idt_senioritydate] [datetime] NULL,
[dec_ii_chargeablestopoffs] [decimal] (19, 6) NULL,
[str_trltype1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_trltype2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_trltype3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_trltype4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_ir_ooamileage] [decimal] (19, 6) NULL,
[dec_il_ooastops] [decimal] (19, 6) NULL,
[dec_il_carryins1] [decimal] (19, 6) NULL,
[dec_il_carryins2] [decimal] (19, 6) NULL,
[str_is_originpointonleg] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_il_origincityonleg] [decimal] (19, 6) NULL,
[str_is_destpointonleg] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_il_destcityonleg] [decimal] (19, 6) NULL,
[str_ib_orderfixedformiles] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_terms] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_ord_trctype4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_mastercompany] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_ord_trl_type2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_ord_trl_type3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_ord_trl_type4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_shipper] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_idec_revenuepermile] [decimal] (19, 6) NULL,
[dec_l_hub_miles] [decimal] (19, 6) NULL,
[dec_ii_custdoc] [decimal] (19, 6) NULL,
[str_s_shipper] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_consignee] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_stopcmpid] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_idc_loadingmeters] [decimal] (19, 6) NULL,
[dec_idc_ordered_loadingmeters] [decimal] (19, 6) NULL,
[str_is_loadingmetersunit] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_idc_orderedweight] [decimal] (19, 6) NULL,
[dec_idc_orderedvolume] [decimal] (19, 6) NULL,
[dec_l_mt_hub_miles] [decimal] (19, 6) NULL,
[dec_l_ld_hub_miles] [decimal] (19, 6) NULL,
[dec_sd_mileage_adj_pct] [decimal] (19, 6) NULL,
[str_originzip] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_destzip] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_il_ord_hdrnumber] [decimal] (19, 6) NULL,
[dec_r_mt_cust_miles] [decimal] (19, 6) NULL,
[dec_r_ld_cust_miles] [decimal] (19, 6) NULL,
[dec_idec_drtodmiles] [decimal] (19, 6) NULL,
[str_is_trlconfiguration] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ib_donotapplylhmins] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_origin_service_area] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_origin_service_zone] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_origin_service_center] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_origin_service_region] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_dest_service_area] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_dest_service_zone] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_dest_service_center] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_dest_service_region] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_lghtype2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_lghtype3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_lghtype4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_il_lghnumber] [decimal] (19, 6) NULL,
[str_s_thirdparty] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_thirdpartytype] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_idc_profit] [decimal] (19, 6) NULL,
[dec_i_segments] [decimal] (19, 6) NULL,
[str_orig_county] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_dest_county] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_origin_ord] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_dest_ord] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_billto_othertype1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_billto_othertype2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_masterordernumber] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dtm_idt_avgfuelprice_date] [datetime] NULL,
[dec_sl_lghnumber] [decimal] (19, 6) NULL,
[str_drv_payto] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_trc_owner] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_trl_owner] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_car_payto] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_mpp_terminal] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_trc_terminal] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_trl_terminal] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_ii_drp_count] [decimal] (19, 6) NULL,
[dec_ii_pup_count] [decimal] (19, 6) NULL,
[str_is_primary_driver] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_freightpickupcmpid] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_trailer2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_ord_unit] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_sdec_quantity] [decimal] (19, 6) NULL,
[dec_idec_odmiles] [decimal] (19, 6) NULL,
[dec_ii_instatemiles] [decimal] (19, 6) NULL,
[str_ib_useodmiles] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ib_useinstatemiles] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_sdec_routemiles_total] [decimal] (19, 6) NULL,
[dec_sdec_mtmiles_total] [decimal] (19, 6) NULL,
[dec_sdec_ldmiles_total] [decimal] (19, 6) NULL,
[dec_carrier_service_days] [decimal] (19, 6) NULL,
[str_s_stp_type] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_calc_dlaycm] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_calc_dlayst] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_timeunit] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_invoiceby] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_l_stp_number] [decimal] (19, 6) NULL,
[dec_fgt_number] [decimal] (19, 6) NULL,
[str_s_route] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_chassis] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_chassis2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_dolly] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_dolly2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_trailer3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_s_trailer4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_idc_gross_profit_margin] [decimal] (19, 6) NULL,
[str_s_dbs_type] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_sdc_ordtotalweight] [decimal] (19, 6) NULL,
[str_sb_onlycarriercontractedrates] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_trl_company] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_trl_fleet] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_trl_division] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_trc_company] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_trc_fleet] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_trc_division] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_drv_company] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_drv_fleet] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_drv_division] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_drv_domicile] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_drv_teamleader] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_is_pallet_type] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dec_il_pallet_count] [decimal] (19, 6) NULL,
[str_carrier_service_level] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ratemode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_dbh_id] [decimal] (19, 6) NULL,
[str_dbs_id] [decimal] (19, 6) NULL,
[dec_loaded_volume] [decimal] (19, 6) NULL,
[str_s_dbs_group] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_mpp_branch] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_mpp2_branch] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_trc_branch] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_trl_branch] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_tpr_branch] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_car_branch] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ord_branch] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastUpdateDate] [datetime] NOT NULL CONSTRAINT [DF__TariffInp__LastU__39862A88] DEFAULT (getdate()),
[LastUpdateBy] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__TariffInp__LastU__3A7A4EC1] DEFAULT (suser_name())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TariffInputTS] ADD CONSTRAINT [pk_TariffInputTS] PRIMARY KEY CLUSTERED ([Id]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[TariffInputTS] TO [public]
GO
GRANT INSERT ON  [dbo].[TariffInputTS] TO [public]
GO
GRANT SELECT ON  [dbo].[TariffInputTS] TO [public]
GO
GRANT UPDATE ON  [dbo].[TariffInputTS] TO [public]
GO
