CREATE TABLE [dbo].[Usuario]
(
[IIDUSUARIO] [int] NOT NULL IDENTITY(1, 1),
[NOMBREUSUARIO] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IIDTIPOUSUARIO] [int] NULL,
[CONTRA] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BHABILITADO] [int] NULL,
[IIDPERSONA] [int] NULL
) ON [PRIMARY]
GO
