CREATE TABLE [dbo].[tck_expresscode]
(
[tck_account_number] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tex_expresscodenumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tex_currency] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tex_100000] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_100001] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_100002] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_100003] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_100004] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_100005] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_100006] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_100007] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_100008] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_100009] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_10000] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_10001] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_10002] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_10003] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_10004] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_10005] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_10006] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_10007] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_10008] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_10009] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_1000] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_1001] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_1002] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_1003] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_1004] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_1005] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_1006] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_1007] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_1008] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_1009] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_100] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_101] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_102] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_103] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_104] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_105] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_106] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_107] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_108] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_109] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_10] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_11] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_12] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_13] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_14] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_15] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_16] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_17] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_18] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_19] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_0] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_1] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_2] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_3] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_4] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_5] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_6] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_7] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_8] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_9] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_s25] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_s50] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_s75] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_s100] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_s125] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_s150] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_s200] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_s300] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_s400] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_s500] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_s700] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_s900] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_expire_date] [datetime] NULL,
[tex_initial_date] [datetime] NULL,
[tex_status] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tex_createdate] [datetime] NOT NULL,
[tex_createuser] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tex_modifieddate] [datetime] NULL,
[tex_modifieduser] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tck_expresscode] ADD CONSTRAINT [PK_tck_expresscode] PRIMARY KEY NONCLUSTERED ([tck_account_number], [tex_expresscodenumber], [tex_currency]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[tck_expresscode] TO [public]
GO
GRANT INSERT ON  [dbo].[tck_expresscode] TO [public]
GO
GRANT REFERENCES ON  [dbo].[tck_expresscode] TO [public]
GO
GRANT SELECT ON  [dbo].[tck_expresscode] TO [public]
GO
GRANT UPDATE ON  [dbo].[tck_expresscode] TO [public]
GO
