CREATE TABLE [dbo].[Timeline_export_detail]
(
[DUNS] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlh_number] [int] NULL,
[tlh_name] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlh_effective] [datetime] NULL,
[tlh_expires] [datetime] NULL,
[tlh_supplier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlh_plant] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlh_dock] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlh_jittime] [int] NULL,
[tlh_leaddays] [int] NULL,
[tlh_leadbasis] [int] NULL,
[tlh_sequence] [int] NULL,
[tlh_direction] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlh_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlh_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlh_branch] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlh_timezone] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlh_subroutedomicle] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlh_dow] [int] NULL,
[tlh_specialist] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlh_updatedby] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tlh_updatedon] [datetime] NULL,
[tlh_effective_basis] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail1_tld_master_ordnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail1_tld_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail1_tld_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail1_tld_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail1_tld_origin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail1_tld_arrive_orig] [datetime] NULL,
[Detail1_tld_arrive_org_lead] [int] NULL,
[Detail1_tld_depart_orig] [datetime] NULL,
[Detail1_tld_depart_org_lead] [int] NULL,
[Detail1_tld_dest] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail1_tld_arrive_yard] [datetime] NULL,
[Detail1_tld_arrive_lead] [int] NULL,
[Detail1_tld_arrive_dest] [datetime] NULL,
[Detail1_tld_arrive_dest_lead] [int] NULL,
[Detail1_tld_trl_unload] [datetime] NULL,
[Detail1_tld_trl_unload_lead] [int] NULL,
[Detail2_tld_master_ordnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail2_tld_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail2_tld_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail2_tld_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail2_tld_origin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail2_tld_arrive_orig] [datetime] NULL,
[Detail2_tld_arrive_org_lead] [int] NULL,
[Detail2_tld_depart_orig] [datetime] NULL,
[Detail2_tld_depart_org_lead] [int] NULL,
[Detail2_tld_dest] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail2_tld_arrive_yard] [datetime] NULL,
[Detail2_tld_arrive_lead] [int] NULL,
[Detail2_tld_arrive_dest] [datetime] NULL,
[Detail2_tld_arrive_dest_lead] [int] NULL,
[Detail2_tld_trl_unload] [datetime] NULL,
[Detail2_tld_trl_unload_lead] [int] NULL,
[Detail3_tld_master_ordnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail3_tld_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail3_tld_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail3_tld_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail3_tld_origin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail3_tld_arrive_orig] [datetime] NULL,
[Detail3_tld_arrive_org_lead] [int] NULL,
[Detail3_tld_depart_orig] [datetime] NULL,
[Detail3_tld_depart_org_lead] [int] NULL,
[Detail3_tld_dest] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail3_tld_arrive_yard] [datetime] NULL,
[Detail3_tld_arrive_lead] [int] NULL,
[Detail3_tld_arrive_dest] [datetime] NULL,
[Detail3_tld_arrive_dest_lead] [int] NULL,
[Detail3_tld_trl_unload] [datetime] NULL,
[Detail3_tld_trl_unload_lead] [int] NULL,
[Detail4_tld_master_ordnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail4_tld_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail4_tld_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail4_tld_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail4_tld_origin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail4_tld_arrive_orig] [datetime] NULL,
[Detail4_tld_arrive_org_lead] [int] NULL,
[Detail4_tld_depart_orig] [datetime] NULL,
[Detail4_tld_depart_org_lead] [int] NULL,
[Detail4_tld_dest] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail4_tld_arrive_yard] [datetime] NULL,
[Detail4_tld_arrive_lead] [int] NULL,
[Detail4_tld_arrive_dest] [datetime] NULL,
[Detail4_tld_arrive_dest_lead] [int] NULL,
[Detail4_tld_trl_unload] [datetime] NULL,
[Detail4_tld_trl_unload_lead] [int] NULL,
[Detail5_tld_master_ordnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail5_tld_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail5_tld_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail5_tld_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail5_tld_origin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail5_tld_arrive_orig] [datetime] NULL,
[Detail5_tld_arrive_org_lead] [int] NULL,
[Detail5_tld_depart_orig] [datetime] NULL,
[Detail5_tld_depart_org_lead] [int] NULL,
[Detail5_tld_dest] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail5_tld_arrive_yard] [datetime] NULL,
[Detail5_tld_arrive_lead] [int] NULL,
[Detail5_tld_arrive_dest] [datetime] NULL,
[Detail5_tld_arrive_dest_lead] [int] NULL,
[Detail5_tld_trl_unload] [datetime] NULL,
[Detail5_tld_trl_unload_lead] [int] NULL,
[Detail6_tld_master_ordnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail6_tld_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail6_tld_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail6_tld_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail6_tld_origin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail6_tld_arrive_orig] [datetime] NULL,
[Detail6_tld_arrive_org_lead] [int] NULL,
[Detail6_tld_depart_orig] [datetime] NULL,
[Detail6_tld_depart_org_lead] [int] NULL,
[Detail6_tld_dest] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail6_tld_arrive_yard] [datetime] NULL,
[Detail6_tld_arrive_lead] [int] NULL,
[Detail6_tld_arrive_dest] [datetime] NULL,
[Detail6_tld_arrive_dest_lead] [int] NULL,
[Detail6_tld_trl_unload] [datetime] NULL,
[Detail6_tld_trl_unload_lead] [int] NULL,
[Detail7_tld_master_ordnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail7_tld_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail7_tld_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail7_tld_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail7_tld_origin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail7_tld_arrive_orig] [datetime] NULL,
[Detail7_tld_arrive_org_lead] [int] NULL,
[Detail7_tld_depart_orig] [datetime] NULL,
[Detail7_tld_depart_org_lead] [int] NULL,
[Detail7_tld_dest] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail7_tld_arrive_yard] [datetime] NULL,
[Detail7_tld_arrive_lead] [int] NULL,
[Detail7_tld_arrive_dest] [datetime] NULL,
[Detail7_tld_arrive_dest_lead] [int] NULL,
[Detail7_tld_trl_unload] [datetime] NULL,
[Detail7_tld_trl_unload_lead] [int] NULL,
[Detail8_tld_master_ordnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail8_tld_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail8_tld_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail8_tld_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail8_tld_origin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail8_tld_arrive_orig] [datetime] NULL,
[Detail8_tld_arrive_org_lead] [int] NULL,
[Detail8_tld_depart_orig] [datetime] NULL,
[Detail8_tld_depart_org_lead] [int] NULL,
[Detail8_tld_dest] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail8_tld_arrive_yard] [datetime] NULL,
[Detail8_tld_arrive_lead] [int] NULL,
[Detail8_tld_arrive_dest] [datetime] NULL,
[Detail8_tld_arrive_dest_lead] [int] NULL,
[Detail8_tld_trl_unload] [datetime] NULL,
[Detail8_tld_trl_unload_lead] [int] NULL,
[Detail9_tld_master_ordnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail9_tld_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail9_tld_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail9_tld_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail9_tld_origin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail9_tld_arrive_orig] [datetime] NULL,
[Detail9_tld_arrive_org_lead] [int] NULL,
[Detail9_tld_depart_orig] [datetime] NULL,
[Detail9_tld_depart_org_lead] [int] NULL,
[Detail9_tld_dest] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail9_tld_arrive_yard] [datetime] NULL,
[Detail9_tld_arrive_lead] [int] NULL,
[Detail9_tld_arrive_dest] [datetime] NULL,
[Detail9_tld_arrive_dest_lead] [int] NULL,
[Detail9_tld_trl_unload] [datetime] NULL,
[Detail9_tld_trl_unload_lead] [int] NULL,
[Detail10_tld_master_ordnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail10_tld_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail10_tld_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail10_tld_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail10_tld_origin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail10_tld_arrive_orig] [datetime] NULL,
[Detail10_tld_arrive_org_lead] [int] NULL,
[Detail10_tld_depart_orig] [datetime] NULL,
[Detail10_tld_depart_org_lead] [int] NULL,
[Detail10_tld_dest] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail10_tld_arrive_yard] [datetime] NULL,
[Detail10_tld_arrive_lead] [int] NULL,
[Detail10_tld_arrive_dest] [datetime] NULL,
[Detail10_tld_arrive_dest_lead] [int] NULL,
[Detail10_tld_trl_unload] [datetime] NULL,
[Detail10_tld_trl_unload_lead] [int] NULL,
[Detail11_tld_master_ordnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail11_tld_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail11_tld_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail11_tld_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail11_tld_origin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail11_tld_arrive_orig] [datetime] NULL,
[Detail11_tld_arrive_org_lead] [int] NULL,
[Detail11_tld_depart_orig] [datetime] NULL,
[Detail11_tld_depart_org_lead] [int] NULL,
[Detail11_tld_dest] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail11_tld_arrive_yard] [datetime] NULL,
[Detail11_tld_arrive_lead] [int] NULL,
[Detail11_tld_arrive_dest] [datetime] NULL,
[Detail11_tld_arrive_dest_lead] [int] NULL,
[Detail11_tld_trl_unload] [datetime] NULL,
[Detail11_tld_trl_unload_lead] [int] NULL,
[Detail12_tld_master_ordnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail12_tld_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail12_tld_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail12_tld_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail12_tld_origin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail12_tld_arrive_orig] [datetime] NULL,
[Detail12_tld_arrive_org_lead] [int] NULL,
[Detail12_tld_depart_orig] [datetime] NULL,
[Detail12_tld_depart_org_lead] [int] NULL,
[Detail12_tld_dest] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail12_tld_arrive_yard] [datetime] NULL,
[Detail12_tld_arrive_lead] [int] NULL,
[Detail12_tld_arrive_dest] [datetime] NULL,
[Detail12_tld_arrive_dest_lead] [int] NULL,
[Detail12_tld_trl_unload] [datetime] NULL,
[Detail12_tld_trl_unload_lead] [int] NULL,
[Detail13_tld_master_ordnum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail13_tld_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail13_tld_saturday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail13_tld_sunday] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail13_tld_origin] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail13_tld_arrive_orig] [datetime] NULL,
[Detail13_tld_arrive_org_lead] [int] NULL,
[Detail13_tld_depart_orig] [datetime] NULL,
[Detail13_tld_depart_org_lead] [int] NULL,
[Detail13_tld_dest] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Detail13_tld_arrive_yard] [datetime] NULL,
[Detail13_tld_arrive_lead] [int] NULL,
[Detail13_tld_arrive_dest] [datetime] NULL,
[Detail13_tld_arrive_dest_lead] [int] NULL,
[Detail13_tld_trl_unload] [datetime] NULL,
[Detail13_tld_trl_unload_lead] [int] NULL
) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[Timeline_export_detail] TO [public]
GO
GRANT INSERT ON  [dbo].[Timeline_export_detail] TO [public]
GO
GRANT REFERENCES ON  [dbo].[Timeline_export_detail] TO [public]
GO
GRANT SELECT ON  [dbo].[Timeline_export_detail] TO [public]
GO
GRANT UPDATE ON  [dbo].[Timeline_export_detail] TO [public]
GO
