CREATE TABLE [dbo].[FA_HOURS]
(
[AAID] [int] NOT NULL,
[GSSSESSIONID] [int] NULL,
[DURATION] [int] NULL,
[ACTIVITY_DESCRTIPTION] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CODE] [int] NULL,
[DATE] [datetime] NULL,
[MILEAGE] [float] NULL,
[SSN] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYSTATUS] [int] NOT NULL CONSTRAINT [CK_PAYSTATUS] DEFAULT (0),
[LOGSTATUS] [int] NOT NULL CONSTRAINT [CK_LOGSTATUS] DEFAULT (0),
[ORDER_INSTRUCTION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDER_DESCRIPTION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FUELBURNED] [money] NULL,
[GUESSLEG] [int] NULL CONSTRAINT [CK_GUESSLEG] DEFAULT (0),
[MPP_ID] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRC_ID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FA_HOURS] ADD CONSTRAINT [PK_FA_HOURS] PRIMARY KEY CLUSTERED ([AAID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [FA_HOURS_DATE_MPPID] ON [dbo].[FA_HOURS] ([DATE], [MPP_ID]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[FA_HOURS] TO [public]
GO
GRANT INSERT ON  [dbo].[FA_HOURS] TO [public]
GO
GRANT REFERENCES ON  [dbo].[FA_HOURS] TO [public]
GO
GRANT SELECT ON  [dbo].[FA_HOURS] TO [public]
GO
GRANT UPDATE ON  [dbo].[FA_HOURS] TO [public]
GO
