CREATE TABLE [dbo].[tts_bs_pnf]
(
[Cliente] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ordenes] [int] NULL,
[Monto] [float] NULL,
[Lag] [int] NULL,
[OrdenesMesa] [int] NULL,
[MontoMesa] [float] NULL,
[LagMesa] [int] NULL,
[OrdenesFact] [int] NULL,
[MontoFact] [float] NULL,
[LagFact] [int] NULL,
[ordenesMesadiez] [float] NULL,
[montoMesadiez] [int] NULL,
[lagMesadiez] [int] NULL,
[ordenesFactdiez] [float] NULL,
[montoFactdiez] [int] NULL,
[lagFactdiez] [int] NULL,
[ordenesMesaveinte] [float] NULL,
[montoMesaveinte] [int] NULL,
[lagMesaveinte] [int] NULL,
[ordenesFactveinte] [float] NULL,
[montoFactveinte] [int] NULL,
[lagFactveinte] [int] NULL,
[ordenesMesatreinta] [float] NULL,
[montoMesatreinta] [int] NULL,
[lagMesatreinta] [int] NULL,
[ordenesFacttreinta] [float] NULL,
[montoFacttreinta] [int] NULL,
[lagFacttreinta] [int] NULL,
[ordenesMesamas] [float] NULL,
[montoMesamas] [int] NULL,
[lagMesamas] [int] NULL,
[ordenesFactmas] [float] NULL,
[montoFactmas] [int] NULL,
[lagFactmas] [int] NULL
) ON [PRIMARY]
GO
