CREATE TABLE [dbo].[tblSigma]
(
[fecha] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[invoice] [int] NULL,
[invstatus] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contador] [int] NULL,
[referencia] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orden] [int] NULL,
[mov_number] [int] NULL,
[unidad] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[operador] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[caja] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[origen] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rep1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rep2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rep3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rep4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rep5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reposicionamiento] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[toneladas] [int] NULL,
[km1] [int] NULL,
[km2] [int] NULL,
[km3] [int] NULL,
[km4] [int] NULL,
[km5] [int] NULL,
[kmRep] [int] NULL,
[kmsTotales] [float] NULL,
[casetas1] [float] NULL,
[casetas2] [float] NULL,
[casetas3] [float] NULL,
[casetas4] [float] NULL,
[casetas5] [float] NULL,
[casetaRep] [float] NULL,
[Casetas] [float] NULL,
[maniobras1] [float] NULL,
[maniobras2] [float] NULL,
[maniobras3] [float] NULL,
[maniobras4] [float] NULL,
[maniobras5] [float] NULL,
[Maniobras] [float] NULL,
[fuel] [float] NULL,
[iva] [float] NULL,
[retencion] [float] NULL
) ON [PRIMARY]
GO
