CREATE TABLE [dbo].[completion_stops]
(
[ord_hdrnumber] [int] NOT NULL,
[stp_number] [int] NOT NULL,
[cmp_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_region1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_region2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_region3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_city] [int] NULL,
[stp_state] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_schdtearliest] [datetime] NULL,
[stp_origschdt] [datetime] NULL,
[stp_arrivaldate] [datetime] NULL,
[stp_departuredate] [datetime] NULL,
[stp_reasonlate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_schdtlatest] [datetime] NULL,
[lgh_number] [int] NULL,
[mfh_number] [int] NULL,
[stp_type] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_paylegpt] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shp_hdrnumber] [int] NULL,
[stp_sequence] [int] NULL,
[stp_region4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_lgh_sequence] [int] NULL,
[trl_id] [char] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_mfh_sequence] [int] NULL,
[stp_event] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_mfh_position] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_lgh_position] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_mfh_status] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_lgh_status] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_ord_mileage] [int] NULL,
[stp_lgh_mileage] [int] NULL,
[stp_mfh_mileage] [int] NULL,
[mov_number] [int] NULL,
[timestamp] [timestamp] NULL,
[stp_loadstatus] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_weight] [float] NULL,
[stp_weightunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_description] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_count] [decimal] (10, 2) NULL,
[stp_countunit] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_comment] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_status] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_reftype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_refnum] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_reasonlate_depart] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_screenmode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[skip_trigger] [tinyint] NULL,
[stp_volume] [float] NULL,
[stp_volumeunit] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_dispatched_sequence] [int] NULL,
[stp_arr_confirmed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_dep_confirmed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_type1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_redeliver] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_osd] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_pudelpref] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_phonenumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_delayhours] [float] NULL,
[stp_ooa_mileage] [float] NULL,
[stp_zipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_OOA_stop] [int] NULL,
[stp_address] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_transfer_stp] [int] NULL,
[stp_phonenumber2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_address2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_contact] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_custpickupdate] [datetime] NULL,
[stp_custdeliverydate] [datetime] NULL,
[stp_podname] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_cmp_close] [int] NULL,
[stp_activitystart_dt] [datetime] NULL,
[stp_activityend_dt] [datetime] NULL,
[stp_departure_status] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_eta] [datetime] NULL,
[stp_etd] [datetime] NULL,
[stp_transfer_type] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_trip_mileage] [int] NULL,
[stp_stl_mileage_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tmp_evt_number] [int] NULL,
[tmp_fgt_number] [int] NULL,
[stp_pallets_in] [int] NULL,
[stp_pallets_out] [int] NULL,
[stp_pallets_received] [int] NULL,
[stp_pallets_shipped] [int] NULL,
[stp_pallets_rejected] [int] NULL,
[psh_number] [int] NULL,
[stp_advreturnempty] [int] NULL,
[stp_country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_loadingmeters] [decimal] (12, 4) NULL,
[stp_loadingmetersunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_cod_amount] [decimal] (8, 2) NULL,
[stp_cod_currency] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_extra_count] [real] NULL,
[stp_extra_weight] [float] NULL,
[stp_alloweddet] [int] NULL,
[stp_detstatus] [int] NULL,
[stp_gfc_arr_radius] [decimal] (7, 2) NULL,
[stp_gfc_arr_radiusunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_gfc_arr_timeout] [int] NULL,
[stp_tmstatus] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_reasonlate_text] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_reasonlate_depart_text] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_est_drv_time] [int] NULL,
[stp_est_activity] [int] NULL,
[nlm_time_diff] [int] NULL,
[stp_lgh_mileage_mtid] [int] NULL,
[stp_count2] [decimal] (10, 2) NULL,
[stp_countunit2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_ord_toll_cost] [money] NULL,
[stp_ord_mileage_mtid] [int] NULL,
[stp_ooa_mileage_mtid] [int] NULL,
[last_updateby] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_updatedate] [datetime] NULL,
[last_updatebydepart] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_updatedatedepart] [datetime] NULL,
[stp_unload_paytype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_completion_odometer] [int] NULL,
[stp_completion_driver1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_completion_driver2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_completion_tractor] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_completion_trailer] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_completion_shift_date] [datetime] NULL,
[stp_completion_shift_id] [int] NULL,
[city_cty_nmstct] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[completion_stops] ADD CONSTRAINT [PK_completion_stops] PRIMARY KEY CLUSTERED ([stp_number]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_completion_stops_lgh_number] ON [dbo].[completion_stops] ([lgh_number]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_completion_stops_ord_hdrnumber] ON [dbo].[completion_stops] ([ord_hdrnumber]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[completion_stops] TO [public]
GO
GRANT INSERT ON  [dbo].[completion_stops] TO [public]
GO
GRANT REFERENCES ON  [dbo].[completion_stops] TO [public]
GO
GRANT SELECT ON  [dbo].[completion_stops] TO [public]
GO
GRANT UPDATE ON  [dbo].[completion_stops] TO [public]
GO
