CREATE TABLE [dbo].[TESTPISAUPLOAD]
(
[idenvio] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rfcvendedora] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[razonsocialremitente] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rfcoperador] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[razonsocialcontratante] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rfccliente] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[razonsocialcliente] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[secuencia] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fechahorallegada] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fechahorasalida] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[claveprodservicio] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[descripcion] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[claveunidad] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[materialpeligroso] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pesoenkg] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[valormercancia] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[moneda] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[numpiezas] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[unidadpeso] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[secuenciaorigen] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[municipio1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[calle1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[estado1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pais1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[colonia1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[codigopostal1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[secuenciadestino] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[municipio2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[calle2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[estado2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pais2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[colonia2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[codigopostal2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[origen] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
