CREATE TABLE [dbo].[carrier411_batch]
(
[cab_batch_number] [int] NOT NULL,
[cas_docket_number] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cab_safety_rating] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_safestat_driver] [decimal] (4, 2) NULL,
[cab_safestat_safety] [decimal] (4, 2) NULL,
[cab_safestat_vehicle] [decimal] (4, 2) NULL,
[cab_authority_broker_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_authority_broker_app_pending] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_authority_broker_revocation_pending] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_authority_common_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_authority_common_app_pending] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_authority_common_revocation_pending] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_authority_contract_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_authority_contract_app_pending] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_authority_contract_revocation_pending] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_insurance_cargo_required] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_insurance_cargo_filed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_insurance_bond_required] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_insurance_bond_filed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_insurance_bipd_required] [int] NULL,
[cab_insurance_bipd_filed] [int] NULL,
[cab_legal_name] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_dba_name] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_business_address] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_business_city] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_business_state] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_business_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_business_country] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_business_phone] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_business_fax] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_rate_date] [datetime] NULL,
[cab_dot_number] [int] NULL,
[cab_411_last_update] [datetime] NULL,
[cab_sms_insp_total] [int] NULL,
[cab_sms_driver_insp_total] [int] NULL,
[cab_sms_driver_oos_insp_total] [int] NULL,
[cab_sms_vehicle_insp_total] [int] NULL,
[cab_sms_vehicle_oos_insp_total] [int] NULL,
[cab_sms_fit_last] [datetime] NULL,
[cab_sms_safe_fit] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_basic_last] [datetime] NULL,
[cab_sms_ins_other_violation] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_ins_other_indicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_unsafe_prcnt] [decimal] (4, 1) NULL,
[cab_sms_unsafe_alert] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_unsafe_violation] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_unsafe_indicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_unsafe_inspect] [int] NULL,
[cab_sms_unsafe_score] [decimal] (5, 2) NULL,
[cab_sms_fatig_prcnt] [decimal] (4, 1) NULL,
[cab_sms_fatig_alert] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_fatig_violation] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_fatig_indicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_fatig_inspect] [int] NULL,
[cab_sms_fatig_score] [decimal] (5, 2) NULL,
[cab_sms_fit_prcnt] [decimal] (4, 1) NULL,
[cab_sms_fit_alert] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_fit_violation] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_fit_indicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_fit_inspect] [int] NULL,
[cab_sms_fit_score] [decimal] (5, 2) NULL,
[cab_sms_cntrl_prcnt] [decimal] (4, 1) NULL,
[cab_sms_cntrl_alert] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_cntrl_violation] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_cntrl_indicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_cntrl_inspect] [int] NULL,
[cab_sms_cntrl_score] [decimal] (5, 2) NULL,
[cab_sms_veh_prcnt] [decimal] (4, 1) NULL,
[cab_sms_veh_alert] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_veh_violation] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_veh_indicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_veh_inspect] [int] NULL,
[cab_sms_veh_score] [decimal] (5, 2) NULL,
[cab_sms_cargo_prcnt] [decimal] (4, 1) NULL,
[cab_sms_cargo_alert] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_cargo_violation] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_cargo_indicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cab_sms_cargo_inspect] [int] NULL,
[cab_sms_cargo_score] [decimal] (5, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[carrier411_batch] ADD CONSTRAINT [PK__carrier411_batch__196C070A] PRIMARY KEY CLUSTERED ([cab_batch_number], [cas_docket_number]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[carrier411_batch] TO [public]
GO
GRANT INSERT ON  [dbo].[carrier411_batch] TO [public]
GO
GRANT REFERENCES ON  [dbo].[carrier411_batch] TO [public]
GO
GRANT SELECT ON  [dbo].[carrier411_batch] TO [public]
GO
GRANT UPDATE ON  [dbo].[carrier411_batch] TO [public]
GO
