CREATE TABLE [dbo].[AccidentesregistroCems]
(
[ID] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FECHA Y HORA] [datetime] NOT NULL,
[ID_OPERADOR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOMBRE DEL OPERADOR] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUMERO CELULAR DEL OPERADOR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UNIDAD TRACTO CAMION] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLACAS TRACTO CAMION] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SERIE TRACTO CAMION] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMOLQUE 1] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLACAS REMOLQUE 1] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SERIE REMOLQUE 1] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOLLY] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SERIE DOLLY] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REMOLQUE 2] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLACAS REMOLQUE 2] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SERIE REMOLQUE 2] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORDEN DE TRABAJO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLIENTE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIRECCION DONDE FUE EL SINIESTRO] [char] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COORDENADAS] [varchar] (61) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[URLGoogleMaps] [varchar] (88) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
