CREATE TABLE [dbo].[country]
(
[code] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[name] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[postcode_routing] [tinyint] NOT NULL CONSTRAINT [DF_country_postcode_routing] DEFAULT (5),
[postcode_billing] [tinyint] NOT NULL CONSTRAINT [DF_country_postcode_billing] DEFAULT (5),
[timezone_offset] [smallint] NULL CONSTRAINT [DF_country_timezone_offset] DEFAULT (0),
[VAT_country] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sunday] [tinyint] NOT NULL CONSTRAINT [DF_country_sunday] DEFAULT (0),
[sunday_open_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_sunday_open_shipping1] DEFAULT ('0000'),
[sunday_close_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_sunday_close_shipping1] DEFAULT ('0000'),
[sunday_open_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_sunday_open_receiving1] DEFAULT ('0000'),
[sunday_close_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_sunday_close_receiving1] DEFAULT ('0000'),
[sunday_open_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_sunday_open_shipping2] DEFAULT ('0000'),
[sunday_close_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_sunday_close_shipping2] DEFAULT ('0000'),
[sunday_open_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_sunday_open_receiving2] DEFAULT ('0000'),
[sunday_close_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_sunday_close_receiving2] DEFAULT ('0000'),
[monday] [tinyint] NOT NULL CONSTRAINT [DF_country_monday] DEFAULT (1),
[monday_open_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_monday_open_shipping1] DEFAULT ('0800'),
[monday_close_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_monday_close_shipping1] DEFAULT ('1200'),
[monday_open_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_monday_open_receiving1] DEFAULT ('0800'),
[monday_close_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_monday_close_receiving1] DEFAULT ('1200'),
[monday_open_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_monday_open_shipping2] DEFAULT ('1300'),
[monday_close_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_monday_close_shipping2] DEFAULT ('1700'),
[monday_open_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_monday_open_receiving2] DEFAULT ('1300'),
[monday_close_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_monday_close_receiving2] DEFAULT ('1700'),
[tuesday] [tinyint] NOT NULL CONSTRAINT [DF_country_tuesday] DEFAULT (1),
[tuesday_open_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_tuesday_open_shipping1] DEFAULT ('0800'),
[tuesday_close_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_tuesday_close_shipping1] DEFAULT ('1200'),
[tuesday_open_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_tuesday_open_receiving1] DEFAULT ('0800'),
[tuesday_close_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_tuesday_close_receiving1] DEFAULT ('1200'),
[tuesday_open_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_tuesday_open_shipping2] DEFAULT ('1300'),
[tuesday_close_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_tuesday_close_shipping2] DEFAULT ('1700'),
[tuesday_open_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_tuesday_open_receiving2] DEFAULT ('1300'),
[tuesday_close_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_tuesday_close_receiving2] DEFAULT ('1700'),
[wednesday] [tinyint] NOT NULL CONSTRAINT [DF_country_wednesday] DEFAULT (1),
[wednesday_open_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_wednesday_open_shipping1] DEFAULT ('0800'),
[wednesday_close_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_wednesday_close_shipping1] DEFAULT ('1200'),
[wednesday_open_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_wednesday_open_receiving1] DEFAULT ('0800'),
[wednesday_close_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_wednesday_close_receiving1] DEFAULT ('1200'),
[wednesday_open_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_wednesday_open_shipping2] DEFAULT ('1300'),
[wednesday_close_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_wednesday_close_shipping2] DEFAULT ('1700'),
[wednesday_open_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_wednesday_open_receiving2] DEFAULT ('1300'),
[wednesday_close_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_wednesday_close_receiving2] DEFAULT ('1700'),
[thursday] [tinyint] NOT NULL CONSTRAINT [DF_country_thursday] DEFAULT (1),
[thursday_open_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_thursday_open_shipping1] DEFAULT ('0800'),
[thursday_close_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_thursday_close_shipping1] DEFAULT ('1200'),
[thursday_open_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_thursday_open_receiving1] DEFAULT ('0800'),
[thursday_close_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_thursday_close_receiving1] DEFAULT ('1200'),
[thursday_open_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_thursday_open_shipping2] DEFAULT ('1300'),
[thursday_close_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_thursday_close_shipping2] DEFAULT ('1700'),
[thursday_open_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_thursday_open_receiving2] DEFAULT ('1300'),
[thursday_close_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_thursday_close_receiving2] DEFAULT ('1700'),
[friday] [tinyint] NOT NULL CONSTRAINT [DF_country_friday] DEFAULT (1),
[friday_open_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_friday_open_shipping1] DEFAULT ('0800'),
[friday_close_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_friday_close_shipping1] DEFAULT ('1200'),
[friday_open_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_friday_open_receiving1] DEFAULT ('0800'),
[friday_close_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_friday_close_receiving1] DEFAULT ('1200'),
[friday_open_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_friday_open_shipping2] DEFAULT ('1300'),
[friday_close_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_friday_close_shipping2] DEFAULT ('1700'),
[friday_open_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_friday_open_receiving2] DEFAULT ('1300'),
[friday_close_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_friday_close_receiving2] DEFAULT ('1700'),
[saturday] [tinyint] NOT NULL CONSTRAINT [DF_country_saturday] DEFAULT (0),
[saturday_open_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_saturday_open_shipping1] DEFAULT ('0000'),
[saturday_close_shipping1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_saturday_close_shipping1] DEFAULT ('0000'),
[saturday_open_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_saturday_open_receiving1] DEFAULT ('0000'),
[saturday_close_receiving1] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_saturday_close_receiving1] DEFAULT ('0000'),
[saturday_open_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_saturday_open_shipping2] DEFAULT ('0000'),
[saturday_close_shipping2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_saturday_close_shipping2] DEFAULT ('0000'),
[saturday_open_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_saturday_open_receiving2] DEFAULT ('0000'),
[saturday_close_receiving2] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_saturday_close_receiving2] DEFAULT ('0000'),
[currency] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_country_currency] DEFAULT ('US$'),
[currencysymbol] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_country_currencysymbol] DEFAULT ('$'),
[decimal_indicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_country_decimal_indicator] DEFAULT ('.'),
[thousand_indicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_country_thousand_indicator] DEFAULT (','),
[symbol_placement] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_country_symbol_placement] DEFAULT ('F'),
[isocode] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdby] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdate] [datetime] NULL,
[updatedby] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[updatedate] [datetime] NULL,
[def_country] [tinyint] NOT NULL CONSTRAINT [DF_country_def_country] DEFAULT (0),
[eu_country] [tinyint] NOT NULL CONSTRAINT [DF_country_eu_country] DEFAULT (0),
[doc_language] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_country_doc_language] DEFAULT ('English'),
[min_postcodelen] [smallint] NULL CONSTRAINT [DF_country_min_postcodelen] DEFAULT (5),
[max_postcodelen] [smallint] NULL CONSTRAINT [DF_country_max_postcodelen] DEFAULT (10),
[customs_countrycode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[decimal_places] [smallint] NOT NULL CONSTRAINT [DF_country_decimal_places] DEFAULT (2),
[phone_format] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[country] ADD CONSTRAINT [pk_country] PRIMARY KEY CLUSTERED ([code]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[country] TO [public]
GO
GRANT INSERT ON  [dbo].[country] TO [public]
GO
GRANT REFERENCES ON  [dbo].[country] TO [public]
GO
GRANT SELECT ON  [dbo].[country] TO [public]
GO
GRANT UPDATE ON  [dbo].[country] TO [public]
GO
