CREATE TABLE [dbo].[TMT_ASSETTRANSFERHISTORY]
(
[IDENT] [int] NOT NULL IDENTITY(1, 1),
[LGH_NUMBER] [int] NULL,
[TRACTOR] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DRIVER] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRAILER] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASGN_DATE] [datetime] NULL,
[ASGN_ENDDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TMT_ASSETTRANSFERHISTORY] ADD CONSTRAINT [PK_TMT_ASSETTRANSFERHISTORY] PRIMARY KEY CLUSTERED ([IDENT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_TMT_ASSETTRANSFERHISTORY_ASGNDATE] ON [dbo].[TMT_ASSETTRANSFERHISTORY] ([ASGN_DATE]) INCLUDE ([LGH_NUMBER], [TRACTOR], [DRIVER], [TRAILER], [ASGN_ENDDATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [LGH_NUMBER_IND] ON [dbo].[TMT_ASSETTRANSFERHISTORY] ([LGH_NUMBER]) ON [PRIMARY]
GO
