CREATE TABLE [dbo].[KaneOrders]
(
[ImpId] [int] NOT NULL IDENTITY(1, 1),
[KaneId] [int] NOT NULL,
[AllAuthors] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AllReaders] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ActualDeliveryDate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraTextFields1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraTextFields2] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraTextFields3] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraTextFields4] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraTextFields5] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Carrier] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OrderNumber] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C2CONS] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C2CONS2] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Cost] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C2CRDT] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Cube] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExpectedDeliveryDate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Mileage] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DocumentNumber] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerAddressNum1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerAddressNum2] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerCity] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerGroupID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerState] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerZip] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EarliestShipDate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FinalDestAddNum1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FinalDestAddNum2] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FinalDestCity] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FinalDestID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FinalDestName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FinalDestState] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FinalDestZip] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraFlagFields1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraFlagFields2] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraFlagFields3] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraFlagFields4] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraFlagFields5] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LatestShipDate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C2LHADATE] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LastStatus] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C2LTL] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StorerName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StorerID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraNumberFields1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraNumberFields2] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraNumberFields3] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraNumberFields4] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtraNumberFields5] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OrderDate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Pallets] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C2PDADATE] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ScheduledPickupDate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DuplicateRow] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FirstDistCity] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FirstDistID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FirstDistName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FirstDistState] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FirstDistZip] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PhoneNumber] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PONumber] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Quantity] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RoutingInstructions] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SecondDistCity] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SecondDistID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SecondDistName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SecondDistState] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SecondDistZip] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C2SEQNO] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SpecialInstructions] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SOrderNumber] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Stackable] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StopNumber] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TripNumber] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C2TSTP] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Weight] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CHANGEC2CONS] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CreatedBy] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DateCreated] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DocReaders] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Form] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LoadType] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[History] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NHISTORY1] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TmpCarrier] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TmpDstAd1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TmpDstAd2] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TmpDstCity] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TmpDstDeliveryDate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TmpDstID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TmpDstName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TmpDstState] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TMPDSTZIP] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TMPMILEAGE] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TmpStopNumber] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TmpTripNumber] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KaneOrders] ADD CONSTRAINT [PK_KaneOrders] PRIMARY KEY CLUSTERED ([ImpId]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KaneOrders] ADD CONSTRAINT [FK_KaneOrders_KaneBatch] FOREIGN KEY ([KaneId]) REFERENCES [dbo].[KaneBatch] ([KaneId])
GO
GRANT DELETE ON  [dbo].[KaneOrders] TO [public]
GO
GRANT INSERT ON  [dbo].[KaneOrders] TO [public]
GO
GRANT SELECT ON  [dbo].[KaneOrders] TO [public]
GO
GRANT UPDATE ON  [dbo].[KaneOrders] TO [public]
GO
