CREATE TABLE [dbo].[dispatchview]
(
[dv_id] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_driver] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_tractor] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_city] [int] NOT NULL,
[dv_states] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_region1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_region2] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_region3] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_region4] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_teamleader] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_fleet] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_division] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_domicile] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_company] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_terminal] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_mpp_type1] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_mpp_type2] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_mpp_type3] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_mpp_type4] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_trc_type1] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_trc_type2] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_trc_type3] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_trc_type4] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_lgh_type1] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_lgh_type2] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_lgh_type3] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_lgh_type4] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_hours_back] [smallint] NOT NULL,
[dv_hours_out] [smallint] NOT NULL,
[dv_cmp_id] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[timestamp] [timestamp] NOT NULL,
[dv_type] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dv_trl_type1] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_trl_type2] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_trl_type3] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_trl_type4] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_lgh_status] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_lgh_instatus] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_trl_status] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_bookedby] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dest_city] [int] NULL,
[dv_dest_states] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dest_cmp_id] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dest_region1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dest_region2] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dest_region3] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dest_region4] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_drvplantype1] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_drvplantype2] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_drvplantype3] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_drvplantype4] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_includedrvplan] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_type1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_type2] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_totalmiles_min] [int] NULL,
[ord_totalmiles_max] [int] NULL,
[dv_event] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_next_event] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_next_cmp_id] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_next_city] [int] NULL,
[dv_next_state] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_next_region1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_next_region2] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_next_region3] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_next_region4] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_last_event] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_tm_status] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_filter] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_sort] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_config] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_config_id] [int] NULL,
[dv_carrier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_view_type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_trc_accessories] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_trl_accessories] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_drv_qualifications] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_drv_status] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_billto] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_hzd_cmd_classes] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_includeplanrec] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_plandays] [tinyint] NULL,
[dv_plandetail] [tinyint] NOT NULL CONSTRAINT [df_dv_plandetail] DEFAULT (0),
[dv_origin_svc_zone] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_origin_svc_area] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_origin_svc_center] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_origin_svc_region] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dest_svc_zone] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dest_svc_area] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dest_svc_center] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dest_svc_region] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_orderedby] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_route] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_booked_revtype1] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_permit_status] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_current_avl_date] [datetime] NULL,
[dv_latest_avl_date] [datetime] NULL,
[dv_car_handling] [tinyint] NULL,
[dv_car_type1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_car_type2] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_car_type3] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_car_type4] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_booking_terminal] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_cmp_othertype1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__dispatchv__dv_cm__7E486D19] DEFAULT ('UNK'),
[dv_dest_cmp_othertype1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__dispatchv__dv_de__7F3C9152] DEFAULT ('UNK'),
[dv_next_cmp_othertype1] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__dispatchv__dv_ne__0030B58B] DEFAULT ('UNK'),
[lgh_type3] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_type4] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dw_criteria1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dw_criteria2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dw_criteria3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_dw_criteria4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_order_refnum] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_trailer1_id] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_trailer2_id] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_order_number] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_shipper] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_consignee] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_reference1_table] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_reference1_type] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_reference1_heading] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_reference2_table] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_reference2_type] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_reference2_heading] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_previous_segment_status] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_trl_equip_type] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_trc_teamleader] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_days_start_offset] [smallint] NULL,
[dv_days_end_offset] [smallint] NULL,
[dv_date_range_mode] [smallint] NULL,
[dv_cmp_othertype1_billto] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_cmp_othertype2_billto] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_origin_include_stop_events] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dv_direct_route_status1] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[dispatchview] ADD CONSTRAINT [AutoPK_dispatchview] PRIMARY KEY CLUSTERED ([dv_id], [dv_type]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [uk_id] ON [dbo].[dispatchview] ([dv_id], [dv_type]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[dispatchview] TO [public]
GO
GRANT INSERT ON  [dbo].[dispatchview] TO [public]
GO
GRANT REFERENCES ON  [dbo].[dispatchview] TO [public]
GO
GRANT SELECT ON  [dbo].[dispatchview] TO [public]
GO
GRANT UPDATE ON  [dbo].[dispatchview] TO [public]
GO
