CREATE TABLE [dbo].[TASK_TEMPLATE_QUESTIONS]
(
[TTQ_ID] [int] NOT NULL IDENTITY(1, 1),
[TTQ_QUESTION] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TTQ_DEFAULT_ANSWER] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TTQ_DEFAULT_ANSWER_ABBR] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TTQ_LABELDEFINITION] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TTQ_ANSWER_REQUIRED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TTQ_WHEN_TO_PROMPT] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TASK_TEMPLATE_ID] [int] NULL,
[TTQ_CREATED_DATE] [datetime] NULL,
[TTQ_CREATED_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TTQ_MODIFIED_DATE] [datetime] NULL,
[TTQ_MODIFIED_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[TASK_TEMPLATE_QUESTIONS] TO [public]
GO
GRANT INSERT ON  [dbo].[TASK_TEMPLATE_QUESTIONS] TO [public]
GO
GRANT SELECT ON  [dbo].[TASK_TEMPLATE_QUESTIONS] TO [public]
GO
GRANT UPDATE ON  [dbo].[TASK_TEMPLATE_QUESTIONS] TO [public]
GO
