CREATE TABLE [dbo].[clientes_nuevos]
(
[cmp_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_address1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_address2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_city] [int] NULL,
[cmp_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_primaryphone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_secondaryphone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_faxphone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_shipper] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_consingee] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_billto] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_othertype1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_othertype2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_artype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_invoicetype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_revtype1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_revtype2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_revtype3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_revtype4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_currency] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_active] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_opens_mo] [int] NULL,
[cmp_closes_mo] [int] NULL,
[cmp_creditlimit] [money] NULL,
[cmp_creditavail] [money] NULL,
[cmp_mileagetable] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mastercompany] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_terms] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_defaultbillto] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_edi214] [int] NULL,
[cmp_edi210] [int] NULL,
[cmp_edi204] [int] NULL,
[cmp_state] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_region1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_region2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_region3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_region4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_addnewshipper] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_opensun] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_openmon] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_opentue] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_openwed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_openthu] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_openfri] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_opensat] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_payfrom] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mapfile] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_contact] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_directions] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[timestamp] [timestamp] NULL,
[cty_nmstct] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_misc1] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_misc2] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_misc3] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_misc4] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mbdays] [smallint] NULL,
[cmp_lastmb] [datetime] NULL,
[cmp_invcopies] [smallint] NULL,
[cmp_transfertype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_altid] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_updatedby] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_updateddate] [datetime] NULL,
[cmp_defaultpriority] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_invoiceto] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_invformat] [int] NULL,
[cmp_invprintto] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_creditavail_update] [datetime] NULL,
[cmd_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[junknotinuse] [datetime] NULL,
[cmp_agedinvflag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_max_dunnage] [int] NULL,
[cmp_acc_balance] [money] NULL,
[cmp_acc_dt] [datetime] NULL,
[cmp_opens_tu] [int] NULL,
[cmp_closes_tu] [int] NULL,
[cmp_opens_we] [int] NULL,
[cmp_closes_we] [int] NULL,
[cmp_opens_th] [int] NULL,
[cmp_closes_th] [int] NULL,
[cmp_opens_fr] [int] NULL,
[cmp_closes_fr] [int] NULL,
[cmp_opens_sa] [int] NULL,
[cmp_closes_sa] [int] NULL,
[cmp_opens_su] [int] NULL,
[cmp_closes_su] [int] NULL,
[cmp_subcompany] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_createdate] [datetime] NULL,
[cmp_taxtable1] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_taxtable2] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_taxtable3] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_taxtable4] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_quickentry] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_slack_time] [int] NULL,
[cmp_mailto_name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mailto_address1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mailto_address2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mailto_city] [int] NULL,
[cmp_mailto_state] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mailto_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mailto_cty_nmstct] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_latseconds] [decimal] (11, 3) NULL,
[cmp_longseconds] [decimal] (11, 3) NULL,
[cmp_mailto_crterm1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mailto_crterm2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mailto_crterm3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mbformat] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mbgroup] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_centroidcity] [int] NULL,
[cmp_centroidctynmstct] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_centroidzip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_ooa_mileage] [float] NULL,
[cmp_ooa_mileage_stops] [float] NULL,
[cmp_mapaddress] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_usestreetaddr] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_primaryphoneext] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_secondaryphoneext] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_palletcount] [int] NULL,
[cmp_fueltableid] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[grp_id] [int] NULL,
[cmp_parent] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_address3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_slacktime_late] [int] NULL,
[cmp_geoloc] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_geoloc_forsearch] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_min_charge] [money] NULL,
[cmp_service_location] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_psoverride] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_MailtToForLinehaulFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mailtoTermsMatchFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_max_weight] [money] NULL,
[cmp_max_weightunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_ivformat] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_ivgroup] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_taxid] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_gp_class] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[doc_language] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_image_routing1] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_image_routing2] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_image_routing3] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_port] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_depot] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_addcurrencysurcharge] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ltsl_auto_add_pul_flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ltsl_default_pickup_event] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ltsl_default_delivery_event] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_PUPTimeAllowance] [int] NULL,
[cmp_DRPTimeAllowance] [int] NULL,
[cmp_maxdetmins] [int] NULL,
[cmp_detcontacts] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_allowdetcharges] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_latlongverifications] [int] NULL,
[cmp_maptuit_customnote] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[external_id] [int] NULL,
[external_type] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_currencysurchargebase] [money] NULL,
[cmp_TrlConfiguration] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_service_location_qual] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_service_location_own] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_service_location_rating] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_MileSearchLevel] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_det_start] [int] NULL,
[cmp_det_apply_if_late] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_reftype_unique] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_PUPalert] [int] NULL,
[cmp_DRPalert] [int] NULL,
[cmp_det_apply_if_early] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_senddetalert] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_leadtime] [int] NULL,
[cmp_railramp] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_athome_location] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_thirdpartytype1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_thirdpartytype2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_aceidtype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_aceid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_TMlatseconds] [int] NULL,
[cmp_TMlongseconds] [int] NULL,
[cmp_TMdistancetolatlong] [decimal] (9, 1) NULL,
[cmp_TMlatlongdate] [datetime] NULL,
[cmp_dimoverride] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_supplier] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_overrideapplyhighestrate] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_rbd_FlatRateOption] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_MinLHAdj] [money] NULL,
[cmp_RateBy] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_rbd_highrateoption] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_last_call_date] [datetime] NULL,
[cmp_last_call_note] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_last_call_user] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_next_call_date] [datetime] NULL,
[cmp_SchdEarliestDateOverride] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_bookingterminal] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_ICaccessorial] [int] NOT NULL,
[cmp_ICaccessorialfactor] [decimal] (8, 4) NOT NULL,
[cmp_GeoCodeRequested] [datetime] NULL,
[cmp_det_increment] [int] NULL,
[cmp_det_rounding] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_det_threshold] [int] NULL,
[cmp_det_override] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_stop_events] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_freestops] [int] NULL,
[cmp_stopevents_pay] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_freestops_pay] [int] NULL,
[cmp_MonObsHolFlag] [smallint] NULL,
[cmp_TueObsHolFlag] [smallint] NULL,
[cmp_WedObsHolFlag] [smallint] NULL,
[cmp_ThuObsHolFlag] [smallint] NULL,
[cmp_FriObsHolFlag] [smallint] NULL,
[cmp_SatObsHolFlag] [smallint] NULL,
[cmp_SunObsHolFlag] [smallint] NULL,
[cmp_FromHrDateAdj] [smallint] NULL,
[holiday_group] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_Payment_terms] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_blended_min_qty] [decimal] (19, 4) NULL,
[cmp_minchargeoption] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_BelongsTo] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_acc_gvt_rpt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_acc_id] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_refnum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_statemiletype1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_statemiletype2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_splitbillonrefnbr] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_inv_toll_detail] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_refnum_gpinvxfer] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_avgstopminutes] [int] NULL,
[cmp_accountof] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_house_number] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_street_name] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mailto_country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_billto_eligible_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_stp_type2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_stp_type3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_crmtype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_inv_controlling_cmp_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_inv_open_ivr_forward_number] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_inv_closed_ivr_forward_number] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_inv_numeric_id] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_firm_appt_value] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_CreditHoldStatus] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_CreditHoldComment] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_InvSrvReleaseOnly] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_InvSrvMode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_ForecastBatch] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_SalesHistoryBatch] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_ForecasterLastReadingDate] [datetime] NULL,
[cmp_ForecasterLastRunDate] [datetime] NULL,
[cmp_ivr_pin] [int] NULL,
[cmp_dedicated_bill] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_dedicated_usedate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_dedicated_datecycle] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_sourcing_include_trans] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_sourcing_include_taxes] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_sourcing_max_distance] [int] NOT NULL,
[cmp_sourcing_quote_type] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_sourcing_quotebillto] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_sourcing_quotetransbillto] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[rowsec_rsrv_id] [int] NULL,
[cmp_defaultstptype1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_hiddenid] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rhh_id] [int] NULL,
[cmp_invoiceby] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_volunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_wgtunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_rateallocation] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_invoiceimageflag] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_TollMethod] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_AvgFuelPriceDateOverride] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_autobill] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_autobill_terms] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_refnum_gpdocdescxfer] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_timezone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_misc5] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_misc6] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_misc7] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_misc8] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_useboldates] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_sendarrivalalert] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_senddeparturealert] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_cmdvalue] [money] NULL,
[cmp_mb_breaktype] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mb_breakvalue] [int] NULL,
[cmp_ar_transfer_nonbundled] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_defaultcons] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_pophubmilesflag] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_servicedrp_rpt] [int] NULL,
[cmp_servicepup_rpt] [int] NULL,
[cmp_servicebillto_rpt] [int] NULL,
[cmp_invoice_when] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mbdayofmonth] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_RateEachPickDrop] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_inv_audit] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_othertype3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_othertype4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_billing_rating_engine] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_app_eqcodes] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_dbh_custinvnum_prefix] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_dbh_custinvnum_startnum] [int] NULL,
[cmp_dbh_custinvnum_digits] [tinyint] NULL,
[cmp_TaxGroup] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_UseDips] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_billto_spotquote] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_custequipprefix] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AppianDistanceFldData] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_allow_tm_update] [tinyint] NULL,
[cmp_isbond] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_doublesdrop_location] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_primaryflagrequired] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_terminal] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_ctw_conv] [float] NULL,
[cmp_ctw_break] [float] NULL,
[cmp_wtc_conv] [float] NULL,
[cmp_ctw_weightunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_ctw_volumeunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_yard_type] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_btm_toll_mileagetable] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_etawcbillto] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_freedays] [int] NOT NULL,
[trl_maxcharge] [money] NULL,
[cmp_DRBack] [int] NULL,
[cmp_DROut] [int] NULL,
[fecha_insert] [datetime] NULL
) ON [PRIMARY]
GO
