CREATE TABLE [dbo].[TASK_TEMPLATE]
(
[TASK_TEMPLATE_ID] [int] NOT NULL IDENTITY(1, 1),
[NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASSIGNED_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIORITY] [int] NULL,
[LEAD_TIME] [int] NOT NULL,
[ACTIVE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CREATED_DATE] [datetime] NOT NULL,
[CREATED_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MODIFIED_DATE] [datetime] NOT NULL,
[MODIFIED_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[USER_DEFINED_TYPE1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENERATION_RULE] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_RULE] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NAME_RULE] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEMPLATE_GROUP_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARENT_TASK_TEMPLATE_ID] [int] NULL,
[NAME_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASSIGNED_USER_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DUE_DATE_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LEAD_TIME_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIORITY_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVE_FLAG_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUS_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE1_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE2_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE3_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE4_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PENDING_CHANGES_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENERATION_RULE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROMPT_ADD_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROMPT_EDIT_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROMPT_DELETE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROMPT_HOLD_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENERATION_RULE2] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASSIGNED_USER_RULE] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORKFLOW_ID] [int] NULL,
[WORKFLOW_TEMPLATE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POST_PROCESS] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASK_TEMPLATE] ADD CONSTRAINT [PK__TASK_TEMPLATE__01B6777B] PRIMARY KEY CLUSTERED ([TASK_TEMPLATE_ID]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[TASK_TEMPLATE] TO [public]
GO
GRANT INSERT ON  [dbo].[TASK_TEMPLATE] TO [public]
GO
GRANT REFERENCES ON  [dbo].[TASK_TEMPLATE] TO [public]
GO
GRANT SELECT ON  [dbo].[TASK_TEMPLATE] TO [public]
GO
GRANT UPDATE ON  [dbo].[TASK_TEMPLATE] TO [public]
GO
