CREATE TABLE [dbo].[MCMESSAGE]
(
[MCM_ID] [int] NOT NULL,
[MCM_SEQUENCE] [smallint] NOT NULL,
[MCM_REQUESTTYPE] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MCM_STATUS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MCM_ORIGINATORIDTYPE] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MCM_ORIGINATORID] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MCM_ORISERVICE] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_ORIADDRESS] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_RECIPIENTIDTYPE] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_RECIPIENTID] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_RECIPSERVICE] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_RECIPADDRESS] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_CREATEDATE] [datetime] NOT NULL,
[MCM_CREATETIME] [datetime] NOT NULL,
[MCM_SENTDATE] [datetime] NULL,
[MCM_SENTTIME] [datetime] NULL,
[MCM_PRIORITY] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_RETURNRECEIPT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_SUBJECT] [char] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_MESSAGETEXT] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_MACRONUM] [smallint] NULL,
[MCM_MACROVER] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_SERVICEMSGID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_HANDLING] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_STATUSMESSAGE] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_REPLYTOMSGID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_DIRECTION] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_SITINGDATE] [datetime] NULL,
[MCM_SITINGTIME] [datetime] NULL,
[MCM_LATITUDE] [int] NULL,
[MCM_LONGITUDE] [int] NULL,
[MCM_EXTSENSORALARM] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_VEHICLEIGNITION] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_PROXIMITY] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_MILESFROM] [float] NULL,
[MCM_DIRECTIONFROM] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_CITY] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_STATE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_VALIDITY] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_MTAVAILABLE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_TRACTOR] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_EXCEPTIONS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOV_NUMBER] [int] NULL,
[MCM_SYSTEMPROCESSED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LGH_NUMBER] [int] NULL,
[MCM_DRIVER1] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_UPDATEDBY] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCM_UPDATEDATE] [datetime] NULL,
[MCM_UPDATETIME] [datetime] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO

/****** Object:  Trigger dbo.dt_mcmessage    Script Date: 6/1/99 11:55:17 AM ******/
/****** Object:  Trigger dbo.dt_mcmessage    Script Date: 12/10/97 5:50:30 PM ******/
create TRIGGER [dbo].[dt_mcmessage] ON [dbo].[MCMESSAGE] FOR DELETE AS 
                                       

DELETE MCEXCEPTION
FROM deleted, MCEXCEPTION
WHERE deleted.MCM_ID = MCEXCEPTION.MCM_ID



GO
CREATE NONCLUSTERED INDEX [dk_createdate] ON [dbo].[MCMESSAGE] ([MCM_CREATEDATE]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [uk_idseq] ON [dbo].[MCMESSAGE] ([MCM_ID], [MCM_SEQUENCE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_servicemsgid] ON [dbo].[MCMESSAGE] ([MCM_SERVICEMSGID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_statrecip] ON [dbo].[MCMESSAGE] ([MCM_STATUS], [MCM_RECIPIENTIDTYPE], [MCM_RECIPIENTID], [MCM_CREATEDATE]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[MCMESSAGE] TO [public]
GO
GRANT INSERT ON  [dbo].[MCMESSAGE] TO [public]
GO
GRANT REFERENCES ON  [dbo].[MCMESSAGE] TO [public]
GO
GRANT SELECT ON  [dbo].[MCMESSAGE] TO [public]
GO
GRANT UPDATE ON  [dbo].[MCMESSAGE] TO [public]
GO
