CREATE TABLE [dbo].[TASK_GENERATION_TRIGGER]
(
[TASK_GENERATION_TRIGGER_ID] [int] NOT NULL IDENTITY(1, 1),
[TRIGGER_EXPRESSION] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GENERATION_ACTION] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROCESSING_ORDER] [int] NOT NULL,
[CREATE_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CREATE_DATETIME] [datetime] NOT NULL,
[MODIFIED_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MODIFIED_DATETIME] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASK_GENERATION_TRIGGER] ADD CONSTRAINT [PK__TASK_GENERATION___782D0D41] PRIMARY KEY CLUSTERED ([TASK_GENERATION_TRIGGER_ID]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[TASK_GENERATION_TRIGGER] TO [public]
GO
GRANT INSERT ON  [dbo].[TASK_GENERATION_TRIGGER] TO [public]
GO
GRANT REFERENCES ON  [dbo].[TASK_GENERATION_TRIGGER] TO [public]
GO
GRANT SELECT ON  [dbo].[TASK_GENERATION_TRIGGER] TO [public]
GO
GRANT UPDATE ON  [dbo].[TASK_GENERATION_TRIGGER] TO [public]
GO
