CREATE TABLE [dbo].[ESTATUSERCOMPANIES]
(
[login] [varchar] (132) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[cmp_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ord_number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESTATUSERCOMPANIES] ADD CONSTRAINT [PK_estatlusercomp] PRIMARY KEY NONCLUSTERED ([login], [cmp_id]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[ESTATUSERCOMPANIES] TO [public]
GO
GRANT INSERT ON  [dbo].[ESTATUSERCOMPANIES] TO [public]
GO
GRANT SELECT ON  [dbo].[ESTATUSERCOMPANIES] TO [public]
GO
GRANT UPDATE ON  [dbo].[ESTATUSERCOMPANIES] TO [public]
GO
