CREATE TABLE [dbo].[tck_transactional_data_log]
(
[tck_reply_code] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_transaction_code] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_request_class] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_company_number] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_pin] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_request_date] [datetime] NULL,
[tck_record_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_issue_date] [datetime] NULL,
[tck_site_number] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_driver_name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_transaction_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_verification_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_transaction_fee] [money] NULL,
[tck_draft_number] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_invoice_amount] [money] NULL,
[tck_invoice_total] [money] NULL,
[tck_exchange_rate] [money] NULL,
[tck_currency] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_authorization_code] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_site_group_number] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_account_number] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_card_number] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_card_group_number] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_unit_truck_number] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_driver_id] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_trailer_number] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_was_card_swiped] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_aba] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_expiration_date] [datetime] NULL,
[tck_device_type] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_error_number] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_device_serial_number] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_driver_cdl] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_trip_number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_po_number] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_invoice_number] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_odometer] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_previous_odometer_reading] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_fee_paid_by_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_site_type] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_location] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_pay_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_fuel_code1] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_fuel_volume1] [money] NULL,
[tck_fuel_amount1] [money] NULL,
[tck_fuel_ppu1] [money] NULL,
[tck_fuel_code2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_fuel_volume2] [money] NULL,
[tck_fuel_amount2] [money] NULL,
[tck_fuel_ppu2] [money] NULL,
[tck_non_highway_fuel_code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_non_highway_fuel_volume] [money] NULL,
[tck_non_highway_amount] [money] NULL,
[tck_non_highway_ppu] [money] NULL,
[tck_oil_quantity] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_oil_amount] [money] NULL,
[tck_other_product1_code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_other_product1_amount] [money] NULL,
[tck_other_product2_code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_other_product2_amount] [money] NULL,
[tck_cash_advance_amount] [money] NULL,
[tck_dash_cash_amount] [money] NULL,
[tck_pay_chek_amount] [money] NULL,
[tck_transaction_payee] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_local_tax1] [money] NULL,
[tck_local_tax2] [money] NULL,
[tck_sales_tax] [money] NULL,
[tck_truck_stop_transaction_fee] [money] NULL,
[tck_fuel_discount_amount] [money] NULL,
[tck_fuel_discount_type] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_fuel_discount_value] [money] NULL,
[tck_override_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_backout_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_backout_date] [datetime] NULL,
[tck_site_pay_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_auth_person_initials] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_affiliate_number1] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_affiliate_number2] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_affiliate_number3] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_affiliate_billing] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_affiliate_control] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_unit_of_measure] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_site_invoice_amount_before_the_discount] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_express_code_number] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_amount_code] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_remaining_balance] [money] NULL,
[tck_original_express_code_amount] [money] NULL,
[tck_adjustment_type] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_adjustment_amount] [money] NULL,
[tck_adjustment_user_id] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_adjustment_notes] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_message_text] [varchar] (78) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tck_control_key] [varchar] (39) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[timestamp] [datetime] NULL,
[tck_customer_card_number] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[tck_transactional_data_log] TO [public]
GO
GRANT INSERT ON  [dbo].[tck_transactional_data_log] TO [public]
GO
GRANT REFERENCES ON  [dbo].[tck_transactional_data_log] TO [public]
GO
GRANT SELECT ON  [dbo].[tck_transactional_data_log] TO [public]
GO
GRANT UPDATE ON  [dbo].[tck_transactional_data_log] TO [public]
GO
