CREATE TABLE [dbo].[TOrder]
(
[lgh_number] [int] NOT NULL,
[mov_number] [int] NULL,
[lgh_driver1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_tractor] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_carrier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_number] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ord_remark] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_company] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ord_customer] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_bookdate] [datetime] NULL,
[ord_bookedby] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_status] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_originpoint] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_destpoint] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_origincity] [int] NULL,
[ord_destcity] [int] NULL,
[ord_originstate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_deststate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_supplier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_billto] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_startdate] [datetime] NULL,
[ord_completiondate] [datetime] NULL,
[ord_revtype1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_revtype2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_revtype3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_revtype4] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_totalweight] [float] NULL,
[ord_totalpieces] [decimal] (10, 2) NULL,
[ord_totalmiles] [int] NULL,
[ord_totalcharge] [float] NULL,
[ord_currency] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_currencydate] [datetime] NULL,
[ord_totalvolume] [float] NULL,
[ord_hdrnumber] [int] NULL,
[ord_refnum] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_invoicewhole] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_shipper] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_consignee] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_pu_at] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_dr_at] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_contact] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_lowtemp] [tinyint] NULL,
[ord_hitemp] [tinyint] NULL,
[ord_quantity] [float] NULL,
[ord_rate] [money] NULL,
[ord_charge] [money] NULL,
[ord_rateunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_unit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_type1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_driver1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_driver2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_tractor] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_trailer] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_type1_desc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_length] [money] NULL,
[ord_width] [money] NULL,
[ord_height] [money] NULL,
[ord_lengthunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_widthunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_heightunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_reftype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_name] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_description] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cht_itemcode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_origin_earliestdate] [datetime] NULL,
[ord_origin_latestdate] [datetime] NULL,
[ord_stopcount] [tinyint] NULL,
[ord_dest_earliestdate] [datetime] NULL,
[ord_dest_latestdate] [datetime] NULL,
[ord_cmdvalue] [money] NULL,
[ord_accessorial_chrg] [money] NULL,
[ord_availabledate] [datetime] NULL,
[ord_miscqty] [decimal] (12, 4) NULL,
[ord_tempunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_datetaken] [datetime] NULL,
[ord_totalweightunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_totalvolumeunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_totalcountunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_rateby] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_quantity_type] [int] NULL,
[TotalPieces] [float] NULL,
[TotalWeight] [float] NULL,
[TotalLineHaulPay] [money] NULL,
[TotalPay] [money] NULL,
[StopPay] [money] NULL,
[PermitPay] [money] NULL,
[FuelPay] [money] NULL,
[PupStpComment] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrpStpComment] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedBy] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carrier_payrate] [money] NULL,
[pyd_description] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
