CREATE TABLE [dbo].[EleosOutboundMsgLastSN]
(
[SN] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EleosOutboundMsgLastSN] ADD CONSTRAINT [PK__EleosOut__32151C644CE166A7] PRIMARY KEY CLUSTERED ([SN]) ON [PRIMARY]
GO
