CREATE TABLE [dbo].[TariffInputDNR]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[CommodityCode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommodityClass] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Weight] [decimal] (19, 6) NULL,
[OriginPoint] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestPoint] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginCity] [decimal] (19, 6) NULL,
[DestCity] [decimal] (19, 6) NULL,
[WeightUnit] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Count] [decimal] (19, 6) NULL,
[CountUnit] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Volume] [decimal] (19, 6) NULL,
[VolumeUnit] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Length] [decimal] (19, 6) NULL,
[Width] [decimal] (19, 6) NULL,
[Height] [decimal] (19, 6) NULL,
[BillDate] [datetime] NULL,
[Billto] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillToOthertype1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BilltoOthertype2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Orderby] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderByOtherType1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderByOtherType2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipper] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Consignee] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Trailer] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrlType1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrlType2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrlType3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrlType4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrailerConfiguration] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrlTerminal] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrlFleet] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrlCompany] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrlDivision] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevType1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevType2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevType3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevType4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalMiles] [decimal] (19, 6) NULL,
[Distunit] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Odmiles] [decimal] (19, 6) NULL,
[Odunit] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MileageTable] [decimal] (19, 6) NULL,
[Company] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Carrier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Loadstat] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Driver1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrvType1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrvType2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrvType3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrvType4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DriverTerminal] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DriverFleet] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DriverCompany] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DriverDivision] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DriverTeamLeader] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DriverDomicile] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Driver2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drv2Type1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drv2Type2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drv2Type3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drv2Type4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Driver2Terminal] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tractor] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrcType1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrcType2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrcType3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrcType4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrcTerminal] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrcFleet] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrcCompany] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrcDivision] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Itemcode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Stoptype1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Delays] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Carryins1] [decimal] (19, 6) NULL,
[Carryins2] [decimal] (19, 6) NULL,
[Ooamileage] [decimal] (19, 6) NULL,
[Ooastop] [decimal] (19, 6) NULL,
[Terms] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mastercompany] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginServicecenter] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginServiceregion] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestServicecenter] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestServiceregion] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lghtype1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lghtype2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lghtype3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lghtype4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Thirdparty] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Thirdpartytype] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segments] [decimal] (19, 6) NULL,
[RateBy] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MasterOrderNumber] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevenueCurrency] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevenueCurrencyDate] [datetime] NULL,
[PayRevenue] [decimal] (19, 6) NULL,
[PayRevenueFixYN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LineHaulRevenue] [decimal] (19, 6) NULL,
[AccessorialRevenue] [decimal] (19, 6) NULL,
[SegmentWeight] [decimal] (19, 6) NULL,
[SegmentVolume] [decimal] (19, 6) NULL,
[SegmentCount] [decimal] (19, 6) NULL,
[OrderHeaderNumber] [decimal] (19, 6) NULL,
[BookedByRevType1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderBranch] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StartDate] [datetime] NULL,
[CompletionDate] [datetime] NULL,
[LastUpdateDate] [datetime] NOT NULL CONSTRAINT [DF__TariffInp__LastU__35B599A4] DEFAULT (getdate()),
[LastUpdateBy] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__TariffInp__LastU__36A9BDDD] DEFAULT (suser_name())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TariffInputDNR] ADD CONSTRAINT [pk_TariffInputDNR] PRIMARY KEY CLUSTERED ([Id]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[TariffInputDNR] TO [public]
GO
GRANT INSERT ON  [dbo].[TariffInputDNR] TO [public]
GO
GRANT SELECT ON  [dbo].[TariffInputDNR] TO [public]
GO
GRANT UPDATE ON  [dbo].[TariffInputDNR] TO [public]
GO
