CREATE TABLE [dbo].[TASK_NOTE_AUDIT]
(
[TASK_NOTE_AUDIT_ID] [int] NOT NULL IDENTITY(1, 1),
[TASK_NOTE_ID] [int] NULL,
[TASK_ID] [int] NULL,
[NOTE_TEXT] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATED_DATE] [datetime] NULL,
[CREATED_USER] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MODIFIED_DATE] [datetime] NOT NULL,
[MODIFIED_USER] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUDIT_ACTION] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AUDIT_CREATED_DATE] [datetime] NOT NULL,
[AUDIT_CREATED_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASK_NOTE_AUDIT] ADD CONSTRAINT [PK__TASK_NOTE_AUDIT__7DE5E697] PRIMARY KEY CLUSTERED ([TASK_NOTE_AUDIT_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [DK_TASK_ID] ON [dbo].[TASK_NOTE_AUDIT] ([TASK_ID]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[TASK_NOTE_AUDIT] TO [public]
GO
GRANT INSERT ON  [dbo].[TASK_NOTE_AUDIT] TO [public]
GO
GRANT REFERENCES ON  [dbo].[TASK_NOTE_AUDIT] TO [public]
GO
GRANT SELECT ON  [dbo].[TASK_NOTE_AUDIT] TO [public]
GO
GRANT UPDATE ON  [dbo].[TASK_NOTE_AUDIT] TO [public]
GO
