CREATE TABLE [dbo].[tariffkeybid]
(
[trk_number] [int] NOT NULL,
[trk_description] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tar_number] [int] NULL,
[trk_startdate] [datetime] NULL,
[trk_enddate] [datetime] NULL,
[trk_billto] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_othertype1] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_othertype2] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_code] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_class] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_type1] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_type2] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_type3] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_type4] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_revtype1] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_revtype2] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_revtype3] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_revtype4] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_originpoint] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_origincity] [int] NULL,
[trk_originzip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_originstate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_destpoint] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_destcity] [int] NULL,
[trk_destzip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_deststate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_minmiles] [int] NULL,
[trk_minweight] [decimal] (19, 4) NULL,
[trk_minpieces] [int] NULL,
[trk_minvolume] [decimal] (19, 4) NULL,
[trk_maxmiles] [int] NULL,
[trk_maxweight] [decimal] (19, 4) NULL,
[trk_maxpieces] [int] NULL,
[trk_maxvolume] [decimal] (19, 4) NULL,
[trk_duplicateseq] [int] NULL,
[timestamp] [timestamp] NULL,
[trk_primary] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_minstops] [int] NULL,
[trk_maxstops] [int] NULL,
[trk_minodmiles] [int] NULL,
[trk_maxodmiles] [int] NULL,
[trk_minvariance] [money] NULL,
[trk_maxvariance] [money] NULL,
[trk_orderedby] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_minlength] [money] NULL,
[trk_maxlength] [money] NULL,
[trk_minwidth] [money] NULL,
[trk_maxwidth] [money] NULL,
[trk_minheight] [money] NULL,
[trk_maxheight] [money] NULL,
[trk_origincounty] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_destcounty] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_company] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_carrier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_lghtype1] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_load] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_team] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_boardcarrier] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_distunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_wgtunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_countunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_volunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_odunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_type1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_type2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_type3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_type4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_type1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_type2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_type3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_type4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cht_itemcode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_stoptype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_delays] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_ooamileage] [int] NULL,
[trk_ooastop] [int] NULL,
[trk_carryins1] [int] NULL,
[trk_carryins2] [int] NULL,
[trk_minmaxmiletype] [tinyint] NULL,
[trk_terms] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_triptype_or_region] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_tt_or_oregion] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_dregion] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_mastercompany] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[trk_mileagetable] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_fueltableid] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_minrevpermile] [money] NULL,
[trk_maxrevpermile] [money] NULL,
[trk_indexseq] [smallint] NULL,
[trk_stp_event] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_return_billto] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_return_revtype1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_custdoc] [int] NULL,
[trk_billtoregion] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_updateby] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_updatedate] [datetime] NULL,
[trk_partytobill] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_partytobill_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tch_id] [int] NULL,
[rth_id] [int] NULL,
[trk_originsvccenter] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_originsvcregion] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_destsvccenter] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_destsvcregion] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_lghtype2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_lghtype3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_lghtype4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_thirdparty] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_thirdpartytype] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_minsegments] [int] NULL,
[trk_maxsegments] [int] NULL,
[billto_othertype1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billto_othertype2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[masterordernumber] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_payto] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_number] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_owner] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_number] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_owner] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pto_id] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_terminal] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trc_terminal] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_terminal] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_primary_driver] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_index_factor] [decimal] (19, 6) NULL,
[stop_othertype1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stop_othertype2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_mintime] [decimal] (9, 4) NULL,
[trk_billto_car_key] [int] NULL,
[brn_id] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mpp_domicile] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_usefor_billable] [int] NULL,
[trk_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trk_mincarriersvcdays] [int] NULL,
[trk_maxcarriersvcdays] [int] NULL,
[laneorigintype] [int] NULL,
[lanedesttype] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [pk_trk_number] ON [dbo].[tariffkeybid] ([trk_number]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[tariffkeybid] TO [public]
GO
GRANT INSERT ON  [dbo].[tariffkeybid] TO [public]
GO
GRANT REFERENCES ON  [dbo].[tariffkeybid] TO [public]
GO
GRANT SELECT ON  [dbo].[tariffkeybid] TO [public]
GO
GRANT UPDATE ON  [dbo].[tariffkeybid] TO [public]
GO
