CREATE TABLE [dbo].[stopsdiesel]
(
[Trc] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProyectoAbbr] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Proyecto] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Motor] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CapacidadTanque] [int] NULL,
[NivelTanque] [int] NULL,
[Cliente] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Movimiento] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Orden] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segmento] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StopNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secuencia] [int] NULL,
[CompaniaOrigen] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CiudadOrigen] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EstadoOrigen] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompaniaDestino] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CiudadDestino] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EstadoDestino] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Kms] [int] NULL,
[StCarga] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Peso] [int] NULL,
[Trailer1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Trailer2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dolly] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EjesTrc] [int] NULL,
[EjesTrl1] [int] NULL,
[EjesTrl2] [int] NULL,
[EjesDolly] [int] NULL,
[Ejes] [int] NULL,
[Rendimiento] [float] NULL,
[Litros] [int] NULL,
[Proveedor] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inicio] [datetime] NULL,
[Fin] [datetime] NULL,
[Duracion] [int] NULL
) ON [PRIMARY]
GO
