CREATE TABLE [dbo].[DW_MODIFY]
(
[DW_NAME] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SEQ] [int] NOT NULL,
[EXPRESSION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_MODIFIED] [datetime] NULL,
[USER_MODIFIED] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[expression_large] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DW_MODIFY] ADD CONSTRAINT [PK_DW_MODIFY] PRIMARY KEY CLUSTERED ([DW_NAME], [SEQ]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[DW_MODIFY] TO [public]
GO
GRANT INSERT ON  [dbo].[DW_MODIFY] TO [public]
GO
GRANT REFERENCES ON  [dbo].[DW_MODIFY] TO [public]
GO
GRANT SELECT ON  [dbo].[DW_MODIFY] TO [public]
GO
GRANT UPDATE ON  [dbo].[DW_MODIFY] TO [public]
GO
