CREATE TABLE [dbo].[cdposttran]
(
[timestamp] [binary] (8) NULL,
[pyd_number] [int] NOT NULL,
[pyh_number] [int] NOT NULL,
[lgh_number] [int] NULL,
[asgn_number] [int] NULL,
[asgn_type] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[asgn_id] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_number] [int] NULL,
[pyd_prorap] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_payto] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyt_itemcode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mov_number] [int] NULL,
[pyd_description] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyr_ratecode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_quantity] [float] NULL,
[pyd_rateunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_unit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_rate] [money] NULL,
[pyd_amount] [money] NULL,
[pyd_pretax] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_glnum] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_currency] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_currencydate] [datetime] NULL,
[pyd_status] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_refnumtype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_refnum] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyh_payperiod] [datetime] NULL,
[pyd_workperiod] [datetime] NULL,
[lgh_startpoint] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_startcity] [int] NULL,
[lgh_endpoint] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lgh_endcity] [int] NULL,
[ivd_payrevenue] [money] NULL,
[pyd_revenueratio] [float] NULL,
[pyd_lessrevenue] [money] NULL,
[pyd_payrevenue] [money] NULL,
[pyd_transdate] [datetime] NULL,
[pyd_minus] [int] NULL,
[pyd_sequence] [int] NULL,
[std_number] [int] NULL,
[pyd_loadstate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_xrefnumber] [int] NULL,
[ord_hdrnumber] [int] NULL,
[pyt_fee1] [money] NULL,
[pyt_fee2] [money] NULL,
[pyd_grossamount] [money] NULL,
[pyd_adj_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_updatedby] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[psd_id] [int] NULL,
[pyd_transferdate] [datetime] NULL,
[pyd_exportstatus] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_releasedby] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cht_itemcode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_billedweight] [int] NULL,
[tar_tarriffnumber] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[psd_batch_id] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_updsrc] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_updatedon] [datetime] NULL,
[pyd_offsetpay_number] [int] NULL,
[pyd_credit_pay_flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_ivh_hdrnumber] [int] NULL,
[psd_number] [int] NULL,
[pyd_ref_invoice] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_ref_invoicedate] [datetime] NULL,
[pyd_ignoreglreset] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_authcode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_PostProcSource] [smallint] NULL,
[pyd_GPTrans] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cac_id] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ccc_id] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_hourlypaydate] [datetime] NULL,
[pyd_isdefault] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_mbtaxableamount] [money] NULL,
[pyd_nttaxableamount] [money] NULL,
[pyd_maxquantity_used] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_maxcharge_used] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_carinvnum] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_carinvdate] [datetime] NULL,
[std_number_adj] [int] NULL,
[pyd_vendortopay] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_pyd_cdposttran_vendortopay] DEFAULT ('UNKNOWN'),
[pyd_vendorpay] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_remarks] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_number] [int] NULL,
[stp_mfh_sequence] [int] NULL,
[pyd_perdiem_exceeded] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_carrierinvoice_aprv] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_carrierinvoice_rjct] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd__aprv_rjct_comment] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_paid_indicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pyd_paid_amount] [money] NULL,
[pyd_payment_date] [datetime] NULL,
[pyd_payment_doc_number] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cpd_crd_number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdp_updatetype] [int] NULL,
[cdp_cashoncard_replace] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cd_days_to_expire] [int] NULL,
[cdp_expiration_date] [datetime] NULL,
[cdp_expresscodenumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdp_amountcode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdp_exchange_rate] [money] NULL,
[cdp_payee] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdp_status] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdp_total_pay] [money] NULL,
[cdp_po_number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdp_productcode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[cdposttran] ADD CONSTRAINT [PK_cdposttran] PRIMARY KEY NONCLUSTERED ([pyd_number]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[cdposttran] TO [public]
GO
GRANT INSERT ON  [dbo].[cdposttran] TO [public]
GO
GRANT REFERENCES ON  [dbo].[cdposttran] TO [public]
GO
GRANT SELECT ON  [dbo].[cdposttran] TO [public]
GO
GRANT UPDATE ON  [dbo].[cdposttran] TO [public]
GO
