CREATE TABLE [dbo].[MCEXCEPTION]
(
[MCM_ID] [int] NOT NULL,
[MCX_STATUS] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MCX_EXCEPTION] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_id] ON [dbo].[MCEXCEPTION] ([MCM_ID]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[MCEXCEPTION] TO [public]
GO
GRANT INSERT ON  [dbo].[MCEXCEPTION] TO [public]
GO
GRANT REFERENCES ON  [dbo].[MCEXCEPTION] TO [public]
GO
GRANT SELECT ON  [dbo].[MCEXCEPTION] TO [public]
GO
GRANT UPDATE ON  [dbo].[MCEXCEPTION] TO [public]
GO
