CREATE TABLE [dbo].[invoicedetailaudit]
(
[ivd_number] [int] NOT NULL,
[audit_sequence] [int] NOT NULL IDENTITY(1, 1),
[audit_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[audit_user] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[audit_date] [datetime] NOT NULL,
[cht_itemcode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_quantity] [float] NULL,
[ivd_rate] [money] NULL,
[ivd_charge] [money] NULL,
[tar_number] [int] NULL,
[ivh_hdrnumber] [int] NULL,
[ord_hdrnumber] [int] NULL,
[audit_app] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_number] [int] NULL,
[ivd_description] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_taxable1] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_taxable2] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_taxable3] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_taxable4] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_unit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cur_code] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_currencydate] [datetime] NULL,
[ivd_glnum] [char] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_type] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_rateunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_billto] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_itemquantity] [float] NULL,
[ivd_subtotalptr] [int] NULL,
[ivd_allocatedrev] [money] NULL,
[ivd_sequence] [int] NULL,
[ivd_invoicestatus] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mfh_hdrnumber] [int] NULL,
[ivd_refnum] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmp_id] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_distance] [float] NULL,
[ivd_distunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_wgt] [float] NULL,
[ivd_wgtunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_count] [decimal] (10, 2) NULL,
[ivd_countunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[evt_number] [int] NULL,
[ivd_reftype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_volume] [float] NULL,
[ivd_volunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_orig_cmpid] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_payrevenue] [money] NULL,
[ivd_sign] [smallint] NULL,
[ivd_length] [money] NULL,
[ivd_lengthunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_width] [money] NULL,
[ivd_widthunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_height] [money] NULL,
[ivd_heightunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_exportstatus] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cht_basisunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_remark] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tar_tariffnumber] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tar_tariffitem] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_fromord] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_zipcode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_quantity_type] [smallint] NULL,
[cht_class] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_mileagetable] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_charge_type] [smallint] NULL,
[ivd_trl_rent] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_trl_rent_start] [datetime] NULL,
[ivd_trl_rent_end] [datetime] NULL,
[ivd_rate_type] [smallint] NULL,
[last_updateby] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_updatedate] [datetime] NULL,
[cht_lh_min] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cht_lh_rev] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cht_lh_stl] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cht_lh_rpt] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cht_rollintolh] [int] NULL,
[cht_lh_prn] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fgt_number] [int] NULL,
[ivd_paylgh_number] [int] NULL,
[ivd_tariff_type] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_taxid] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_ordered_volume] [decimal] (18, 0) NULL,
[ivd_ordered_loadingmeters] [decimal] (18, 0) NULL,
[ivd_ordered_count] [decimal] (18, 0) NULL,
[ivd_ordered_weight] [decimal] (18, 0) NULL,
[ivd_loadingmeters] [decimal] (18, 0) NULL,
[ivd_loadingmeters_unit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_revtype1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_hide] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_baserate] [decimal] (19, 4) NULL,
[ivd_rawcharge] [decimal] (19, 4) NULL,
[ivd_oradjustment] [decimal] (19, 4) NULL,
[ivd_cbadjustment] [decimal] (19, 4) NULL,
[ivd_fsc] [decimal] (19, 4) NULL,
[ivd_splitbillratetype] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_bolid] [int] NULL,
[ivd_shared_wgt] [decimal] (19, 4) NULL,
[ivd_miscmoney1] [money] NULL,
[ivd_tollcost] [money] NULL,
[ivd_ARTaxAuth] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_paid_indicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_paid_amount] [money] NULL,
[ivd_actual_quantity] [float] NULL,
[ivd_actual_unit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_tax_basis] [money] NULL,
[fgt_supplier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_loaded_distance] [float] NULL,
[ivd_empty_distance] [float] NULL,
[ivd_MaskFromRating] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ivd_car_key] [int] NULL,
[ivd_leaseassetid] [int] NULL,
[ivd_showas_cmpid] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[invoicedetailaudit] ADD CONSTRAINT [pk_invoicedetailaudit] PRIMARY KEY CLUSTERED ([ivd_number], [audit_sequence]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_ida_ivh_hdrnumber] ON [dbo].[invoicedetailaudit] ([ivh_hdrnumber], [cht_itemcode]) WITH (FILLFACTOR=95) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dk_ivdaudit_ord_hdrnumber] ON [dbo].[invoicedetailaudit] ([ord_hdrnumber]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[invoicedetailaudit] TO [public]
GO
GRANT INSERT ON  [dbo].[invoicedetailaudit] TO [public]
GO
GRANT REFERENCES ON  [dbo].[invoicedetailaudit] TO [public]
GO
GRANT SELECT ON  [dbo].[invoicedetailaudit] TO [public]
GO
GRANT UPDATE ON  [dbo].[invoicedetailaudit] TO [public]
GO
