CREATE TABLE [dbo].[ttsgroups]
(
[grp_id] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[grp_name] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[timestamp] [timestamp] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[dt_ttsgroups_rowsec] ON [dbo].[ttsgroups]
FOR DELETE
AS
	
	DELETE	RowSecUserAssignments
	FROM	deleted d
	WHERE	RowSecUserAssignments.rsua_idtype = 'G'
			AND RowSecUserAssignments.usr_userid = d.grp_id

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[it_ttsgroups_rowsec] ON [dbo].[ttsgroups]
FOR INSERT
AS

	INSERT	RowSecUserAssignments (
				rsua_idtype,
				usr_userid,
				rscv_id
			)					
	SELECT	'G',
			tg.grp_id, 
			rscv.rscv_id
	FROM	inserted tg
			CROSS JOIN RowSecColumns rsc
			INNER JOIN RowSecColumnValues rscv on rsc.rsc_id = rscv.rsc_id
	WHERE	rsc.rsc_sequence > 0
			AND rsc.rsc_unknown_value = rscv.rscv_value
			AND NOT EXISTS	(	SELECT	*
								FROM	RowSecUserAssignments rsua_inner
										INNER JOIN RowSecColumnValues rscv_inner on rscv_inner.rscv_id = rsua_inner.rscv_id
								WHERE	rsua_inner.rsua_idtype = 'G'
										AND rsua_inner.usr_userid = tg.grp_id
										AND rscv_inner.rscv_value = rscv.rscv_value
										AND rscv_inner.rsc_id = rsc.rsc_id
							)	

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[ttsgroups_d] ON [dbo].[ttsgroups] FOR DELETE  AS 
BEGIN
SET NOCOUNT ON -- 06/25/2007 MDH PTS: 38085: Added 

/****************************************************************************/
/* Target Table                        Primary Key Column(s)                */
/* --------------                      --------------                       */
/* dbo.ttsgroups                       grp_id                               */
/*                                                                          */
/* Foreign Key Table                   Foreign Key Column(s)                */
/* --------------                      --------------                       */
/* dbo.ttsgroupasgn                    grp_id                               */
/*                  		                                            */
/* REVISION HISTORY:							    */
/* Date ? 	PTS# - 	AuthorName ? Revision Description		    */
/* 10/02/2007	35763	SLM	     Add table note_group_restriction       */
/* 10/08/2007   35767   SLM 	     Add table note_note_type_permits       */
/*                                                                          */
/****************************************************************************/

/*** Begin CASCADE deletes generated by Object Manager ***/

DELETE ttsgroupasgn
FROM ttsgroupasgn, deleted
WHERE  ttsgroupasgn.grp_id =  deleted.grp_id
/*** End CASCADE deletes generated by Object Manager ***/

DELETE ttspermission
FROM ttspermission, deleted
WHERE ttspermission.per_id = deleted.grp_id
and ttspermission.per_idtype = 'B'

-- PTS 35763
DELETE note_group_restriction
FROM note_group_restriction, deleted
WHERE  note_group_restriction.note_grp_id = deleted.grp_id

-- PTS 35767
DELETE note_note_type_permits
FROM note_note_type_permits, deleted
WHERE  note_note_type_permits.note_grp_id = deleted.grp_id

END






GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[ttsgroups_u] ON [dbo].[ttsgroups] FOR UPDATE  AS 
BEGIN
SET NOCOUNT ON -- 06/25/2007 MDH PTS: 38085: Added 

/****************************************************************************/
/* Target Table                        Primary Key Column(s)                */
/* --------------                      --------------                       */
/* dbo.ttsgroups                       grp_id                               */
/*                                                                          */
/* Foreign Key Table                   Foreign Key Column(s)                */
/* --------------                      --------------                       */
/* dbo.ttsgroupasgn                    grp_id                               */
/*                                                                          */
/****************************************************************************/
/* Target Table                        Foreign Key Column(s)                */
/* --------------                      --------------                       */
/* dbo.ttsgroups                       (none)                               */
/*                                                                          */
/* Primary Key Table                   Primary Key Column(s)                */
/* --------------                      --------------                       */
/* (none)                                                                   */
/****************************************************************************/

/*** Begin CASCADE updates generated by Object Manager ***/
IF UPDATE (grp_id)
BEGIN
UPDATE ttsgroupasgn
SET  ttsgroupasgn.grp_id =  inserted.grp_id
FROM  ttsgroupasgn, inserted, deleted
WHERE  ttsgroupasgn.grp_id =  deleted.grp_id

UPDATE ttspermission
SET ttspermission.per_id = inserted.grp_id
FROM ttspermission, inserted, deleted
WHERE ttspermission.per_id = deleted.grp_id AND
ttspermission.per_idtype = 'B'

/*** End CASCADE updates generated by Object Manager ***/
END


END


GO
CREATE UNIQUE NONCLUSTERED INDEX [k_grpid] ON [dbo].[ttsgroups] ([grp_id]) INCLUDE ([grp_name]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[ttsgroups] TO [public]
GO
GRANT INSERT ON  [dbo].[ttsgroups] TO [public]
GO
GRANT REFERENCES ON  [dbo].[ttsgroups] TO [public]
GO
GRANT SELECT ON  [dbo].[ttsgroups] TO [public]
GO
GRANT UPDATE ON  [dbo].[ttsgroups] TO [public]
GO
