CREATE TABLE [dbo].[Persona]
(
[IIDPERSONA] [int] NOT NULL IDENTITY(1, 1),
[NOMBRE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APPATERNO] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APMATERNO] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CORREO] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIRECCION] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IIDSEXO] [int] NULL,
[BHABILITADO] [int] NULL,
[NUMEROTELEFONICO] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEMPLEADO] [int] NULL,
[IIDSUCURSAL] [int] NULL
) ON [PRIMARY]
GO
