CREATE TABLE [dbo].[cashcarddef]
(
[crddef_cardnumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[crddef_accountid] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[crddef_customerid] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[crddef_status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_status] DEFAULT ('I'),
[crddef_usecard] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_usecard] DEFAULT ('N'),
[crddef_directdeposit] [int] NOT NULL CONSTRAINT [df_cashcarddef_crddef_directDeposit] DEFAULT (0),
[crddef_atmaccess] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_atmaccess] DEFAULT ('N'),
[crddef_vruaccess] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_vruaccess] DEFAULT ('0'),
[crddef_limitnetworkbycard] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_limitnetworkbycard] DEFAULT ('0'),
[asgn_type] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_asgn_type] DEFAULT ('DRV'),
[asgn_id] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_asgn_id] DEFAULT ('UNKNOWN'),
[crddef_firstname] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_lastname] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_driverlicensenum] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_driverlicensestate] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_unitnumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_unitnumber] DEFAULT ('UNKNOWN'),
[crddef_driver] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_trailernumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_tripnumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_fuelpurchaseyn] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_fuelpurchaseyn] DEFAULT ('0'),
[crddef_purchaselimit] [money] NULL,
[crddef_onetimepurchaselimit] [money] NULL,
[crddef_diesellimit] [int] NULL,
[crddef_reeferlimit] [int] NULL,
[crddef_purchrenewdaily] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_purchrenewdaily] DEFAULT ('0'),
[crddef_purchrenewmon] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_purchrenewmon] DEFAULT ('0'),
[crddef_purchrenewtue] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_purchrenewtue] DEFAULT ('0'),
[crddef_purchrenewwed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_purchrenewwed] DEFAULT ('0'),
[crddef_purchrenewthu] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_purchrenewthu] DEFAULT ('0'),
[crddef_purchrenewfri] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_purchrenewfri] DEFAULT ('0'),
[crddef_purchrenewsat] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_purchrenewsat] DEFAULT ('0'),
[crddef_purchrenewsun] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_purchrenewsun] DEFAULT ('0'),
[crddef_purchrenewtrip] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_purchrenewtrip] DEFAULT ('0'),
[crddef_expcashflagyn] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_expcashflagyn] DEFAULT ('0'),
[crddef_cashlimit] [money] NULL,
[crddef_onetimecashlimit] [money] NULL,
[crddef_cashbalance] [money] NULL,
[crddef_cashrenewdaily] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_cashrenewdaily] DEFAULT ('0'),
[crddef_cashrenewmon] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_cashrenewmon] DEFAULT ('0'),
[crddef_cashrenewtue] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_cashrenewtue] DEFAULT ('0'),
[crddef_cashrenewwed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_cashrenewwed] DEFAULT ('0'),
[crddef_cashrenewthu] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_cashrenewthu] DEFAULT ('0'),
[crddef_cashrenewfri] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_cashrenewfri] DEFAULT ('0'),
[crddef_cashrenewsat] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_cashrenewsat] DEFAULT ('0'),
[crddef_cashrenewsun] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_cashrenewsun] DEFAULT ('0'),
[crddef_cashrenewtrip] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [df_cashcarddef_crddef_cashrenewtrip] DEFAULT ('0'),
[crddef_phoneserviceyn] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_phoneserviceyn] DEFAULT ('0'),
[crddef_phoneamountlimit] [money] NULL,
[crddef_phonerenewdaily] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_phonerenewdaily] DEFAULT ('0'),
[crddef_phonerenewsun] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_phonerenewsun] DEFAULT ('0'),
[crddef_phonerenewmon] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_phonerenewmon] DEFAULT ('0'),
[crddef_phonerenewtue] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_phonerenewtue] DEFAULT ('0'),
[crddef_phonerenewwed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_phonerenewwed] DEFAULT ('0'),
[crddef_phonerenewthu] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_phonerenewthu] DEFAULT ('0'),
[crddef_phonerenewfri] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_phonerenewfri] DEFAULT ('0'),
[crddef_phonerenewsat] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_phonerenewsat] DEFAULT ('0'),
[crddef_phonerenewtrip] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_phonerenewtrip] DEFAULT ('0'),
[crddef_oilamountlimit] [money] NULL,
[crddef_oillimit] [int] NULL,
[crddef_oilrenewdaily] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_oilrenewdaily] DEFAULT ('0'),
[crddef_oilrenewsun] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_oilrenewsun] DEFAULT ('0'),
[crddef_oilrenewmon] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_oilrenewmon] DEFAULT ('0'),
[crddef_oilrenewtue] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_oilrenewtue] DEFAULT ('0'),
[crddef_oilrenewwed] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_oilrenewwed] DEFAULT ('0'),
[crddef_oilrenewthu] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_oilrenewthu] DEFAULT ('0'),
[crddef_oilrenewfri] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_oilrenewfri] DEFAULT ('0'),
[crddef_oilrenewsat] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_oilrenewsat] DEFAULT ('0'),
[crddef_oilrenewtrip] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [df_cashcarddef_crddef_oilrenewtrip] DEFAULT ('0'),
[crddef_updatestatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_errormessage] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_purchrenewdaily_old] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_purchrenewtrip_old] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_cashrenewdaily_old] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_cashrenewtrip_old] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_phonerenewdaily_old] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_phonerenewtrip_old] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_oilrenewdaily_old] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crddef_oilrenewtrip_old] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[limitnetwork_expdate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[cashcarddef] ADD CONSTRAINT [pk_cashcarddef] PRIMARY KEY CLUSTERED ([crddef_cardnumber], [crddef_accountid], [crddef_customerid]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[cashcarddef] TO [public]
GO
GRANT INSERT ON  [dbo].[cashcarddef] TO [public]
GO
GRANT REFERENCES ON  [dbo].[cashcarddef] TO [public]
GO
GRANT SELECT ON  [dbo].[cashcarddef] TO [public]
GO
GRANT UPDATE ON  [dbo].[cashcarddef] TO [public]
GO
