CREATE TABLE [dbo].[MCGROUP]
(
[MCG_GROUP] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MCG_NAMETYPE] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MCG_NAME] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [uk_groupid] ON [dbo].[MCGROUP] ([MCG_GROUP], [MCG_NAMETYPE], [MCG_NAME]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[MCGROUP] TO [public]
GO
GRANT INSERT ON  [dbo].[MCGROUP] TO [public]
GO
GRANT REFERENCES ON  [dbo].[MCGROUP] TO [public]
GO
GRANT SELECT ON  [dbo].[MCGROUP] TO [public]
GO
GRANT UPDATE ON  [dbo].[MCGROUP] TO [public]
GO
