CREATE TABLE [dbo].[completion_orderheader]
(
[ord_company] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_number] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ord_customer] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_bookdate] [datetime] NULL,
[ord_bookedby] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_status] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_originpoint] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_destpoint] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_invoicestatus] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_origincity] [int] NULL,
[ord_destcity] [int] NULL,
[ord_originstate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_deststate] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_originregion1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_destregion1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_supplier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_billto] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_startdate] [datetime] NULL,
[ord_completiondate] [datetime] NULL,
[ord_revtype1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_revtype2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_revtype3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_revtype4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_totalweight] [float] NULL,
[ord_totalpieces] [decimal] (10, 2) NULL,
[ord_totalmiles] [int] NULL,
[ord_totalcharge] [float] NULL,
[ord_currency] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_currencydate] [datetime] NULL,
[ord_totalvolume] [float] NULL,
[ord_hdrnumber] [int] NOT NULL,
[ord_refnum] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_invoicewhole] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_remark] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_shipper] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_consignee] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_pu_at] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_dr_at] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_originregion2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_originregion3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_originregion4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_destregion2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_destregion3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_destregion4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mfh_hdrnumber] [int] NULL,
[ord_priority] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mov_number] [int] NULL,
[tar_tarriffnumber] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tar_number] [int] NULL,
[timestamp] [timestamp] NULL,
[tar_tariffitem] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_contact] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_showshipper] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_showcons] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_subcompany] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_lowtemp] [int] NULL,
[ord_hitemp] [int] NULL,
[ord_quantity] [float] NULL,
[ord_rate] [money] NULL,
[ord_charge] [money] NULL,
[ord_rateunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_unit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trl_type1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_driver1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_driver2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_tractor] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_trailer] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_length] [money] NULL,
[ord_width] [money] NULL,
[ord_height] [money] NULL,
[ord_lengthunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_widthunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_heightunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_reftype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_description] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_terms] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cht_itemcode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_origin_earliestdate] [datetime] NULL,
[ord_origin_latestdate] [datetime] NULL,
[ord_odmetermiles] [int] NULL,
[ord_stopcount] [tinyint] NULL,
[ord_dest_earliestdate] [datetime] NULL,
[ord_dest_latestdate] [datetime] NULL,
[ref_sid] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ref_pickup] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_cmdvalue] [money] NULL,
[ord_accessorial_chrg] [money] NULL,
[ord_availabledate] [datetime] NULL,
[ord_miscqty] [money] NULL,
[ord_tempunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_datetaken] [datetime] NULL,
[ord_totalweightunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_totalvolumeunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_totalcountunits] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_loadtime] [float] NULL,
[ord_unloadtime] [float] NULL,
[ord_drivetime] [float] NULL,
[ord_rateby] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_quantity_type] [int] NULL,
[ord_thirdpartytype1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_thirdpartytype2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_charge_type] [smallint] NULL,
[ord_bol_printed] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_fromorder] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_mintemp] [smallint] NULL,
[ord_maxtemp] [smallint] NULL,
[ord_distributor] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[opt_trc_type4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[opt_trl_type4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_cod_amount] [money] NULL,
[appt_init] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[appt_contact] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_ratingquantity] [float] NULL,
[ord_ratingunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_booked_revtype1] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_hideshipperaddr] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_hideconsignaddr] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_trl_type2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_trl_type3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_trl_type4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_tareweight] [int] NULL,
[ord_grossweight] [int] NULL,
[ord_mileagetable] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_allinclusivecharge] [money] NULL,
[ord_extrainfo1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo5] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo6] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo7] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo8] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo9] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo10] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo11] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo12] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo13] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo14] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_extrainfo15] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_rate_type] [smallint] NULL,
[ord_barcode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_broker] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_stlquantity] [float] NULL,
[ord_stlunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_stlquantity_type] [tinyint] NULL,
[ord_fromschedule] [int] NULL,
[ord_schedulebatch] [int] NULL,
[ord_trlrentinv] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_revenue_pay_fix] [int] NULL,
[ord_revenue_pay] [money] NULL,
[ord_reserved_number] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_customs_document] [int] NULL,
[ord_noautosplit] [tinyint] NULL,
[ord_noautotransfer] [tinyint] NULL,
[ord_totalloadingmeters] [decimal] (12, 4) NULL,
[ord_totalloadingmetersunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_charge_type_lh] [smallint] NULL,
[ord_complete_stamp] [datetime] NULL,
[last_updateby] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_updatedate] [datetime] NULL,
[ord_entryport] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_exitport] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_mileage_adj_pct] [decimal] (9, 2) NULL,
[ord_commodities_weight] [float] NULL,
[ord_intermodal] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_order_source] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_dimfactor] [decimal] (12, 4) NULL,
[external_id] [int] NULL,
[external_type] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ord_UnlockKey] [int] NULL,
[ord_TrlConfiguration] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_origin_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_dest_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_rate_mileagetable] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_toll_cost] [money] NULL,
[ord_toll_cost_update_date] [datetime] NULL,
[ord_raildest] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_railpoolid] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_trailer2] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_route] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_route_effc_date] [datetime] NULL,
[ord_route_exp_date] [datetime] NULL,
[ord_odmetermiles_mtid] [int] NULL,
[ord_edipurpose] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_ediuseraction] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_edistate] [tinyint] NULL,
[ord_no_recalc_miles] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_editradingpartner] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_edideclinereason] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_miscdate1] [datetime] NULL,
[ord_carrier] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_completion_odometer_start] [int] NULL,
[ord_completion_odometer_end] [int] NULL,
[ord_completion_pickup_count] [int] NULL,
[ord_completion_drop_count] [int] NULL,
[from_cmp_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[from_cty_nmstct] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[to_cmp_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[to_cty_nmstct] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_completion_batch_eligible] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_completion_batch_status] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_completion_shift_date] [datetime] NULL,
[ord_completion_shift_id] [int] NULL,
[ord_completion_bill_miles] [money] NULL,
[ord_completion_pay_miles] [money] NULL,
[ord_completion_total_time] [money] NULL,
[ord_completion_agent] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billto_cmp_name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billto_cty_nmstct] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_completion_loaddate] [datetime] NULL,
[ord_completion_ivhpyd_count] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[completion_orderheader] ADD CONSTRAINT [PK_completion_orderheader] PRIMARY KEY CLUSTERED ([ord_hdrnumber]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[completion_orderheader] TO [public]
GO
GRANT INSERT ON  [dbo].[completion_orderheader] TO [public]
GO
GRANT REFERENCES ON  [dbo].[completion_orderheader] TO [public]
GO
GRANT SELECT ON  [dbo].[completion_orderheader] TO [public]
GO
GRANT UPDATE ON  [dbo].[completion_orderheader] TO [public]
GO
