CREATE TABLE [dbo].[MCMACROTEXT]
(
[MCT_SERVICE] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MCT_DIRECTION] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MCT_MACRONUM] [smallint] NOT NULL,
[MCT_SEQUENCE] [smallint] NOT NULL,
[MCT_TEMPLATE] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [uk_servdirmacseq] ON [dbo].[MCMACROTEXT] ([MCT_SERVICE], [MCT_DIRECTION], [MCT_MACRONUM], [MCT_SEQUENCE]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[MCMACROTEXT] TO [public]
GO
GRANT INSERT ON  [dbo].[MCMACROTEXT] TO [public]
GO
GRANT REFERENCES ON  [dbo].[MCMACROTEXT] TO [public]
GO
GRANT SELECT ON  [dbo].[MCMACROTEXT] TO [public]
GO
GRANT UPDATE ON  [dbo].[MCMACROTEXT] TO [public]
GO
