CREATE TABLE [dbo].[TASK_AUDIT]
(
[TASK_AUDIT_ID] [int] NOT NULL IDENTITY(1, 1),
[TASK_ID] [int] NULL,
[TASK_TEMPLATE_ID] [int] NULL,
[NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAME_P] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAME_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TASK_LINK_ENTITY_VALUE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TASK_LINK_ENTITY_SYS_VALUE] [int] NULL,
[TASK_LINK_ENTITY_TABLE_ID] [int] NULL,
[DESCRIPTION] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION_P] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORIGINAL_DUE_DATE] [datetime] NULL,
[ASSIGNED_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASSIGNED_USER_P] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASSIGNED_USER_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DUE_DATE] [datetime] NULL,
[DUE_DATE_P] [datetime] NULL,
[DUE_DATE_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LEAD_TIME] [int] NULL,
[LEAD_TIME_P] [int] NULL,
[LEAD_TIME_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIORITY] [int] NULL,
[PRIORITY_P] [int] NULL,
[PRIORITY_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPLETED_DATE] [datetime] NULL,
[ACTIVE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVE_FLAG_P] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVE_FLAG_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUS_P] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUS_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATED_DATE] [datetime] NULL,
[CREATED_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MODIFIED_DATE] [datetime] NULL,
[MODIFIED_USER] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE1_P] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE1_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE2_P] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE2_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE3_P] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE3_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE4] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE4_P] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_DEFINED_TYPE4_F] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PENDING_CHANGES_FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO6] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO7] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO8] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO9] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO10] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO11] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO12] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO13] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO14] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDL_INFO15] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUDIT_ACTION] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AUDIT_CREATED_DATE] [datetime] NOT NULL,
[AUDIT_CREATED_USER] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROMPT_ADD_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENERATION_RULE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROMPT_EDIT_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROMPT_DELETE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROMPT_HOLD_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TASK_AUDIT] ADD CONSTRAINT [PK__TASK_AUDIT__727433EB] PRIMARY KEY CLUSTERED ([TASK_AUDIT_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [DK_TASK_ID] ON [dbo].[TASK_AUDIT] ([TASK_ID]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[TASK_AUDIT] TO [public]
GO
GRANT INSERT ON  [dbo].[TASK_AUDIT] TO [public]
GO
GRANT REFERENCES ON  [dbo].[TASK_AUDIT] TO [public]
GO
GRANT SELECT ON  [dbo].[TASK_AUDIT] TO [public]
GO
GRANT UPDATE ON  [dbo].[TASK_AUDIT] TO [public]
GO
