CREATE TABLE [dbo].[LegHeaderSummary_VentasSemanal]
(
[ord_hdrnumber] [int] NULL,
[OrderNumber] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MoveNumber] [int] NULL,
[LegNumber] [int] NULL,
[OrderedBy] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillTo] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillToName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipper] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipperName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShipperLocation] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_origincity] [int] NULL,
[ShipDate] [datetime] NULL,
[Consignee] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConsigneeName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConsigneeLocation] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_destcity] [int] NULL,
[DeliveryDate] [datetime] NULL,
[MoveStartDate] [datetime] NULL,
[LegStartDate] [datetime] NULL,
[LegEndDate] [datetime] NULL,
[MoveEndDate] [datetime] NULL,
[DriverID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lider] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tractor] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Trailer] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevType1] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevType2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevType3] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevType4] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelectedRevenue] [float] NULL,
[SelectedPay] [float] NULL,
[TravelMiles] [float] NULL,
[LoadedMiles] [float] NULL,
[EmptyMiles] [float] NULL,
[BillMiles] [float] NULL,
[LoadCount] [float] NULL,
[OrderCount] [float] NULL,
[InvoiceStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Weight] [float] NULL,
[WeightUOM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Volume] [float] NULL,
[VolumeUOM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PkgCount] [float] NULL,
[PkgCountUOM] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LegPct] [float] NULL,
[OrderPct] [float] NULL,
[CurrentStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Region] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rorigen] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rdestino] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Flota] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fechaini] [datetime] NULL,
[Fechafin] [datetime] NULL
) ON [PRIMARY]
GO
