CREATE TABLE [dbo].[OPEN_PAYABLES]
(
[INVOICE_ID] [decimal] (15, 0) NOT NULL,
[VENDOR_ID] [decimal] (15, 0) NOT NULL,
[INVOICE_NUM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[INVOICE_AMOUNT] [float] NOT NULL,
[VENDOR_SITE_ID] [decimal] (15, 0) NOT NULL,
[AMOUNT_PAID] [float] NULL,
[INVOICE_DATE] [datetime] NULL,
[TMW_ALT_ID] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[OPEN_PAYABLES] TO [public]
GO
GRANT INSERT ON  [dbo].[OPEN_PAYABLES] TO [public]
GO
GRANT REFERENCES ON  [dbo].[OPEN_PAYABLES] TO [public]
GO
GRANT SELECT ON  [dbo].[OPEN_PAYABLES] TO [public]
GO
GRANT UPDATE ON  [dbo].[OPEN_PAYABLES] TO [public]
GO
