CREATE TABLE [dbo].[tablauno]
(
[t1ord_hdrnumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1lgh_tractor] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1lgh_primary_trailer] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1DrvOrCarrier] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1lgh_driver1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1mov_number] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1lgh_number] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1lgh_startdate] [datetime] NOT NULL,
[t1lgh_Enddate] [datetime] NOT NULL,
[t1NumberOfPaytos] [int] NOT NULL,
[t1CompensationForLegHeader] [decimal] (18, 0) NOT NULL,
[t1FirstPayTo] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1FirstPayToCompensation] [decimal] (18, 0) NOT NULL,
[t1LastPayTo] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1LastPayToCompensation] [decimal] (18, 0) NOT NULL,
[t1OrderStartDate] [datetime] NOT NULL,
[t1OrderEndDate] [datetime] NOT NULL,
[t1trl_type1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1trl_type2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1trl_type3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1trl_type4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1lgh_carrier] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1cmp_id_start] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1lgh_startcty_nmstct] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1cmp_id_end] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1lgh_endcty_nmstct] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1LoadedMlsMove] [int] NOT NULL,
[t1MTMlsMove] [int] NOT NULL,
[t1TotMlsMove] [int] NOT NULL,
[t1LoadedMlsLegHeader] [int] NOT NULL,
[t1MTMlsLegHeader] [int] NOT NULL,
[t1TotMlsLegHeader] [int] NOT NULL,
[t1TotLHChargeForMove] [decimal] (18, 0) NOT NULL,
[t1AccChargeMove] [decimal] (18, 0) NOT NULL,
[t1AllChargesMove] [decimal] (18, 0) NOT NULL,
[t1PercentLghMlsOfMoveMls] [decimal] (18, 0) NOT NULL,
[t1AllocatedLHChargeForLgh] [decimal] (18, 0) NOT NULL,
[t1AllocatedAcclChargeForLgh] [decimal] (18, 0) NOT NULL,
[t1AllocatedTotlChargesForLgh] [decimal] (18, 0) NOT NULL,
[t1RevPerMileAllCharges] [decimal] (18, 0) NOT NULL,
[t1RevPerMileLHCharge] [decimal] (18, 0) NOT NULL,
[t1FirstBillTo] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1lgh_class1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1lgh_class2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1lgh_class3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1lgh_class4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1trc_type1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1trc_type2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1trc_type3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1trc_type4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1FirstBillDate] [datetime] NOT NULL,
[t1LastBillDate] [datetime] NOT NULL,
[t1FirstCompletionDate] [datetime] NOT NULL,
[t1TotalFuelSurchargeForMove] [decimal] (18, 0) NOT NULL,
[t1AllocatedFuelSurchargeChargeForLgh] [decimal] (18, 0) NOT NULL,
[t1trc_company] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1trc_division] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1trc_fleet] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1MinCommodityCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1MinCommodityClass] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1MinOrderHdrnumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1WeekOfTheYear] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1CompletionDateOnly] [datetime] NOT NULL,
[t1mpp_type1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1mpp_type2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1mpp_type3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1mpp_type4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1NumberOfSplitsOnMove] [int] NOT NULL,
[t1NumberOfOrdersOnLeg] [int] NOT NULL,
[t1NumberOfInvoicesOnMove] [int] NOT NULL,
[t1YYYY_MM_DD_LghEndDT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1YYYY_MM_WWLghEndDT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1AllocRevMinusPay] [decimal] (18, 0) NOT NULL,
[t1AllocRevMinusPayPerTrvlMile] [decimal] (18, 0) NOT NULL,
[t1mpp_teamleader] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[t1CountofLoads] [int] NOT NULL
) ON [PRIMARY]
GO
