CREATE TABLE [dbo].[EXTRA_INFO_TAB]
(
[TAB_ID] [int] NOT NULL,
[EXTRA_ID] [int] NOT NULL,
[TAB_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [INX_EXTRA_INFO_TAB] ON [dbo].[EXTRA_INFO_TAB] ([TAB_ID], [EXTRA_ID]) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[EXTRA_INFO_TAB] TO [public]
GO
GRANT INSERT ON  [dbo].[EXTRA_INFO_TAB] TO [public]
GO
GRANT REFERENCES ON  [dbo].[EXTRA_INFO_TAB] TO [public]
GO
GRANT SELECT ON  [dbo].[EXTRA_INFO_TAB] TO [public]
GO
GRANT UPDATE ON  [dbo].[EXTRA_INFO_TAB] TO [public]
GO
