CREATE TABLE [dbo].[packinglist]
(
[fgt_number] [int] NULL,
[fgt_cmd_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fgt_weight] [float] NULL,
[fgt_weightunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fgt_count] [decimal] (10, 2) NULL,
[fgt_countunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fgt_volume] [float] NULL,
[fgt_volumeunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fgt_loadingmeters] [decimal] (12, 4) NULL,
[fgt_loadingmetersunit] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fgt_description] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fgt_additionl_description] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_code] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_name] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_hazardous] [int] NULL,
[cmd_imdg_class] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_imdg_subclass] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_haz_num] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_haz_class] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_haz_subclass] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cmd_adr_packaging_group] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[language] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbyname] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbyaddress1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbyaddress2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderby_primaryphone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderby_faxphone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbycity] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbyzip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbycountry] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbytaxid] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[orderbylanguage] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipperaddress1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipperaddress2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipper_primaryphone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipper_faxphone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippercity] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipperzip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippercountry] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippertaxid] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shipperlanguage] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consigneename] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consigneeaddress1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consigneeaddress2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consignee_primaryphone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consignee_faxphone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consigneecity] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consigneezip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consigneecountry] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consingneedoclanguage] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consigneetaxid] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billtoname] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billtoaddress1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billtoaddress2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billto_primaryphone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billto_faxphone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billtocity] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billtozip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billtotaxid] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billtodoclanguage] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billtocountry] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[doc_language] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stoplanguage] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEFAULT_LANGUAGE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountryLanguage] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[brn_niwodid] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[brn_name] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[brn_add1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[brn_add2] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[brn_city] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[brn_state] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[brn_zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[brn_country] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_origin_earliestdate] [datetime] NULL,
[ord_origin_latestdate] [datetime] NULL,
[ord_dest_earliestdate] [datetime] NULL,
[ord_dest_latestdate] [datetime] NULL,
[ord_number] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_hdrnumber] [int] NULL,
[ord_bookedby] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usr_contact_number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_remark] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ord_terms] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_comment] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_cod_amount] [decimal] (8, 2) NULL,
[CODTEXT] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_cod_currency] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stp_number] [int] NULL,
[ref_number] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[drop_reference] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pickup_reference] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USERID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
GRANT DELETE ON  [dbo].[packinglist] TO [public]
GO
GRANT INSERT ON  [dbo].[packinglist] TO [public]
GO
GRANT REFERENCES ON  [dbo].[packinglist] TO [public]
GO
GRANT SELECT ON  [dbo].[packinglist] TO [public]
GO
GRANT UPDATE ON  [dbo].[packinglist] TO [public]
GO
